### ISSUE TITLE
immich_postgres healthcheck not working

### ISSUE THREAD

**Issue by PotatoPTT** [immich-app/immich#10134] opened 2024-06-11 13:54 UTC
### The bug

In the latest dockercompose was added a healthcheck but in immich_postgres
`SELECT SUM(checksum_failures) FROM pg_stat_database` returns NULL not 0, so the healthcheck fails every time
For a temporary solution i just changed to `SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database`

### The OS that Immich Server is running on

Docker/Non Relatable

### Version of Immich Server

v1.106.1

### Version of Immich Mobile App

v1.106.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
database:
    container_name: immich_postgres
    image: ${IMMICH_POSTGRES}
    env_file:
      - .env
    networks:
      - non_exposed
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT SUM(checksum_failures) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    labels:
      - 'wud.watch=false'
```

### Your .env content

```Shell
NON RELATABLE
```

### Reproduction steps

```bash
1. Run the container
2. Wait 5 minutes
3. Healthcheck fails
```

**Comment by AngelaDMerkel** [comment] 2024-06-11 15:02
I am also experiencing this issue

**Comment by dsquare86** [comment] 2024-06-11 15:38
Same issue on micro services and postgres

**Comment by zaggash** [comment] 2024-06-11 15:52
This is not a bug.
You are using running the DB without checksum.
So do not use the new test.

You can however, backup the DB, then create a new one with the new env POSTGRES_INITDB_ARGS: '--data-checksums'.
Then restore the DB.

You database will be recreated with checksum enabled and the new healthcheck will work.

**Comment by lo97** [comment] 2024-06-11 18:09
> This is not a bug. You are using running the DB without checksum. So do not use the new test.
> 
> You can however, backup the DB, then create a new one with the new env POSTGRES_INITDB_ARGS: '--data-checksums'. Then restore the DB.
> 
> You database will be recreated with checksum enabled and the new healthcheck will work.

How should we backup the DB, create a new one and restore it? Does anyone have a step by step guide?

**Comment by Tractor777** [comment] 2024-06-11 18:26
Will this work? https://immich.app/docs/administration/backup-and-restore/#:~:text=The%20recommended%20way%20to%20backup,to%20use%20the%20pg_dumpall%20command.

**Comment by PotatoPTT** [comment] 2024-06-11 19:11
> This is not a bug. You are using running the DB without checksum. So do not use the new test.
> 
> You can however, backup the DB, then create a new one with the new env POSTGRES_INITDB_ARGS: '--data-checksums'. Then restore the DB.
> 
> You database will be recreated with checksum enabled and the new healthcheck will work.

**Comment by mertalev** [comment] 2024-06-11 23:53
I think this should be fixed. The health check shouldn’t report Postgres as unhealthy unless it has a reason to think it is. Adding a COALESCE would make it more elegant for existing databases (and generally for users who disable checksums).

**Comment by zaggash** [comment] 2024-06-11 23:55
It is written in the documentation FAQ
I agree it deserves more visibility

https://immich.app/docs/FAQ#how-can-i-verify-the-integrity-of-my-database

**Closed** 2024-06-12 00:18 UTC
