### ISSUE TITLE
Camcorder videos using number of frames for duration

### ISSUE THREAD

**Issue by Hixxey** [immich-app/immich#11530] opened 2024-08-02 08:54 UTC
### The bug

Immich appears to be using the number of frames for the video length, but only for videos recorded using my Sony AX43 camcorder.
I noticed that in the below example the video shows 38:24 
<img width="542" alt="Screenshot 2024-08-02 094421" src="https://github.com/user-attachments/assets/4e19f2a6-c8b4-4113-9615-364e861b4930">
but the actual length is 1:32.
<img width="872" alt="Screenshot 2024-08-02 094447" src="https://github.com/user-attachments/assets/db19aa71-046f-48b3-9ea8-3e1cd8ede4e8">
35 minutes 24 seconds converted to seconds is 2304.
The videos are 25fps so that would be 2304/25 = 92.16 (1.54 Minutes = 1 Minute and 32 Seconds)
<img width="296" alt="Screenshot 2024-08-02 094632" src="https://github.com/user-attachments/assets/ecea1182-e933-41e2-9455-2fda7571232f">
It looks to me like it might need to use a different value from the metadata, but I'm not sure which would be best.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0 build.167

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #command: [ "start.sh", "immich" ]
    volumes:
      - ./immich/library:/usr/src/app/upload/library
      - ./immich/cache/upload:/usr/src/app/upload/upload
      - ./immich/cache/thumbs:/usr/src/app/upload/thumbs
      - ./immich/cache/profile:/usr/src/app/upload/profile
      - ./immich/cache/encoded-video:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
      - ${HOMEDATA}/Pictures:/photos:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    environment:
      DB_USERNAME: ${ADMIN_USER}
      DB_PASSWORD: ${ADMIN_PASSWORD}
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich_postgres
      REDIS_HOSTNAME: immich_redis
      TZ: ${TIMEZONE}
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    labels:
      autoheal-app: true
  
  immich-machine-learning: #needs to be hyphenated otherwise the url doesn't work
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./immich/library:/usr/src/app/upload/library
      - ./immich/cache/upload:/usr/src/app/upload/upload
      - ./immich/cache/thumbs:/usr/src/app/upload/thumbs
      - ./immich/cache/profile:/usr/src/app/upload/profile
      - ./immich/cache/encoded-video:/usr/src/app/upload/encoded-video
      - ./immich-machine-learning/model-cache:/cache
    restart: always
    environment:
      TZ: ${TIMEZONE}
    labels:
      autoheal-app: true
  
  immich_redis:
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    container_name: immich_redis
    restart: always
    environment:
      TZ: ${TIMEZONE}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./immich-redis:/data
    labels:
      autoheal-app: true
  
  immich_postgres:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
      - "5432:5432"
    volumes:
      - ./immich-postgres:/var/lib/postgresql/data
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    labels:
      autoheal-app: true
```

### Your .env content

```Shell
IMMICH_VERSION=v1.111.0
ADMIN_USER=***
ADMIN_PASSWORD=*********
USER_ID=1000
GROUP_ID=1000
TIMEZONE="Europe/London"
HOMEDATA="/mnt/home"
```

### Reproduction steps

```bash
1. Upload an image from a camcorder. Other users have reported Sony a6300 and a7iii mirrorless cameras. My camera is the Sony AX43.
2. View the thumbnail in Immich, it will display the number of frames as the duration
```

**Comment by bo0tzz** [comment] 2024-08-02 12:03
We use the `Duration` tag as provided by exiftool. Can you run exiftool on the original file and post the full output here?

**Comment by Hixxey** [comment] 2024-08-02 12:13
> We use the `Duration` tag as provided by exiftool. Can you run exiftool on the original file and post the full output here?

File name: 22-03-03-14-50 1.MP4 (ExifTool)

>>> Composite <<<

AvgBitrate : 60.9 Mbps
ImageSize : 3840x2160
Megapixels : 8.3
Rotation : 0


>>> File <<<

Directory : /data/Videos/2022/03/03
FileAccessDate : 2024:05:30 17:08:31+01:00
FileInodeChangeDate : 2024:05:30 17:08:26+01:00
FileModifyDate : 2022:03:03 14:51:38+00:00
FileName : 22-03-03-14-50 1.MP4
FilePermissions : -rwxrwxrwx
FileSize : 701 MB
FileType : MP4
FileTypeExtension : mp4
MIMEType : video/mp4


>>> QuickTime <<<

AudioAttributes : (none)
AudioAvgBitrate : 1.54 Mbps
AudioBitsPerSample : 16
AudioChannels : 2
AudioCodec : twos
AudioFormat : twos
AudioMaxBitrate : 1.54 Mbps
AudioSampleRate : 48000
AudioTrackID : 2
Balance : 0
BitDepth : 24
CompatibleBrands : XAVC, mp42, iso2
CompressorID : avc1
CompressorName : AVC Coding
ContentDescribes : Track 1
CreateDate : 2022:03:03 14:50:05
CurrentTime : 0 s
Duration : 0:01:32
FileFunctionFlags : Additional tracks
GraphicsMode : srcCopy
HandlerDescription : Non-Real Time Metadata
HandlerType : Video Track
ImageHeight : 2160
ImageWidth : 3840
MajorBrand : Sony XAVC
MatrixStructure : 1 0 0 0 1 0 0 0 1
MediaCreateDate : 2022:03:03 14:50:05
MediaDataOffset : 192
MediaDataSize : 701411621
MediaDuration : 0:01:32
MediaHeaderVersion : 0
MediaLanguageCode : und
MediaModifyDate : 2022:03:03 14:50:05
MediaTimeScale : 48000
MetaFormat : rtmd
MinorVersion : 100.1f.ff
ModifyDate : 2022:03:03 14:50:05
MovieHeaderVersion : 0
NextTrackID : 4
OpColor : 0 0 0
PixelAspectRatio : 1:1
PosterTime : 0 s
PreferredRate : 1
PreferredVolume : 100.00%
PreviewDuration : 0 s
PreviewTime : 0 s
SelectionDuration : 0 s
SelectionTime : 0 s
SourceImageHeight : 2160
SourceImageWidth : 3840
TimeScale : 90000
TimeZone : +00:00
TrackCreateDate : 2022:03:03 14:50:05
TrackDuration : 0:01:32
TrackHeaderVersion : 0
TrackID : 2
TrackLayer : 0
TrackModifyDate : 2022:03:03 14:50:05
TrackProperty : Main track; No attributes; Priority 0
TrackVolume : 100.00%
VideoAttributes : Variable bitrate, [16], [17]
VideoAvgBitrate : 60 Mbps
VideoAvgFrameRate : 25
VideoCodec : avc1
VideoFrameRate : 25
VideoMaxBitrate : 60 Mbps
VideoMaxFrameRate : 25
VideoSize : 3840x2160
VideoTrackID : 1
XResolution : 72
YResolution : 72


>>> XML <<<

AudioFormatAudioRecPortAudioCodec : LPCM16, LPCM16
AudioFormatAudioRecPortPort : DIRECT, DIRECT
AudioFormatAudioRecPortTrackDst : CH1, CH2
AudioFormatNumOfChannel : 2
CreationDateValue : 2022:03:03 14:50:05Z
DeviceManufacturer : Sony
DeviceModelName : FDR-AX43
DeviceSerialNo : 4294967295
DurationValue : 2304
LastUpdate : 2022:03:03 14:50:05Z
LtcChangeTableHalfStep : false
LtcChangeTableLtcChangeFrameCount : 0, 2303
LtcChangeTableLtcChangeStatus : increment, end
LtcChangeTableLtcChangeValue : 08160000, 11480100
LtcChangeTableTcFps : 25
RecordingModeCacheRec : false
RecordingModeType : normal
TargetMaterialUmidRef : 060A2B340101010501010D431300000036763C9E419605D29C50D1FFFE913BD1
VideoFormatVideoFrameCaptureFps : 25p
VideoFormatVideoFrameFormatFps : 25p
VideoFormatVideoFrameVideoCodec : AVC_3840_2160_HP@L51
VideoFormatVideoLayoutAspectRatio : 16:9
VideoFormatVideoLayoutNumOfVerticalLine : 2160
VideoFormatVideoLayoutPixel : 3840
VideoFormatVideoRecPortPort : DIRECT

**Comment by bo0tzz** [comment] 2024-08-02 12:38
Duplicate of #8244, I'll ask you follow up questions in there if that's OK.

**Closed by bo0tzz** 2024-08-02 12:38 UTC
