### ISSUE TITLE
shared albums not showing up on mobile app

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3179] opened 2023-07-09 16:00 UTC
### The bug

I had to reinstall the mobile app on my partner's phone for the shared albums to show up. There was nothing in the logs except something stating a refresh of albums was already in progress.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

1.66.0 build.106

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by waclaw66** [comment] 2023-07-22 08:17
Can confirm, shared albums are not showing.

**Comment by waclaw66** [comment] 2023-08-07 12:37
I think it's already fixed.

**Comment by SteffenAuer** [comment] 2023-09-13 06:02
I'm still experiencing this issue. I have a bunch of albums that I own and share with my partner. Whenever I add a new image to one of them, they will not show up on her device. Neither the logs in the app nor the server container show anything in this context. The only remedy that helped was indeed reinstalling the app. Merely logging out and back in did not solve it.
On my device however, they show up almost immediately. So I add a new image to a shared album using the web interface, check my app and they're there. I assume it's because I own these albums so they are refreshed in a different manner..?

**Comment by jensfriisnielsen** [comment] 2023-10-21 19:55
I also experience this with my partners mobile app. I'm on version 1.82.1

**Comment by alextran1502** [comment] 2023-10-21 23:53
@jensfriisnielsen Hello, can you help log out and log back in?

**Comment by jensfriisnielsen** [comment] 2023-10-22 06:49
Thanks @alextran1502 that did the trick. After logging back in and waiting for the spinner to stop all my shared albums appeared on my partners mobile app.

And thank you for a great piece of software @alextran1502. Immich is exactly what I was missing since my kids were born. :clap: :1st_place_medal:

**Comment by tmorgan497** [comment] 2023-11-01 01:42
My partner and I are also experiencing a similar issue on mobile. She can't see any of my photos or shared albums in the mobile app, but she can see them on the webapp no problem. Also tried logging out and logging back in on both devices. The only message on screen is "It seems <partner> does not have any photos... Or your server version does not match the app version." 

We are both 1.83.0 on mobile, and the server is also on 1.83.0.

**Comment by alextran1502** [comment] 2023-11-01 02:23
@tmorgan497 can you capture the screenshot? If both phones cannot get any images, perhaps it is proxy issue? Do you mind connect to the instance over local IP for testing

**Comment by mjr128** [comment] 2023-11-01 14:12
I also experienced the same issue. Resolved by adding a new shared album from the mobile which didn't see the shared album. After that the list of shared albums updated and the albums appeared.

I tried this after disconnected/reconnected and reinstalled the application on IOS v1.83.0 build .123

I suppose this is just a cache issue.

**Comment by tmorgan497** [comment] 2023-11-02 01:04
@alextran1502 

Here are screenshots from my wife's phone showing the server url, versions, and what happens when I click on shared photos

![IMG_20231101_195948.jpg](https://github.com/immich-app/immich/assets/21185911/730f37bc-19fd-4ca5-835d-281a35564e96)

![IMG_20231101_195944.jpg](https://github.com/immich-app/immich/assets/21185911/c6cfb1d1-d05c-4a3a-931b-16d4ce15744e)


And the corresponding screenshots from my phone:
![Screenshot_20231101-200302.png](https://github.com/immich-app/immich/assets/21185911/0835184d-5dd8-47c9-8c25-4e11237e7802)

![Screenshot_20231101-195733.png](https://github.com/immich-app/immich/assets/21185911/c85c312d-b12b-4724-8ac7-978c9de92c2f)



I will try what @mjr128 suggested. Hopefully it's just a cache thing.

**Comment by alextran1502** [comment] 2023-11-02 01:06
@tmorgan497 Can you help grab the log of the mobile app from both phones?

**Comment by tmorgan497** [comment] 2023-11-02 01:16
@alextran1502 unfortunately I already cleared the cache/reinstalled on both devices 😬 which did seem to fix the issue. I can try to replicate it and report back with the logs.

**Comment by tmorgan497** [comment] 2023-11-02 01:43
@alextran1502 I was able to replicate the issue again by removing her as my partner, then reinstalling the app on her phone, then adding her back as my partner. To fix the issue, I reinstalled the app again. I also verified that she can see the shared photos on the web app. I attached the log from her phone when the issue occurred, but to me it doesn't seem to indicate anything about the sharing issue. 

[Immich_log_2023-11-01T20 31 08.689614.csv](https://github.com/immich-app/immich/files/13233222/Immich_log_2023-11-01T20.31.08.689614.csv)

**Comment by fyfrey** [comment] 2023-11-05 09:34
Weird, the log neither contains a "Load partner assets" message nor an error. I think we need to add more logging to figure out the issue.

**Comment by OlegLoewen** [comment] 2023-11-05 16:12
I have the same issue. 

1. On my device, I shared my photos to my partner on mobile.
2. After partner logs in on mobile, immich server isn't reachable.
3. On web I can see partner photos with no issues.

**Comment by alextran1502** [comment] 2023-11-05 16:31
@OlegLoewen did you use the partner sharing feature? 

Can you elaborate on point number 2 as the Immich server isn't reachable, is it from the login page, or did the server crash after you logged in?

**Comment by OlegLoewen** [comment] 2023-11-05 17:37
@alextran1502 , 
yes I configured the partner sharing feature for the very first time. 
Regarding point number 2: after partner sharing has been configured, if I navigate to partner directory (on any mobile phone), then immich isn't reachable neither in web, nor on mobile. Where/how can I provide the right logs to you?

**Comment by alextran1502** [comment] 2023-11-05 17:45
@OlegLoewen you can pull the mobile app logs, and the server logs

**Comment by OlegLoewen** [comment] 2023-11-05 18:36
sure, here you go (btw. machine learning is disabled):
[Immich_log_2023-11-05T18_47_25.425932.csv](https://github.com/immich-app/immich/files/13260480/Immich_log_2023-11-05T18_47_25.425932.csv)
[_immich_web_logs.txt](https://github.com/immich-app/immich/files/13260481/_immich_web_logs.txt)
[_immich_server_logs.txt](https://github.com/immich-app/immich/files/13260482/_immich_server_logs.txt)
[_immich_proxy_logs.txt](https://github.com/immich-app/immich/files/13260483/_immich_proxy_logs.txt)
[_immich_microservices_logs.txt](https://github.com/immich-app/immich/files/13260484/_immich_microservices_logs.txt)

**Comment by OlegLoewen** [comment] 2023-11-07 08:28
@alextran1502 any progress here? Or do you need further logs?

**Comment by mirisbowring** [comment] 2023-11-12 11:44
I also have the same problem on shared albums. We are around 8 Users on the instance and it seems like the refresh is only working for me (admin user) - I also am the only with an iOS - if there could be a difference

**Comment by fyfrey** [comment] 2023-11-12 15:07
relevant part of the server log:

> [Nest] 6  - 11/05/2023, 2:35:28 PM   ERROR [ExceptionsHandler] duplicate key value violates unique constraint "PK_f1cc8f73d16b367f426261a8736"
QueryFailedError: duplicate key value violates unique constraint "PK_f1cc8f73d16b367f426261a8736"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:140:21)
    at async PartnerRepository.create (/usr/src/app/dist/infra/repositories/partner.repository.js:31:9)
    at async PartnerService.create (/usr/src/app/dist/domain/partner/partner.service.js:29:25)

and maybe

> [Nest] 6  - 11/05/2023, 3:39:46 PM   ERROR [ExpressAdapter] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:406:5)
    at ServerResponse.onclose (node:internal/streams/end-of-stream:159:30)
    at ServerResponse.emit (node:events:526:35)
    at emitCloseNT (node:_http_server:1023:10)
    at Socket.onServerResponseClose (node:_http_server:278:5)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:337:12)


the app log shows the following severe errors (504 on the server):

> 2023-11-05 18:35:48.484735,LogLevel.SEVERE,"AssetService","Error while getting remote assets: ApiException 504

> 2023-11-05 15:39:43.236322,LogLevel.WARNING,"UserService","Failed get all users:
ApiException 504

and as a consequence:

> 2023-11-05 14:44:29.398949,LogLevel.SEVERE,"ImmichErrorLogger","Catch all error:  - Key 'currentUser' not found in Store

@OlegLoewen it seems your Immich server was not reachable by your proxy server and this resulted in issues.

**Comment by fyfrey** [comment] 2023-11-12 15:10
> I also have the same problem on shared albums. We are around 8 Users on the instance and it seems like the refresh is only working for me (admin user) - I also am the only with an iOS - if there could be a difference

please also provide the app and server logs (please clear the logs, restart the app and reproduce the issue, then share the logs). thank you

**Comment by archive-r** [comment] 2023-11-22 03:43
Same issue in IOS. I'll upload the logs when I get home.

**Comment by archive-r** [comment] 2023-11-22 12:31
> Same issue in IOS. I'll upload the logs later

This issue appears to have been resolved in v1.88.2. Shared albums are now displayed correctly in the app.

**Closed** 2023-12-04 16:22 UTC
Labels: bug, 📱mobile

**Comment by taoyx** [comment] 2024-11-08 19:56
even on the latest version 1.220.1, I still found this issue. 

I tried with logging out and logging in, no luck

**Comment by alextran1502** [comment] 2024-11-08 21:22
@taoyx This issue has closed, so I'd appreciate if you can open a new issue and post the relevant logs and information so we can troubleshoot
