### ISSUE TITLE
[UI] Unnatural date format used in search

### ISSUE THREAD

**Issue by null-von-sushi** [immich-app/immich#10992] opened 2024-07-10 09:41 UTC
### The bug

Searching currently requires users to enter the date in MM/DD/YYYY format. While I understand that immich is American software, it has users around the world and the majority of the word works in either ascending or descending order (DD/MM/YYYY for the west, YYYY/MM/DD for the east). 
Please would you consider implementing a setting that allows us to specify the date in either of the two?
Thank you for your consideration

### The OS that Immich Server is running on

TrueNAS

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not sure, I did not use docker. TrueNAS abstracts all this in it's webui when installing apps...
```

### Your .env content

```Shell
Same as above.
```

### Reproduction steps

```
1. Open your immich instance's website
2. Click the settings icon next to the search bar at the top
3. Observe the date input field asking for MM/DD/YYYY
```

### Relevant log output

```shell
N/A
```

**Comment by bo0tzz** [comment] 2024-07-10 10:29
This should probably be changed to use the locale from the user settings.

**Comment by michelheusschen** [comment] 2024-07-10 10:32
The date format is already based on the configured language and nothing is forcing the date format to be `mm/dd/yyyy`. When I set my language to Japanese for example, the date format changes:

![image](https://github.com/immich-app/immich/assets/59014050/eedadbf4-0fa1-4c28-aa82-5a2bbd131b56)

**Comment by bo0tzz** [comment] 2024-07-10 10:42
@michelheusschen it should be based on locale, not language.

**Comment by andrebrait** [comment] 2024-07-12 06:26
Yes, I second that. Language and locale aren't the same thing and date format here should be derived from locale (e.g. en-GB and en-IE use dd/mm/yyyy, whereas en-US uses mm/dd/yyyy)

**Comment by WhiteWoodenWall** [comment] 2024-08-16 23:26
if I change both my language and custom locale to Japanese, I am still presented with the mm/dd/yyyy format. Perhaps the default browser locale/language setting is taking priority?

**Comment by danieldietzler** [comment] 2024-09-21 18:57
@WhiteWoodenWall correct, that is browser-dependent. Also, this issue is a duplicate of #8781 from a technical standpoint

**Closed by danieldietzler** 2024-09-21 18:57 UTC
Labels: good first issue, 🖥️web
