### ISSUE TITLE
[BUG] Counter does not display correctly during Backup

### ISSUE THREAD

**Issue by assid2** [immich-app/immich#894] opened 2022-10-30 05:58 UTC
**Describe the bug**
While Backup takes place, the total and remainder is updated, but the number of backed up assets do not.

**To Reproduce**
1. Go to 'Backup'
2. Click on 'Start Backup'
3. See the counters move , Total and Remainder gets updated, whilst Backup does not.

**Expected behavior**
Counter should work correctly.

**Screenshots**
https://photos.app.goo.gl/NfHhx5CyBK8iXPa68

**System**
- Phone OS [iOS, Android]: `Android`
- Server Version: `1.33.0`
- Mobile App Version: `Current as per play store, fresh install on 2022-10-30, device not available at the moment.`

**Comment by alextran1502** [comment] 2022-12-27 20:19
Hello is this issue still relevant?

**Comment by brayStorm** [comment] 2023-01-16 23:35
Yes.![image](https://user-images.githubusercontent.com/20567279/212780323-ae51e921-d1d1-48c4-90b5-49faea714b4b.jpeg)

**Comment by MingoDynasty** [comment] 2023-02-07 06:12
I get the same issue.
![Screenshot_20230206-220737](https://user-images.githubusercontent.com/7714548/217162780-dc886583-309f-4967-94cc-b25143328374.jpg)

**Comment by JavaSCU** [comment] 2023-03-03 13:28
same 
![Uploading Screenshot_2023-03-03-21-25-00-895-edit_app.alextran.immich.jpg…]()
![Uploading Screenshot_2023-03-03-21-25-00-896-edit_app.alextran.immich.jpg…]()

**Comment by JavaSCU** [comment] 2023-03-03 13:29
same 
![Uploading Screenshot_2023-03-03-21-25-00-895-edit_app.alextran.immich.jpg…]()
![Uploading Screenshot_2023-03-03-21-25-00-896-edit_app.alextran.immich.jpg…]()

**Comment by wardpieters** [comment] 2023-05-09 14:58
Experiencing the same issue.

App: 1.55.0 build 78
Server: 1.55.0

![image](https://github.com/immich-app/immich/assets/19374765/1efe5f86-ec5a-4fb0-991d-5735eab6617f)

**Comment by PriZZZrak** [comment] 2023-06-19 12:25
v1.61.0 Bug is there

**Comment by jrasm91** [comment] 2023-10-26 19:29
Going to go ahead and close this as a duplicate of #968, which has more details.

**Closed by jrasm91** 2023-10-26 19:29 UTC
Labels: bug, 📱mobile
