### ISSUE TITLE
Feature picture missing, causing the entire person to go missing from the "people" tab

### ISSUE THREAD

**Issue by madson007** [immich-app/immich#9732] opened 2024-05-24 16:02 UTC
### The bug

When going through random photo's, there will be people tagged without a feature photo. These people don't show up in the "people" tab.
If i give a blank image person a name, i can find them in the people tag when searching for them.
Manually selecting a feature photo fixes the entire problem.

Additional findings:
When setting a feature photo to a video -> will set the feature photo to a blank (broken) image. (maybe the face recognition job tries to set the initial feature photo to that from a video)

![image2](https://github.com/immich-app/immich/assets/7085286/05a0bfef-03e0-430d-bd72-549325f4c1b8)
![image](https://github.com/immich-app/immich/assets/7085286/9c8702e1-6f37-4d58-a0ae-a0e62a1a8ac7)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

1.105.0 build 139

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Network: bridge
image: ghcr.io/imagegenius/immich
```

### Your .env content

```Shell
WebUI:2284
DB_HOSTNAME: <internal ip>

PostgreSQL Host
DB_USERNAME:postgres
DB_PASSWORD:<passw>
DB_DATABASE_NAME: immich
REDIS_HOSTNAME:localhost
DB_PORT:5433
REDIS_PORT:6379
REDIS_PASSWORD:
MACHINE_LEARNING_GPU_ACCELERATION:
MACHINE_LEARNING_WORKERS:1
MACHINE_LEARNING_WORKER_TIMEOUT:120
DOCKER_MODS:imagegenius/mods:universal-redis
```

### Reproduction steps

```bash
1.upload files to server via phone app
2.go through random photo's and see tagged people in the info tab without feature photo
3.Go to this user -> manually select feature photo -> fixes it
4.Selecting a feature photo -> then selecting a video causes an blank feature photo
```

**Comment by danieldietzler** [comment] 2024-09-21 18:25
Hey, is this on the latest version still an issue?

**Comment by bverkron** [comment] 2024-12-02 18:15
@danieldietzler I am having the same issue right now on the latest version. 1.21.1

**Comment by danieldietzler** [comment] 2024-12-02 18:32
Did you re-run face recognition or thumbnail generation on all assets to make sure it's actually still an issue? @bverkron

**Comment by bverkron** [comment] 2024-12-02 20:11
I ran into the issue under a fresh Immich account with a fresh set of uploaded images and it's been over 12 hours since they were uploaded and the Tasks section did not show anything was still running so I assume that has all happened freshly on these images already.

Despite that I am manually re-running face detection using the refresh option (which is by proxy re-running face recognition). Will also run thumbnail refresh after if that does not fix it. Will report back.

**Comment by bverkron** [comment] 2024-12-02 21:57
Regenerating thumbnails fixed it, but I'm not sure why. There is a bit more to my scenario I just realized, which might explain it.

I am publishing photos to Immich from Lightroom Classic and some of these photos have face detection already embedded. I have Immich set to extract this info. When a "new" face / person comes into Immich via that metadata it comes in without the person's face thumbnail. This makes some sense being that Immich did not add this info itself and thus does not already have a face associated with that person. However, this is still true even with images that were already in Immich and already had a thumbnail but just had a new person tagged in Lightroom and then pushed to the existing photo in Immich. I can see that being "by design" for the most part and it not generating the persons face thumbnail until the thumbnail task has run,.

However, I don't understand why people without face thumbnails don't show in the Person view. Is that by design? If something is detected as a Person (in this case via external data read in when the photo comes into Immich or has new metadata pushed) should it not still show up in the Person view so it can be dealt with by the user? i.e. have a face thumb manually selected or have it merged with an existing person?

As-is there is no way to even find these and deal with them unless you go directly to a photo and view the info ℹ️ panel and see the person without the face thumbnail and click into it... or manually re-run thumbnail generation.

**Comment by mertalev** [comment] 2024-12-02 22:14
1. I agree with this
2. Person thumbnail generation for faces coming from metadata is currently buggy and tracked in #12440. Re-selecting the thumbnail for a person (even the same image) fixes it

**Comment by bverkron** [comment] 2024-12-02 22:19
Great info, thanks for the very quick response!

Side note. Immich is absolutely amazing. One of the best self-hosted products I've ever used with one of the most responsive dev teams. I am super looking forward fully adopting it into my workflow paying for a license once I iron all the kinks in the workflow.

Amazing job everyone.

**Closed** 2024-12-03 20:04 UTC
