### ISSUE TITLE
[BUG] Blurry thumbnails when zoomed in

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#2749] opened 2023-06-13 09:44 UTC
### The bug

Lots of devices with high resolution displays will increase the UI size by default to increase legibility. This means that if `devicePixelRatio` > 1, Immich thumbnails are blurry. It might be better to support dynamic thumbnail generation depending on the resolution required by the client. This can be achieved with reasonable performance using something like [groupcache](https://github.com/golang/groupcache), and is one the base [examples](https://go.dev/talks/2013/oscon-dl.slide#46) Google used when it was introduced. I actually wrote this exact thing for a project about a decade ago [here](https://github.com/uhthomas/sana/blob/archive/route/thumbnailhandler.go).

### The OS that Immich Server is running on

N/A

### Version of Immich Server

1.60.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Zoom into Immich on the web
2. Observe blurry thumbnails
```

**Comment by mertalev** [comment] 2023-08-16 04:54
This issue can be closed as thumbnail sizes are now customizable.

**Closed by mertalev** 2023-08-16 04:54 UTC
Labels: bug, 🖥️web, 🗄️server

**Comment by mertalev** [comment] 2023-08-16 16:10
That's a feature request, not a bug. The problem of blurry thumbnails is fixed.

**Comment by jrasm91** [comment] 2023-08-16 16:14
IMO I think being able to customize thumbnail settings solves this in the short-term and mid-term. I agree we might want a better approach form thumbnails long-term though. What you are talking about here sounds more about an entire overhaul of the thumbnail implementation/strategy/approach, which will obviously require a lot more thought. A github discsussion sounds like an appropriate place to track it.
