### ISSUE TITLE
photo type support problem  & request(.pic file not support)

### ISSUE THREAD

**Issue by everlo** [immich-app/immich#14906] opened 2024-12-24 12:11 UTC
### The bug

I use the mobile UI in iphone 12 immich app version is v1.123.0. 
I choose a folder in my phone to upload photos to server. there is a .pic type photo(maybe have more....), the log shows "unsupported file type xxxx.pic";
after the fail log, the upload task can't continue. In addtion, I cancelled and tried many times but failed.
Sinserelly want the project can repair this bug, or give remain method to help me upload my photos. thanks very much.

### The OS that Immich Server is running on

ubuntu 22.0

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not neserry for this issue.
```

### Your .env content

```Shell
not neserry for this issue.
```

### Reproduction steps

1.I use the mobile UI in iphone 12 immich app version is v1.123.0. 
2.I choose a folder in my phone to upload photos to server. there is a .pic type photo(maybe have more....), the log shows "unsupported file type xxxx.pic";
3.after the fail log, the upload task can't continue. In addtion, I cancelled and tried many times but failed.
Sinserelly want the project can repair this bug, or give remain method to help me upload my photos. thanks very much.

### Relevant log output

```shell
not nessesary
```

### Additional information

not nessesary

**Comment by bo0tzz** [comment] 2024-12-24 12:51
Dupe of #6173

**Closed by bo0tzz** 2024-12-24 12:51 UTC
