### ISSUE TITLE
[BUG] Stuck building timeline

### ISSUE THREAD

**Issue by JasperVanEsveld** [immich-app/immich#1497] opened 2023-01-31 20:14 UTC
**Describe the bug**
Setup immich today, it worked nicely, could backup and view my photo's.

After sometime it prompted me to log back in (even though I checked stay logged in)
Now the timeline is stuck building, I can still search and view albums.

**To Reproduce**
1. Open mobile app
2. Close and wait till opening prompts login
3. Building timeline no longer stops 

**Expected behavior**
Maybe load for some time, and then display the photo's/videos

**System**
- Phone OS [Android]: `13`
- Server Version: `1.43.1`
- Mobile App Version: `1.43.0 build 66`

**Comment by JasperVanEsveld** [comment] 2023-01-31 20:21
Just checked if a phone restart would help, it did not.
Web view works fine

**Comment by jrasm91** [comment] 2023-01-31 21:39
I think I've experienced this myself. Does logging out and then back in change anything?

**Comment by JasperVanEsveld** [comment] 2023-01-31 21:54
Oh yea, that fixed it thanks!

Think I will still leave this open, as it is still a bug.
But at least one with a simple work around :)

**Comment by palitu** [comment] 2023-02-13 03:49
i too have had this issue

**Comment by gfrabetti** [comment] 2023-02-13 18:48
Same here. Tried on my phone with 1k pics and It worked like a charm, but when I tried on my wife's phone with almost 30k pics it uploaded all fine (webview works 100%) but I'm stuck at building the timeline. 

I tried restarting server, restarting phone, logging in and out...even tried logging in her account on my phone and it's all the same. When I check the logs on her account it's full of "Error while getting remote assets" errors.

**Comment by jrasm91** [comment] 2023-02-13 19:26
Often when there is a "Error while getting remote assets" error, it's due to the client/server being out of date. Make sure the server and mobile app are both up to date in this case.

**Comment by erlenddahl** [comment] 2023-02-16 12:15
I just experienced this same bug myself. Both server and app were up to date. I was logged out because I had deactivated my network connection (I think), so I reconnected and logged in, and then it said "Building timeline" for a few hours before I found this issue. After logging out and in again, it built the timeline in about a second.

**Comment by alextran1502** [comment] 2023-02-24 03:21
I've fixed this issue, please help me double check on the latest update 1.49

**Comment by jilles** [comment] 2023-03-03 14:38
I'm having this on server 1.50.1 and Android app 1.50.0 and about 150k pictures and 9k videos. Let me know what I can do to help debugging.

**Comment by alextran1502** [comment] 2023-03-29 15:12
This should be fixed in the v1.52 release

**Closed by alextran1502** 2023-03-29 15:12 UTC
Labels: bug

**Comment by wattsra** [comment] 2023-11-18 14:18
I'm getting this issue today on server version 1.87 and android app version 1.86 build 110

Is it a regression with the latest version?

**Comment by Symbiot78** [comment] 2024-01-13 18:29
seeing the same here on 1 iPhone. I've installed immich on 3 phones now and 2 just work. The last ( using my wife's account) just hangs there preparing timeline.

**Comment by figadore** [comment] 2024-02-28 02:31
I'm having this issue on 1.96.0. Logging out and back in doesn't appear to work

**Comment by alextran1502** [comment] 2024-02-28 03:31
@figadore Can you grab the log on her phone, did her phone finish the hashing process (circular loading icon on the bottom app bar)

**Comment by figadore** [comment] 2024-02-28 04:13
> finish the hashing process (circular loading icon on the bottom app bar)

Not sure about this one, attaching a screenshot that hopefully answers the question(?)

![image](https://github.com/immich-app/immich/assets/3253971/bda88311-f4ba-4c69-93dc-7e418f769207)

[Immich log Feb 27.csv](https://github.com/immich-app/immich/files/14428759/Immich.log.Feb.27.csv)

**Comment by figadore** [comment] 2024-02-28 04:45
Here are some logs with more details
[Immich logs debug Feb 27.csv](https://github.com/immich-app/immich/files/14428949/Immich.logs.debug.Feb.27.csv)

**Comment by alextran1502** [comment] 2024-02-28 05:03
@figadore There is an error of gathering the information of the album, I assume you have some assets on the server. Can you try kill the app and then open it again?

**Comment by figadore** [comment] 2024-02-28 14:42
> I assume you have some assets on the server. Can you try kill the app and then open it again?

There are a 267 assets, all from an external library. No albums created yet. I've killed the app multiple times, even uninstalled it

**Comment by alextran1502** [comment] 2024-02-28 15:32
@figadore are those assets on your account or your wife account? Did she select anything for backup on her phone?

**Comment by figadore** [comment] 2024-02-28 17:36
> @figadore are those assets on your account or your wife account? Did she select anything for backup on her phone?

Nothing is selected for backup on her phone, and the assets are on my account. If those are the cause, I'd say the progress spinner is a bit confusing.

Going down that road a bit further (but maybe this should be a separate issue), I couldn't find the sharing setting for "Show in timeline" on the mobile app, and it doesn't appear to _save_ when I toggle it in the web app (I toggle it, collapse the Sharing section, expand the sharing section, and it is untoggled again. I see nothing happening in the network tab, and nothing shows up in the js console).

**Comment by alextran1502** [comment] 2024-02-28 20:14
@figadore Ah, then this explains the observation. Since the assets are on your account, they will not appear on your wife's account. The current mechanism means that you will have to choose an album for backup to display those local assets on the timeline.

Showing timeline on the mobile app can be toggle by visiting the partner's page view from the Sharing tab and click on the bottom at the upper right hand corner

**Comment by figadore** [comment] 2024-02-28 20:25
@alextran1502 so the primary bug can be summarized as "Stuck 'Building timeline' when there are no photos to display" . Instead, it should show a message about "no photos" or "tap to upload your first photo" or something.

> Since the assets are on your account, they will not appear on your wife's account. 

This sounds like a secondary bug, where selecting "Show in timeline" for the partner sharing option does not work. It is still unclear whether this would prevent the initial bug from being encountered. For clarity, I'm talking about the feature mentioned in https://github.com/immich-app/immich/discussions/5692#discussioncomment-7850822 where the partner sharing photos should appear on the main timeline

**Comment by alextran1502** [comment] 2024-02-28 20:42
@figadore Did you enable shared in timeline from her account, so that she can see your photos?

**Comment by alextran1502** [comment] 2024-02-28 21:34
@figadore Confirm that the show in timeline toggle is bugging out. Will push out a fix soon

**Comment by keesfluitman** [comment] 2024-06-16 10:40
Can confirm that anyone with no photos themselves gets this in a loop.

**Comment by melyux** [comment] 2025-05-11 20:19
How do you upload a single photo? There's no upload button, Immich forces you to upload the entire album.

**Comment by alextran1502** [comment] 2025-05-11 22:50
@melyux choose the album that the asset is in. Don't press upload in the backup screen. Go to the main timeline and long press to select the asset you want to upload, there is an upload button at the bottom menu

**Comment by melyux** [comment] 2025-05-12 07:12
Ah okay, I had to force quit the app and open it and the timeline suddenly built all at once.
