### ISSUE TITLE
[BUG] Issue #1946 isn't fixed. Images still show double on mobile device.

### ISSUE THREAD

**Issue by florihupf** [immich-app/immich#2818] opened 2023-06-16 18:42 UTC
### The bug

But they are not uploaded twice to the server, so progress! :)

Also, I don't know how to reopen issues.

### The OS that Immich Server is running on

Truenas Scale

### Version of Immich Server

v1.61.1

### Version of Immich Mobile App

v1.61.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
stock
```

### Your .env content

```Shell
stock
```

### Reproduction steps

```bash
See orig. issue
```

**Comment by uhthomas** [comment] 2023-06-16 19:11
Duplicate of #1946. Thanks for letting us know!

**Closed by uhthomas** 2023-06-16 19:11 UTC
Labels: bug, need triage
