### ISSUE TITLE
Backup album is not selected when the content is emptied

### ISSUE THREAD

**Issue by t0rv1c** [immich-app/immich#13134] opened 2024-10-03 00:09 UTC
### The bug

Once photos are removed from a backup album, the "album" is not going to have its content backed up and synced when new files are created.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

Latest

### Version of Immich Mobile App

Latest

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

1. Take pictures on mobile device
2. Make sure the camera folder is selected as a location to back up in immich
3. Trigger the backup if not automated 
4. Once everything is uploaded to the server, delete all the photos from the device's camera folder

Now the folder is not synced anymore and you have to manually go select the "album" once new files have been created in the folder. The pictures you deleted from the device now appear blank with a exclamation mark in the timeline and the syncing seems broken even after selecting the album to be synced again. Toggling off and on background backup seems to re-enable the syncing...

**Comment by caetanoange** [comment] 2024-11-25 16:04
I have the same issue on my phone.

**Comment by bo0tzz** [comment] 2024-11-30 11:51
dupe of #7711

**Closed by bo0tzz** 2024-11-30 11:51 UTC
