### ISSUE TITLE
[Feature]: Use as gallery to show photos and videos directly from server

### ISSUE THREAD

**Issue by Txxicer** [immich-app/immich#541] opened 2022-08-27 17:54 UTC
### Feature detail

Hello,

this software is a great product to backup and store files from a mobile phone and to view them directly in the app or through the web interface. But I miss a big feature.

It would be nice if you could implement the function, that the software can use pictures and videos from a folder on a server, so that I can view the files in web interface or in the app.

### Platform

Server

**Comment by bo0tzz** [comment] 2022-08-27 18:08
I think this is a duplicate of #34

**Comment by alextran1502** [comment] 2022-08-28 01:16
Duplicated of #34

**Closed by alextran1502** 2022-08-28 01:16 UTC
Labels: feature, need triage
