### ISSUE TITLE
Index existing upload folder 

### ISSUE THREAD

**Issue by FelixHaimmerer** [immich-app/immich#714] opened 2022-09-18 08:36 UTC
### Feature detail

Hello there,

I really love this project and want to use it for all my photos. 

It would be great if there is a way to move all the pictures to the upload folder of the users. And then start a job to get Immich looking over the existing uploads, figure out whats new and add them to the database. Like a reindex of the uploads.

Thanks!

### Platform

Server

**Comment by bo0tzz** [comment] 2022-09-18 08:37
Duplicate of #7 and #34

**Closed by bo0tzz** 2022-09-18 08:37 UTC
Labels: feature, need triage
