### ISSUE TITLE
Date display wrong, homepage timeline is using UTC timezone however the photo time is correct in info page

### ISSUE THREAD

**Issue by MFYDev** [immich-app/immich#10417] opened 2024-06-17 02:31 UTC
### The bug

Hello, just upgraded to the latest v1.106.4, I just uploaded a photo which was taken on GMT-4 on June 16 however on the homepage this picture is displaying under tomorrow's date which is Jun 17, in the photo info page it is correct

### The OS that Immich Server is running on

ubuntu 22.04

### Version of Immich Server

1.106.4

### Version of Immich Mobile App

1.106.4

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - 2283:3001
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "0 */4 * * *"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
      BACKUP_KEEP_DAYS: 30
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=****

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=sjahvysifdgnwer87sjdhgkja
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=****
DB_USERNAME=postgres
DB_DATABASE_NAME=****

REDIS_HOSTNAME=immich_redis

PUBLIC_LOGIN_PAGE_MESSAGE="****"
```

### Reproduction steps

```bash
1.Upgrade to the latest version
2.My timezone is America/New_York, upload an image taken around 10pm
3.The image is displaying under tomorrow's date
...
```

**Comment by MFYDev** [comment] 2024-06-17 02:32
![image](https://github.com/immich-app/immich/assets/53750381/b7a0d9d4-ca10-45b7-9c16-7149d49e4517)
photo info is correct
However it is in tomorrow's date
![image](https://github.com/immich-app/immich/assets/53750381/da983293-5276-4340-a17a-6f9fbcf90877)

**Comment by bo0tzz** [comment] 2024-06-17 07:50
Can you try a force refresh/clearing your browser cache?

**Comment by MFYDev** [comment] 2024-06-17 13:36
> Can you try a force refresh/clearing your browser cache?

Hi, thank you for the response, I tried both incognito and normal model with cache cleared, still the same which is really weird

**Comment by snuq** [comment] 2024-06-17 18:30
Just installed Immich and running into the same problem (images are displayed in different 'day folder' than they should be).

In my case tho, the displayed dates are weird as well - for instance, one photo shows "Nov 23, 2023  Thu, 7:18 AM GMT-08:00", the photo was taken at 3:18 pm PST, and this is the time that the file modified date displays.  
The photo's original date and time exif data shows:  2023:11:23 15:18:57
so... it thinks that the exif/modified date is gmt and its subtracting 8 hours from that to get what it thinks is my time?

Also, some files that are in the wrong 'date folder' are showing in UTC timezone when i view the info.  These files appear to be mostly videos, and dont have any exif data.  like the other files, the date and time are displayed correctly when viewing the files in a file explorer.

**Comment by RanKKI** [comment] 2024-06-28 12:26
![image](https://github.com/immich-app/immich/assets/14053802/da456e92-23ec-42e6-a51a-d904f4a12ab2)

Same image, shows different date

**Comment by snuq** [comment] 2024-07-09 19:55
First off, my timezone is PDT, all photos were taken in that timezone, and the server is in that timezone.  GPS was disabled on my phone for all the photos and videos that were taken (i only enable it when im needing navigation).

First example:
I have an image dated Nov 23, 2023, 4:09 PM GMT-08:00, it shows this correctly in the info pane.
In the photo timeline, this image is placed in Nov 24, 2023.
Another image taken on same device from the same day - Nov 23, 2023 at 3:52 PM GMT-08:00 is in the correct day on the timeline. 

Second example:
Even worse are the videos, I have one actually taken on December 30th, 2023 at 8:47PM (as indicated by the date modified in the file) which shows in the timeline under December 31st, it thinks was taken at "Dec 31, 2023, 4:47 AM UTC" in the photo info.
In the Immich android app, this shows up in the correct date in the timeline, but when I check the image date it shows the (incorrect) decmber 31st at 4:47am.



One of the things I tried to make this work better was setting the 'TZ' environment variable to my timezonee... but somehow this makes it WORSE in some ways... it seems to have corrected the time display of images in the info pane (tho videos are still incorrect), but those images are now displayed in the wrong date on the timeline when they were correctly displayed before...


I also ran into another bug that appears related - when I tried to back up some photos from the android app, they ended up in folders with the incorrect date (in the same way as the timeline shows the incorrect date).

Honestly, I REALLY wish I could just force everything to be interpreted as my timezone unless gps data or timezones are SPECIFICALLY set in the files... this would resolve all of these problems i think.

**Comment by chodthewacko** [comment] 2024-07-11 21:30
just encountered this as well.  1.107.2
Like snuq, I am in new york.   many ipad videos are showing, on the web page, in UTC, causing any photos taken after 8pm to appear on the next day in the timeline.

On the android app, the videos appear in EST.
What really threw me off is that the arrow keys/cursor keys on the keyboard follow "EST order".
So if you have pic1, pic2, vid3, pic4, vid5   in chronological order,
on the web page you see:
July 5:
vid3 -> vid5
July 4:
pic1, pic2, pic4

which would make you think, if you hit 'right' when viewing vid3, you should go to vid5.  
You don't - it goes to pic4.

I originally hit right arrow 5 times expecing to go to the picture 5 "spaces" to the right, and it didn't.

**Comment by MFYDev** [comment] 2024-08-15 02:38
same issue is still happening now even if I set the TZ in the .env in the latest version today

**Comment by Thinkscape** [comment] 2024-08-15 23:46
Here's an example.

* My system time (and browser time) is AEST time zone `16 Aug 2024, 9:44 GMT+10:00`. 
* The photo is `15 Aug 2024 Thu, 09:12 GMT+10:00`
* All immich services are running with `TZ=Australia/Sydney` (which is GMT+10:00)
* Immich is showing the photo under `Today`


<img width="1512" alt="Screenshot 2024-08-16 at 9 38 40 AM" src="https://github.com/user-attachments/assets/f9213385-618b-46d0-b4c7-5776b8642766">
<img width="1502" alt="Screenshot 2024-08-16 at 9 38 46 AM" src="https://github.com/user-attachments/assets/444e469e-50b3-4591-ac0f-9d68ce74edfd">

**Comment by tjhorner** [comment] 2024-08-18 03:43
I am experiencing this as well.

<details>
<summary>Version info</summary>

Immich
[v1.112.1](https://github.com/immich-app/immich/releases/tag/v1.112.1)

ExifTool
12.91

Node.js
v20.16.0

Libvips
8.15.2

ImageMagick
7.1.1-24

FFmpeg
6.0.1-6

Repository
[immich-app/immich](https://github.com/immich-app/immich)

Source
[v1.112.1@f7bfde6a3](https://github.com/immich-app/immich/commit/f7bfde6a3286d4b454c2f05ccf354914f8eccac6)

Build
[10396590839](https://github.com/immich-app/immich/actions/runs/10396590839)

Build Image
[v1.112.1](https://github.com/immich-app/immich/pkgs/container/immich-server)
</details>

The below screenshot was taken at August 17, 2024 at 8:33 PM Pacific Time. All of these photos were taken/uploaded on the same day in Pacific Time.

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/368d58fa-50ae-42f9-bebe-bc05f4dc3f6d">

Browser date: Sat Aug 17 2024 20:33:34 GMT-0700 (Pacific Daylight Time)

`TZ=America/Los_Angeles` is set on all containers.

<details>
<summary>Metadata for the first image in "Yesterday"</summary>

```json
{
    "id": "0e6de382-b684-42b1-9411-fda5fa3f8265",
    "deviceAssetId": "E5EDE398-69F4-4FAA-94D8-5541E131328A/L0/001",
    "ownerId": "c7c204f4-5a70-4074-aed6-6a09ef09f9a6",
    "owner": {
        "id": "c7c204f4-5a70-4074-aed6-6a09ef09f9a6",
        "email": "", // redacted
        "name": "TJ Horner",
        "profileImagePath": "",
        "avatarColor": "green"
    },
    "deviceId": "85a4bcaa692a512c691f95968385f81e97c9c824305cccfeabe6b740d5e0bdb2",
    "libraryId": null,
    "type": "IMAGE",
    "originalPath": "upload/upload/c7c204f4-5a70-4074-aed6-6a09ef09f9a6/f9/69/f9699162-4000-4abe-8ec5-136038a16725.HEIC",
    "originalFileName": "IMG_9848.HEIC",
    "originalMimeType": "image/heic",
    "resized": true,
    "thumbhash": "UQgKDQBFao9oGbhmhoiIqCzPovM8",
    "fileCreatedAt": "2024-08-18T03:02:29.732Z",
    "fileModifiedAt": "2024-08-18T03:02:29.000Z",
    "localDateTime": "2024-08-17T20:02:29.732Z",
    "updatedAt": "2024-08-18T03:16:20.266Z",
    "isFavorite": false,
    "isArchived": false,
    "isTrashed": false,
    "duration": "0:00:00.000000",
    "exifInfo": {
        "make": "Apple",
        "model": "iPhone 15 Pro",
        "exifImageWidth": 4032,
        "exifImageHeight": 3024,
        "fileSizeInByte": 1337326,
        "orientation": "6",
        "dateTimeOriginal": "2024-08-18T03:02:29.732Z",
        "modifyDate": "2024-08-18T03:02:29.000Z",
        "timeZone": "UTC-7",
        "lensModel": "iPhone 15 Pro back triple camera 6.765mm f/1.78",
        "fNumber": 1.8,
        "focalLength": 6.764999866,
        "iso": 3200,
        "exposureTime": "0.5",
        "latitude": 0, // redacted
        "longitude": 0, // redacted
        "city": "Redmond",
        "state": "Washington",
        "country": "United States of America",
        "description": "",
        "projectionType": null,
        "rating": null
    },
    "livePhotoVideoId": null,
    "tags": [],
    "people": [],
    "unassignedFaces": [],
    "checksum": "aN1aV91G7ndP+oCYuwA2SPZGVtY=",
    "stackCount": null,
    "isOffline": false,
    "hasMetadata": true,
    "duplicateId": null
}
```

</details>

<details>
<summary>Metadata for the photo in "Sun, Aug 18"</summary>

```json
{
    "id": "4a5336c5-614f-4dde-b4b3-835a89e6308f",
    "deviceAssetId": "E3998847-BA66-4DBE-8898-9EC93621F863/L0/001",
    "ownerId": "c7c204f4-5a70-4074-aed6-6a09ef09f9a6",
    "owner": {
        "id": "c7c204f4-5a70-4074-aed6-6a09ef09f9a6",
        "email": "", // redacted
        "name": "TJ Horner",
        "profileImagePath": "",
        "avatarColor": "green"
    },
    "deviceId": "85a4bcaa692a512c691f95968385f81e97c9c824305cccfeabe6b740d5e0bdb2",
    "libraryId": null,
    "type": "IMAGE",
    "originalPath": "upload/upload/c7c204f4-5a70-4074-aed6-6a09ef09f9a6/94/35/94354eab-3a1b-455e-b94d-e9a7e3b97a69.jpg",
    "originalFileName": "camphoto_1254324197.jpg",
    "originalMimeType": "image/jpeg",
    "resized": true,
    "thumbhash": "CPgFDQCQiE+bqKfXk2h5aIZPbPjF",
    "fileCreatedAt": "2024-08-18T03:01:41.000Z",
    "fileModifiedAt": "2024-08-18T03:01:41.000Z",
    "localDateTime": "2024-08-18T03:01:41.000Z",
    "updatedAt": "2024-08-18T03:13:37.510Z",
    "isFavorite": false,
    "isArchived": false,
    "isTrashed": false,
    "duration": "0:00:00.000000",
    "exifInfo": {
        "make": null,
        "model": null,
        "exifImageWidth": 3024,
        "exifImageHeight": 4032,
        "fileSizeInByte": 2245290,
        "orientation": null,
        "dateTimeOriginal": "2024-08-18T03:01:41.000Z",
        "modifyDate": "2024-08-18T03:01:41.000Z",
        "timeZone": null,
        "lensModel": null,
        "fNumber": null,
        "focalLength": null,
        "iso": null,
        "exposureTime": null,
        "latitude": null,
        "longitude": null,
        "city": null,
        "state": null,
        "country": null,
        "description": "",
        "projectionType": null,
        "rating": null
    },
    "livePhotoVideoId": null,
    "tags": [],
    "people": [],
    "unassignedFaces": [],
    "checksum": "1ssXAqBaqKOJLV4wZi9N+X55mgk=",
    "stackCount": null,
    "isOffline": false,
    "hasMetadata": true,
    "duplicateId": null
}
```

</details>

The correct time and time zone appears for each of the photos when viewing them individually:

<img width="358" alt="image" src="https://github.com/user-attachments/assets/e16ac806-1c2f-4d74-9d2e-23f9a6548757">

<img width="335" alt="image" src="https://github.com/user-attachments/assets/9e437dbe-30df-471b-a4e1-c3b13b3aaa3c">

**Comment by tjhorner** [comment] 2024-08-18 05:07
Ok, I did some investigation and it appears to be related to how `localDateTime` is calculated. It depends on if the EXIF data has a timezone offset attached to it.

Here's the problem area:

https://github.com/immich-app/immich/blob/5ef9a8ff8d5cf62c4468db6f93a084ee4cd9fac3/server/src/services/metadata.service.ts#L229-L242

I haven't verified this by stepping through it in a debugger, but here's what I think is happening. This snippet is intended to apply the time zone from the EXIF data to the `dateTimeOriginal` (assuming it is a UTC timestamp) in order to get the timestamp in the time zone that it was taken.

However, it looks like this step is unnecessary since the `dateTimeOriginal` appears already adjusted to be in the correct time zone. As an example, the photo taken on August 17, 2024 at 8:02 PM Pacific Time that I posted above has the following `dateTimeOriginal`: `2024-08-18T03:02:29.732Z`. This is the correct UTC timestamp, already adjusted for the time zone it was taken in:

```js
// Convert `dateTimeOriginal` to local time zone
luxon.DateTime.fromISO("2024-08-18T03:02:29.732Z").toLocaleString(luxon.DateTime.DATETIME_FULL)
'August 17, 2024 at 8:02 PM PDT'
```

However, since the EXIF data also specifies a time zone of `UTC-7`, the metadata processing job applies this offset to the `dateTimeOriginal` in order to get the `localDateTime` (which is `2024-08-17T20:02:29.732Z`). But since the offset was already accounted for, instead of a timestamp at 8:02 PM **_PDT_**, it is a timestamp at 8:02 PM **_UTC_**:

```js
// Convert `localDateTime` to local time zone
luxon.DateTime.fromISO("2024-08-17T20:02:29.732Z").toLocaleString(luxon.DateTime.DATETIME_FULL)
'August 17, 2024 at 1:02 PM PDT'
```

I think the assumption is made that all dates are TZ-less, since the client code for rendering the photos in the timeline specifies UTC as the timezone for `localDateTime` rather than obtaining it from the ISO8601 string:

https://github.com/immich-app/immich/blob/5ef9a8ff8d5cf62c4468db6f93a084ee4cd9fac3/web/src/lib/utils/timeline-util.ts#L7-L8

But since the [column type in the database is `TIMESTAMP WITH TIME ZONE`](https://github.com/immich-app/immich/blob/5ef9a8ff8d5cf62c4468db6f93a084ee4cd9fac3/server/src/entities/asset.entity.ts#L100-L101), the timezone metadata is getting stored alongside the timestamp, and it appears to assume UTC for all dates, as indicated by the ISO8601 timestamps specifying no offset.

I'll try to get a local dev instance spun up and fix the issue. Hopefully maybe a PR if I am able to!

**Comment by tjhorner** [comment] 2024-08-18 05:44
I can confirm that omitting `zone: 'UTC'` from the `localDateTime` parsing and removing the snippet which incorrectly offsets the `dateTimeOriginal` fixes the issue; both photos now show up as being taken today:

<img width="413" alt="image" src="https://github.com/user-attachments/assets/7cfd0cca-7418-438e-a1a0-4abdd0c14a13">

I'll make a PR shortly.

**Comment by etnoy** [comment] 2024-08-18 07:24
Localdatetime is used to put it into the correct time bin. It is intended to be the local time for where the photo is taken, so the utc conversation is intended.

**Comment by etnoy** [comment] 2024-08-18 07:26
See #4072 for an explanation

**Comment by etnoy** [comment] 2024-08-18 07:36
Time zone logic is very messy and is filled with edge cases. Sorry if you already mentioned this, but what camera took the photos, and were they processed in some way? The TZ variable is a bit of a hack where we tell immich the default time zone to apply to photos that lack the information, usually DSLR photos. Modern phone cameras usually have this information correct. The TZ hack fails if you go on a trip to another time zone. The real fix is usually to edit the TZ information of the photos with exiftool. Maybe I should make a guide...

It seems like localdatetime stores the wrong date of the photos, in my experience this usually means that the issue is within the metadata of the photos, but I could be wrong.

Fun fact, Google photos has terrible support for DSLR photos because they just ignore this issue altogether. If I upload my d700 photos to Google photos and have phone pictures taken of the same event, they will be offset by several hours! Each photo must be manually corrected in the web ui.

**Comment by tjhorner** [comment] 2024-08-18 07:38
The photos are from an iPhone 15 Pro. The `dateTimeOriginal` stores the correct UTC timestamp of when the photo was taken, taking into account the time zone offset. Immich is performing an unnecessary additional offset.

**Comment by etnoy** [comment] 2024-08-18 07:46
That does sound strange. I'm still on vacation for another week or two so I'm only on my phone for now. I think we'll need to add some e2e tests for TZ logic, that infrastructure was not available to us when we made #4072 . 

Any change to the logic needs extensive testing to make sure all the edge cases are treated correctly.

**Comment by etnoy** [comment] 2024-08-18 07:52
> The photos are from an iPhone 15 Pro, directly from the Immich mobile app with no processing. [This comment](https://github.com/immich-app/immich/issues/10417#issuecomment-2295098682) includes the full JSON metadata of these photos (at the bottom of the comment) if you want to take a look. The `dateTimeOriginal` stores the correct UTC timestamp of when the photo was taken, taking into account the time zone offset. Immich is performing an unnecessary additional offset.
> 
> The conversion to UTC in the frontend should not be happening at all; this will make all date formatting happen relative to the current UTC time rather than the user's local time zone. The timestamps are ISO8601 so there is no need to specify the time zone.

I'm curious. Are the photos taken with the iphone with gps on or off?

**Comment by tjhorner** [comment] 2024-08-18 07:53
On. The second one was taken with Telegram's in-app camera, which is why much of the EXIF information is missing. However, the `dateTimeOriginal` is still correct despite the time zone not being present.

**Comment by etnoy** [comment] 2024-08-18 08:04
Ok. As another test, what happens if you unset the TZ variable, rerun metadata extraction for that image and check the info pane?

I want to know if it changes. If it does, the photo itself doesn't contain TZ data, it's only assumed from the default time zone set by the TZ variable.

**Comment by tjhorner** [comment] 2024-08-18 08:12
Neither photo changes timestamp in the info pane with TZ unset and metadata extraction re-run. Date, time, and time zone are all correct.

**Comment by etnoy** [comment] 2024-08-18 08:15
Thanks for verifying

**Comment by tjhorner** [comment] 2024-08-18 08:23
It appears `exiftool-vendored` already does some processing on the raw `DateTimeOriginal` tag to return a TZ-corrected timestamp, which is why we are seeing a correct `dateTimeOriginal`, and why Immich's processing of the same tag is redundant:

https://github.com/photostructure/exiftool-vendored.js/blob/d6fa63469aebb911a7ac929ab287e7d6fe503bec/src/ExifToolOptions.ts#L156-L168

**Comment by tjhorner** [comment] 2024-08-18 08:25
You mentioned that DSLR photos will often have incorrect EXIF data and will differ by hours from a phone. Do you have examples of those on hand?

**Comment by tjhorner** [comment] 2024-08-18 08:45
So, separately from how `localDateTime` is calculated, I'm pretty sure we can safely make the client-side change to remove the `zone: 'UTC'` parameter from `timeline-util`. This parameter isn't intended to tell Luxon what the time zone of the _input_ is; ISO8601 is a TZ-aware format, so that is already specified within the string. It is only relevant when formatting and transforming the time — from the Luxon docs:

> Specifically, a DateTime's zone affects its behavior in these ways:
>
> 1. Times will be formatted as they would be in that zone.
> 2. Transformations to the DateTime (such as plus or startOf) will obey any DSTs in that zone that affect the calculation (see "Math across DSTs" below)

We don't want to format the times in UTC, so that one is clearly a bug. This change will slightly mitigate the impact of the incorrect `localDateTime`s.

**Comment by tjhorner** [comment] 2024-08-18 09:10
Ok, I'm reading over that original PR again and I think I get the gist of the change. The goal is for assets to be sorted, grouped, etc. by the local time of capture, e.g. if a photo was taken at 00:00 Eastern Time and 00:00 Pacific Time, they will still both show up in the same day no matter what. I understand why the times are being formatted as UTC now, since that is intended to be the "local" TZ-less capture date.

The issue, then, is happening when the EXIF data has no datetime tags and `asset.fileCreatedAt` is used instead. This means that `dateTimeOriginal` will still be TZ-corrected, but there will be no [`timeZoneOffset`](https://github.com/immich-app/immich/blob/5ef9a8ff8d5cf62c4468db6f93a084ee4cd9fac3/server/src/services/metadata.service.ts#L232) because the date did not originate from the tags themselves, but instead the system. So `localDateTime` will still be the correct UTC timestamp, but incorrect in the context of the local capture date.

**Comment by etnoy** [comment] 2024-08-18 09:15
Thanks for your help in looking into this. As you can probably tell, this is a can of worms indeed. 

When I'm back at my computer, I think we should start to add more e2e tests and add relevant TZ cases to our test asset repository. Then we can start changing code.

**Comment by tjhorner** [comment] 2024-08-18 09:18
> As you can probably tell, this is a can of worms indeed.

Totally. Working with dates is such a pain 😅 

> When I'm back at my computer, I think we should start to add more e2e tests and add relevant TZ cases to our test asset repository. Then we can start changing code.

Sounds good to me. Let me know if you would like me to send over any of the photos I'm experiencing issues with to assist in writing those test cases.

**Comment by C-Otto** [comment] 2024-08-30 08:19
I'll have a look at this. Personal note: issue surfaces in album c539fe5c-5ae3-4275-b27a-48eba9050341.

**Comment by C-Otto** [comment] 2024-08-30 11:06
Some insights (only web, I haven't looked at the app). I'm in Germany and my browser is configured to use Europe/Berlin, which currently is at offset +2. The Immich server container is also using Europe/Berlin.

- From https://immich.app/docs/install/environment-variables/: `TZ is used by exiftool as a fallback in case the time zone cannot be determined from the image metadata.` I think this is confusing, as the time zone is not the same thing as the offset relative to UTC. For example, the time zone Europe/Berlin means +1 in winter and +2 in summer (which is working fine, see below). As the date and offset (usually) is part of some asset's metadata, this suffices to place it on a timeline, or convert the information to some (local, browser specific) representation, though.
- The **details view** shows the date and offset correctly for assets where it is configured (exif, XMP, ...), with the exception noted in the next bullet point. As (usually?) no time zone information is stored, this is also not shown (and impossible to deduce automatically). One of my early morning New Zealand photos taken with a camera configured for the offset (+13 offset) shows the local time and date with the offset information. A photo just taken a few minutes earlier (still early morning in NZ) , where I manually tweaked the offset to be +2, shows up at an evening time the before it was actually taken. This may happen if you forget to set the offset (or, more fancy, time zone) in your camera and Immich can't do anything about it, but at least the shown "absolute" time is correct (you just don't know the correct LOCAL time of the location where the picture was taken). This time may be used to sort photos chronologically, i.e. "which was taken first?".
- The **details view** does **not** show the correct offset if it is **zero**, for example when taken in Iceland (Reykjavík). If you configure any valid location with an offset of +0 has the same effect as configuring UTC (also +0, sometimes called "Z"): Immich assumes there is **no** offset information and always shows the (+0) time converted to the local time zone. An image taken in **January** at midnight in Iceland for me shows up as 1am (+1), an image taken in **July** (still in Iceland, at midnight) shows up as 2am (+2). This is due to different offsets (daylight saving time) used in my configured time zone (Europe/Berlin). I consider this a bug. UTC (`Z`) should be treated differently than explicitly configured offsets (`+00:00`). Currently, Immich writes out `Z` instead of `+00:00` when explicitly selecting the Iceland timezone. To me, this is a **bug**.
- The **album overview** (below the title) shows the date range of all assets in the album, with all times converted to the browser time zone. An image taken on 31 December 1999 at 23:59 in Iceland is treated as 01 January 2000 (at 00:59) as my browser is running using the Europe/Berlin timezone. This is somehow correct, but might be unexpected. Configuring my system/browser to use this time zone "fixes" the issue, i.e. the album overview now shows 1999.
- The (album) **timeline** always shows the local time of the assets, ignoring all offset information. In the aforementioned early morning New Zealand example, the photo with the correct offset information (+13) is shown for the date of the morning, while the photo with +2 as the configured offset shows up on the day before (even though it's supposed to be the same morning). This seems to be intentional, showing the respective local time and date (assuming the time zone / offset information in the asset's metadata is correct), so that finding those assets doesn't depend on the time zone of your browser. A picture taken on December 31st in New Zealand always shows up in December 31st. The same holds for the other extreme (Samoa Islands with -11).

**Comment by sirweazel** [comment] 2024-09-09 15:08
There are a lot of similar time issue topics.  I'm trying to follow them as i have this issue or similar like others. Here i posted some screenshots showing the date of the DB container not using the environmental variable.  Could that be an issue, and possible why the photos show as yesterday (like i'm running a few hours in the future)?  I show time i took screenshots, and showing "yesterday" but it was still today.  Conainer was running a few hours ahead not using eastern or new york time zone.

I didn't want to repost all my screenshots, so i'll link to this other thread.
[https://github.com/immich-app/immich/discussions/12322#discussioncomment-10585286](url)

**Comment by sirweazel** [comment] 2024-09-13 03:09
There are multiple threads with this issue.  In one of the threads I'm following, which I mentioned at previous post, It looks like someone might have posted a fix. Link below. I'm on my mobile so I'm having difficulty formatting things correctly if someone wants to tidy up my post feel free.

https://github.com/immich-app/immich/pull/12612

**Comment by danieldietzler** [comment] 2024-09-21 18:43
I'd like to close this in favor of #12650. Any objections?

**Comment by danieldietzler** [comment] 2024-09-21 18:44
Oh and actually, it may have been fixed by the PR @sirweazel referenced, yea. Could someone verify?

**Comment by snuq** [comment] 2024-09-26 19:00
If the fix mentioned above has been put into the latest release, then its not fixed yet.  The issue still exists in 1.116, in fact if anything its gotten WORSE, now the times/dates in the info panel are incorrect as well.

to illustrate - 
![Clipboard01](https://github.com/user-attachments/assets/82d90ea6-a10f-41c1-a1f4-37af9ad15482)
all those photos were taken on the 10th, which immich seems to at least have an idea of internally or it wouldnt be putting them BELOW the other photos.... in previous versions, the info panel for the lower photos would say the correct date of the 10th, but now the info panel shows the 11th

my server still has the TZ environment variable set to "America/Los_Angeles"

**Comment by danieldietzler** [comment] 2024-09-26 19:18
Did you re-extract metadata for those again?

**Comment by snuq** [comment] 2024-09-26 20:31
i selected them and did 'refresh metadata' from the hamburger menu. i havnt done a full db refresh tho

**Comment by danieldietzler** [comment] 2024-09-26 20:37
That should be enough. I'd like to close this in favor of #12650 though, as that's supposed to bundle all those issues. I'd appreciate it if you could post a message summarizing the issue there, and also provide a sample file (as a zip archive).

**Closed by danieldietzler** 2024-09-26 20:37 UTC

**Comment by Tjsyl** [comment] 2024-09-29 03:54
Most of the images from today show "Yesterday" and one shows in the future "Sun, Sep 29".
