### ISSUE TITLE
[Feature]: Shared Album from URL

### ISSUE THREAD

**Issue by AARtwo** [immich-app/immich#517] opened 2022-08-22 14:41 UTC
### Feature detail

With Google Photos you can share albums with a URL, not requiring a user to login to view the album. Having that feature to allow anyone to view the album without authentication for that one album would be great.

### Platform

Server

**Comment by bo0tzz** [comment] 2022-08-22 14:41
Duplicate of #265

**Closed by bo0tzz** 2022-08-22 14:41 UTC
Labels: feature, need triage
