### ISSUE TITLE
[BUG] IOS App - Items to upload shows negative number

### ISSUE THREAD

**Issue by brent7320** [immich-app/immich#1208] opened 2022-12-29 14:25 UTC
**Describe the bug**
The "Remainder" field in the upload section in the IOS app on an iPhone shows a negative number.

**Expected behavior**
The upload count should reflect the current remained of items left to upload. 

**Screenshots**
https://user-images.githubusercontent.com/789482/209966757-44eddeb3-692a-47f2-a024-c2976385a559.jpeg

**System**
iOS: `1.40`

**Comment by alextran1502** [comment] 2022-12-29 14:43
Duplicate of #968

**Closed** 2022-12-29 14:43 UTC
Labels: bug, need triage
