### ISSUE TITLE
'Add a location' feature in Immich web doesn't work on Safari

### ISSUE THREAD

**Issue by eon-pixel** [immich-app/immich#9594] opened 2024-05-19 09:18 UTC
### The bug

The dialog box/menu for the 'Add a location' feature does not appear correctly on Safari.

I opened an image, then clicked info, then 'Add a location'. The dialog box opens for a fraction of a second before appearing to vanish, leaving the rest of the web interface in slight greyscale. 

I am using macOS 14.5 and Safari 17.5.

Below is an example of the problem:
<img width="1728" alt="screenshot" src="https://github.com/immich-app/immich/assets/85057057/363bea06-c21c-452c-94a3-28fd6c51dc3f">

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1. Open an image on Immich web 
2. Click on info
3. Click on 'Add a location'
4. Dialog box opens then vanishes
```

**Comment by danieldietzler** [comment] 2024-05-20 12:36
Duplicate of #8223

**Comment by Xenthio** [comment] 2024-05-25 05:58
This isn't a duplicate issue, the two issues seem to be different. 
When you specify z-index on the details panel you are creating a new stacking context, so the fullscreen zindex 9999 popup doesn't overlay anything outside of it.
<img width="430" alt="image" src="https://github.com/immich-app/immich/assets/28588188/4bfa30df-12a8-4999-9da5-e6525889847d">

you are able to fix this by removing the highlighted class which specifies the z-index. or you could move the popup from inside the detail panel outside of it.

**Comment by Xenthio** [comment] 2024-05-25 06:00
Or for consistent behaviour, you can specify overflow:visible on the detail panel

**Comment by bo0tzz** [comment] 2024-05-25 08:10
This is indeed a different issue

**Closed** 2024-05-25 19:36 UTC
Labels: bug, 🖥️web
