### ISSUE TITLE
[Feature]: Shift+click to select range of pictures

### ISSUE THREAD

**Issue by jagjordi** [immich-app/immich#1243] opened 2022-12-31 21:19 UTC
### Feature detail

Similar to google photos, or any file explorer, selecting an item and then selecting another while holding shift key should select all the items in between. Right now pressing shift unselects any selected items. It would be great to have this to quickly create albums :)

### Platform

Web

**Comment by bo0tzz** [comment] 2022-12-31 21:26
Duplicate of #709

**Closed by bo0tzz** 2022-12-31 21:26 UTC
Labels: feature, need triage
