### ISSUE TITLE
[Feature]: Regonize people from pictures using machine learning

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#1333] opened 2023-01-16 10:37 UTC
### Feature detail

I would love to see a way for me to say who someone in a picture is, and it would find that person from all of the pictures and organize them under that person's name/picture.

Similar to how photoprism does it.

### Platform

Server

**Comment by bo0tzz** [comment] 2023-01-16 10:48
Duplicate of #294

**Closed by bo0tzz** 2023-01-16 10:48 UTC
Labels: feature, need triage

**Comment by samip5** [comment] 2023-01-16 11:05
Ah sorry, tried to search for it but did not find that.
