### ISSUE TITLE
iOS Immich app uploading makes phone extremely hot

### ISSUE THREAD

**Issue by jadenquinn** [immich-app/immich#12806] opened 2024-09-20 00:20 UTC
### The bug

When I'm uploading images to the Immich server within the house, my phone gets incredibly hot, too hot to hold. This isn't a hardware issue since I've seen mention of this elsewhere regarding the iOS Immich app as well. I can only assume it's also using way more power than it needs to to do what it's doing since it's getting that hot.

No other app I have ever used gets my phone this hot, not even when rendering a video in LumaFusion for example. When I am out of the house and am uploading through cell service, my phone doesn't get *as* hot, about 2/3 as hot. This to me means the severity of this problem is dependent on how fast the uploads are going to some degree... pun intended.

I also can say that since no other app does this when uploading to shares in the house, this is an Immich-specific problem.

### The OS that the Immich Server is running on

macOS 14.6.1

### The version of the Immich Server

v1.115.0

### The version of the Immich Mobile App

1.115.0 build.175

### The platform with the issue

- [X] Mobile
- [ ] Server
- [ ] Web

### My docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### My .env file content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres1595610030

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### The reproduction steps

Upload photos from an iPhone to an Immich server at 10MB/s or higher.

### Relevant log output

```shell
N/A.
```

### Additional information

My girlfriend uses the same Immich server I have set up, although she calls it "eye-mitch". She hasn't encountered this problem, but her internet isn't really fast enough to cause this issue anyway.

**Comment by mmomjian** [comment] 2024-09-20 00:22
Thanks for reporting. Duplicate of #3082 , Immich is very I/O heavy with big backups

**Closed by mmomjian** 2024-09-20 00:22 UTC

**Comment by alextran1502** [comment] 2024-09-20 00:25
The process of read/upload file  can be taxing for CPU if the process runs continuously for a long time, maybe there is a cpu temperature api that we can read and throttle the upload speed when it gets hot

**Comment by mertalev** [comment] 2024-09-20 00:43
I'm pretty sure this is related to the thumbnail bug I noticed the other day. There's an "easter egg" feature that can show the thumbnail of the currently uploaded asset. This widget ends up causing every asset to get its thumbnail decoded, possibly multiple times. Removing this widget made CPU usage go from peaking at 73% on a 4-core emulator to around 20% (average is lower).

**Comment by mmomjian** [comment] 2024-09-20 00:48
Hm. should we reopen #3082 then..? there is a lot more info there.

**Comment by mertalev** [comment] 2024-09-20 00:52
Yes, it should be re-opened.
