### ISSUE TITLE
[BUG] CSV_RECORD_INCONSISTENT_FIELD_LENGTHS after reboot

### ISSUE THREAD

**Issue by florihupf** [immich-app/immich#2152] opened 2023-04-03 07:52 UTC
### The bug

Hi there,

I needed to reboot the server and now the microservices container doesn't spin up but instead throws:

```
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^

CsvError: Invalid Record Length: expect 19, got 1 on line 9817
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:940:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:903:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1336:26)
    at Parser.final [as _final] (node:internal/streams/transform:112:25)
    at callFinal (node:internal/streams/writable:694:27)
    at prefinish (node:internal/streams/writable:723:7)
    at finishMaybe (node:internal/streams/writable:733:5)
    at afterWrite (node:internal/streams/writable:504:3)
    at onwrite (node:internal/streams/writable:477:7)
    at Parser.Transform._read (node:internal/streams/transform:245:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 1451030,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 9817,
  records: 9816,
  columns: false,
  error: undefined,
  header: false,
  index: 1,
  raw: undefined,
  column: 1,
  quoting: false,
  record: [ '1010873' ]
}
```

Is there a way to fix this?

Thanks in advance!

### The OS that Immich Server is running on

Truenas Scale

### Version of Immich Server

1.52.1

### Version of Immich Mobile App

1.52.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Stock
```

### Your .env content

```Shell
Stock
```

### Reproduction steps

```bash
Reboot Server.
Output logs from microservices container.
```

**Comment by bo0tzz** [comment] 2023-04-03 09:42
Duplicate of #1963. Try deleting and recreating the microservices container.

**Closed by bo0tzz** 2023-04-03 09:42 UTC
Labels: bug, need triage

**Comment by florihupf** [comment] 2023-04-04 16:55
Thanks, that worked!
