### ISSUE TITLE
[BUG] Google Motion Photos not playing back correctly on immich android app

### ISSUE THREAD

**Issue by Rihcus** [immich-app/immich#4319] opened 2023-10-03 01:56 UTC
### The bug

The immich android app seems to be having trouble playing back google motion photos. It seems to skip through the video. Some samples bellow.

Android app (issue present):

https://github.com/immich-app/immich/assets/30292597/da1ca835-ac7a-49d6-a4e6-83d24db5a47f

iOS app (no issue present):

https://github.com/immich-app/immich/assets/30292597/6ca79e43-9574-40e4-bb73-9e4e7318be0e

Web Firefox/Chrome (no issue present):

https://github.com/immich-app/immich/assets/30292597/08deb960-3d43-4080-9568-3e2c0659cb4c

### The OS that Immich Server is running on

macOS 12.6.2 21G320 x86_64

### Version of Immich Server

v1.80.0

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /Volumes/MACHD/PhotoLibrary/Library/Photos/Oneplus8/OP8_Camera_Backup/Camera:/mnt/media/Camera:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /Volumes/MACHD/PhotoLibrary/Library/Photos/Oneplus8/OP8_Camera_Backup/Camera:/mnt/media/Camera:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/Volumes/MACHD/PhotoLibrary/immich-upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Make sure immich server is running version v1.18.0
2. Upload a Google motion photo using the immich android app
3. View the photo on immich android app (optionally verify on web/ ios app).
...
```

**Comment by Shlokp** [comment] 2023-10-15 14:54
To help with figuring out the issue, here are 2 unedited images, both taken on the same day, with the same settings (~couple seconds apart).

Taken on Pixel 7 Pro with motion photos on. The first image (ending in 530) plays fine on the immich app, the second image, (ending in 183) stutters.

![PXL_20230822_122711530 MP](https://github.com/immich-app/immich/assets/35976544/df0efaa8-c87a-46fe-a8ef-fd5f8004257f)

![PXL_20230822_122709183 MP](https://github.com/immich-app/immich/assets/35976544/0029e2e6-ff55-42ea-ae45-97d572be5016)

Video of the issue in immich - https://youtu.be/HJRxWXtVsFg

**Comment by jrasm91** [comment] 2024-05-13 19:27
There were some issues with extracting android motion videos in the past. If these videos/photos are re-uploaded do they still suffer from the same issue?

**Comment by Shlokp** [comment] 2024-05-13 21:54
Hi, 

Just redownload these same images and uploaded to immich. The same issue continues. 1 image plays the motion aspect fine, the second doesn't. Both play fine on Google photos.

Version 1.103.1 for both server and mobile

**Comment by jrasm91** [comment] 2024-05-13 21:57
Can you send me a zip of a broken file so I can reproduce it locally?

**Comment by Shlokp** [comment] 2024-05-13 22:02
[275333377-0029e2e6-ff55-42ea-ae45-97d572be5016.zip](https://github.com/immich-app/immich/files/15300389/275333377-0029e2e6-ff55-42ea-ae45-97d572be5016.zip)

**Comment by Shlokp** [comment] 2024-05-13 22:04
I've just tried it again and it looks weird on Google photos :/

**Comment by Shlokp** [comment] 2024-05-13 22:11
Here's another image

Took on pixel 7 pro, looks fine on Google photos, when I save it on Google photos and upload to immich, it doesn't play the motion photos properly 

[PXL_20240322_170351467.MP.zip](https://github.com/immich-app/immich/files/15300446/PXL_20240322_170351467.MP.zip)

**Comment by jrasm91** [comment] 2024-05-13 22:15
Both of those played fine for me. The second one needed to be transcoded, but it worked

**Comment by Shlokp** [comment] 2024-05-13 22:17
I'll try it out tomorrow, see if that's the issue. What codec does Google use by default? And which one does immich require

**Comment by jrasm91** [comment] 2024-05-13 22:25
Immich will transcode if it doesn't match the selected target, which is h264 by default I think. The used codec depends on the camera though.

**Comment by Shlokp** [comment] 2024-05-13 22:30
Which ones can immich support natively? I assumed the default format used by pixels would be supported and didn't think about transcode

**Comment by jrasm91** [comment] 2024-05-13 23:07
It is more about which clients can play which codecs. We use h264 which is supported basically everywhere. New phones seem to be using h265 more often now though.

**Comment by Shlokp** [comment] 2024-05-23 05:57
The motion photo plays back fine once I've transcoded everything to H264. I'm surprised H265 playback doesn't work on pixel 7 pro

**Comment by jrasm91** [comment] 2024-07-02 14:02
Sweet, looks like this is fixed now. We've addressed some issues around motion video extraction since this issue was opened.

**Closed by jrasm91** 2024-07-02 14:02 UTC
Labels: bug
