### ISSUE TITLE
[BUG] Immich background backup service does not respect the backup option and uploads anyway

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#983] opened 2022-11-16 21:04 UTC
**Describe the bug**
So I've turned off Immich's backup button, and I've noticed that there are still new items being uploaded to the server.
I have not turned off the backup background service, though. Does the backup background service not respect the backup button status?

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Turn off backup, but keep background backup on.
2. Create new assets by taking a picture or video
3. Wait a bit.
4. See Immich uploading the new item, despite the turned off backup option.

**Expected behavior**
I expected Immich to stop automatically uploading any new and/or updated assets on my device.

**System**
- Phone OS [iOS, Android]: `Android 12`
- Server Version: `1.35.0`
- Mobile App Version: `1.35.0`

**Comment by alextran1502** [comment] 2022-11-17 03:05
@zoodyy Is this issue something you are aware of?

**Comment by zoodyy** [comment] 2022-11-19 05:35
This actually works as intended. (Foreground) backup and background backup work independently. Thus, on Android, you can choose from four different backup strategies:

1. (foreground) backup disabled + background backup disabled: no backup is performed unless you manually click `Start Backup` at the bottom of the backup screen
2. (foreground) backup enabled + background backup disabled: automatic backup is only performed while app is open
3. (foreground) backup disabled + background backup enabled: backup is only performed in the background whenever new photos are taken (respects "only on wifi" and "only while charging" settings)
4. (foreground) backup enabled + background backup enabled: backup is performed in the background whenever new photos are taken (respects "only on wifi" and "only while charging" settings) AND always performs backup while the app is open (irrespective of "only on wifi" and "only while charging" settings)

I think we should possibly rename the old backup to sth. like "foreground backup", give hints in the app  & document the backup settings to avoid confusion OR remove the foreground background backup on Android entirely.

**Comment by alextran1502** [comment] 2022-11-21 12:14
Closing as this is the intended behavior

**Closed by alextran1502** 2022-11-21 12:14 UTC
Labels: need triage
