### ISSUE TITLE
Top of mobile app not visible on tablet

### ISSUE THREAD

**Issue by graemearthur** [immich-app/immich#10234] opened 2024-06-12 22:04 UTC
### The bug

![IMG-20240612-WA0007](https://github.com/immich-app/immich/assets/826712/f806e8c1-5170-4031-8817-3c3a1065da7a)

Top bar of app is hidden on Samsung galaxy A6 lite

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

1.106.3

### Version of Immich Mobile App

1.106.3 build 143

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1.
2.
3.
...
Open app on tablet
```

**Comment by Snowknight26** [comment] 2024-06-12 22:10
Duplicate of https://github.com/immich-app/immich/issues/10010?

**Closed** 2024-06-27 20:58 UTC
