### ISSUE TITLE
[BUG] wrong total images (mobile)

### ISSUE THREAD

**Issue by Bluemangoo** [immich-app/immich#3167] opened 2023-07-09 00:05 UTC
### The bug

![Screenshot_2023-07-09-07-51-40-880_app alextran immich](https://github.com/immich-app/immich/assets/63218454/c3c5fef6-f759-4887-8eef-b4863f4d02ff)

Total number is lower than backuped number.

I'm sure all the images uploaded is in the range. According to my system gallery, `4090` is the right number.

### The OS that Immich Server is running on

Windows WSL2

### Version of Immich Server

1.66.1

### Version of Immich Mobile App

1.66.0 (build.89)

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
default(latest)
```

### Your .env content

```Shell
default(latest)
```

### Reproduction steps

```bash
1. Choose albums to backup (not `recent`)
2. Wait it to backup (maybe interrupt by network error and killing process in many times)
3. Check, you have got the number under zero🤯
```

### Additional information

My phone is MI8, does it matter?

**Comment by EnochPrime** [comment] 2023-07-09 00:16
Duplicate of #968

**Comment by Bluemangoo** [comment] 2023-07-09 00:38
OK, I'll close this one.

**Closed** 2023-07-09 00:38 UTC
Labels: bug, need triage
