### ISSUE TITLE
Immich IOS.app albums button press takes forever

### ISSUE THREAD

**Issue by machitza** [immich-app/immich#14047] opened 2024-11-10 11:30 UTC
### The bug

Pressing Immich IOS.app albums button press takes forever as i have over 100 albums. Can you make a local cache of albums and only when swipe down to refresh albums?

### The OS that Immich Server is running on

Ubuntu 22

### Version of Immich Server

1.120.1

### Version of Immich Mobile App

1.120.1 build 183

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

1.open immich ios app
2.press albums
3.app becomes slow while refreshing albums
...

**Comment by bo0tzz** [comment] 2024-11-10 11:34
Dupe of #13631

**Closed by bo0tzz** 2024-11-10 11:34 UTC
