### ISSUE TITLE
[Feature]: automatic deletion of photos/videos after x days

### ISSUE THREAD

**Issue by Snuupy** [immich-app/immich#356] opened 2022-07-17 04:55 UTC
### Feature detail

Similar to Google Photos' feature:  
- https://support.google.com/files/answer/10862356?hl=en
- https://cdn.nerdschalk.com/wp-content/uploads/2021/09/how-to-delete-backed-up-photos-and-videos-4-a.png?width=800

I'd like to see a feature for the app to automatically remove photos/videos after a set number of days so my phone isn't taking up all this storage space :)

### Platform

Mobile App

**Comment by zackpollard** [comment] 2022-10-01 00:30
This is a duplicate of #

**Closed** 2022-10-01 00:30 UTC
Labels: feature
