### ISSUE TITLE
Extreme stuttering in App when having a large amount of albums.

### ISSUE THREAD

**Issue by Hely0n** [immich-app/immich#14185] opened 2024-11-17 11:36 UTC
### The bug

Since the new mobile app overhaul, me and my girlfriend have the issue, that the whole app gets extremely unresponsive and has like 5fps after opening the Albums-Tab. I assume it‘s due to our large amount of albums that get loaded from the server in the background. After a minute or so, it finishes and the performance returns to normal, but it refreshes the albums nearly every time we open the app. Unfortunately that makes the app unusable currently.

I could somehow find out how to count my albums, if this information is needed.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

v1.120.2 build.184

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. have a large amount of Albums (if think)
2. open the album tab on the app

### Additional information

iPhone 15 Pro Max and iPhone 15

**Comment by bo0tzz** [comment] 2024-11-17 11:49
Dupe of #12497

**Closed by bo0tzz** 2024-11-17 11:49 UTC
