### ISSUE TITLE
[Feature]: Preserve source names as a generated Album name

### ISSUE THREAD

**Issue by zatricky** [immich-app/immich#684] opened 2022-09-13 12:36 UTC
### Feature detail

This request is different from #38 and #570 though it does have some theoretical similarity.

I would like to be able to preserve the source information by creating an Album that automatically includes the images from that source. As examples when uploading from "WhatsApp-Images", DCIM from two separate mobile devices, or two unrelated folders within the CLI, these would automatically generate five separate albums.

Purpose-wise, as an example, I'd like to share a whole bunch of photos taken on vacation - but presently I have to scroll through unrelated media items and manually add the correct items to an album. Were this feature available, it would be much easier to find the correct images without the distraction of the unrelated media.

### Platform

Server

**Comment by dorianim** [comment] 2022-09-13 20:13
Maybe similar to #537 ?

**Comment by zatricky** [comment] 2022-09-14 17:54
@dorianim thanks ; yes #537 is certainly similar enough that solving this issue might solve that one as well. However, I feel like #537 is asking for a mobile app feature whereas I'm suggesting a client-independent feature.

**Comment by bo0tzz** [comment] 2022-09-15 08:49
Duplicate of #537. I renamed that issue slightly to capture the full extent.

**Closed by bo0tzz** 2022-09-15 08:49 UTC
Labels: feature, need triage
