### ISSUE TITLE
[BUG] Wrong location on map

### ISSUE THREAD

**Issue by MrColumbo** [immich-app/immich#4340] opened 2023-10-04 13:26 UTC
### The bug

Some pictures with Exif date from Chile show close to India - even on the demo instance from immich
![P1260658](https://github.com/immich-app/immich/assets/5223590/d8606c45-f86a-42bb-9cb8-31242c3a04a3)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.18

### Version of Immich Mobile App

v1.18

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
error is even on demo instance
```

### Your .env content

```Shell
error is even on demo instance
```

### Reproduction steps

```bash
1.upload photo (see attachment) or see here: blob:https://demo.immich.app/a3d0236c-47a5-429b-8f96-fbaad00f7947
2.look on info and map
3.
...
```

**Comment by MrColumbo** [comment] 2023-10-04 16:49
in my example the exif is like that

GPS Latitude                    : 18 deg 32' 43.53" S
GPS Longitude                   : 70 deg 19' 52.40" W

=> GPS Position                    : 18 deg 32' 43.53" S, 70 deg 19' 52.40" W

should be close to Arica in Chile but not India

**Comment by jrasm91** [comment] 2023-10-09 04:58
Duplicate of #4340

**Closed** 2023-10-09 04:58 UTC
Labels: bug, need triage
