### ISSUE TITLE
[BUG] iPhone 14 - 4K HDR videos do not load in Safari on MacOS

### ISSUE THREAD

**Issue by brent7320** [immich-app/immich#1197] opened 2022-12-28 11:04 UTC
**Describe the bug**
I synced the entire photo library on my iPhone to Immich (32,000+ photos and videos), everything went great for photos. However most larger videos do not load in the webUI within Safari on MacOS. I have verified that all adblockers and content blockers are disabled. This behavior does NOT exist when opening the site in Microsoft Edge on the same device, this only happens in Safari on a MacBook. You can look in webInspector in safari and see numerous "206 - Partial Content" errors when hovering over and clicking on larger video files. A preview image of these videos shows correctly, but the video will not play when hovered over or clicked on. 

- Does NOT work on Safari in MacOS
- DOES work in Microsoft Edge (chromium) in MacOS
- DOES work in Safari on IOS

**To Reproduce**
1. Go to 'Photos'
2. Click on 'Video Thumbnail'
4. See that the video does not load

**Expected behavior**
Video files should play within Safari

**Screenshots**
The error below is returned for these videos when the video is hover
Summary
URL: http://192.168.1.12:2283/api/asset/file/c5a89655-74bc-447f-93b1-166661ee9172?isThumb=false&isWeb=true
Status: 206 Partial Content
Source: Network

Request
Range: bytes=0-25244180
Accept: */*
Referer: http://192.168.1.12:2283/photos
Accept-Encoding: identity
Connection: Keep-Alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
X-Playback-Session-Id: 39019A1D-7368-4E59-84C6-CB83A01E377D

Response
Content-Type: video/mp4
Content-Range: bytes 0-25244180/25244181
Date: Wed, 28 Dec 2022 10:46:50 GMT
Content-Length: 25244181
Cache-Control: max-age=31536000
Connection: keep-alive
Server: nginx/1.23.3
X-Powered-By: Express

Query String Parameters
isThumb: false
isWeb: true

**System**
- Phone OS [iOS, Android]: `<version>`
- Server Version: `1.40`
- Mobile App Version: `1.40`

**Comment by alextran1502** [comment] 2022-12-28 16:16
I cannot reproduce the issue. Is there a specific video that you can share for testing?

**Comment by brent7320** [comment] 2022-12-28 17:13
Sure, what method do you prefer to share over. I tested this again in a inPrivate window to eliminate cache issues and you can see the numerous 206's

![image](https://user-images.githubusercontent.com/789482/209848252-75d443c5-4b3e-4355-b03c-12319fd899f3.png)

**Comment by alextran1502** [comment] 2022-12-28 18:05
You can zip it and share it here

**Comment by brent7320** [comment] 2022-12-28 18:58
Here you go, this is actually downloaded from Immich, so the file is definitely there. I also tried playing it through the WebUI on another Mac in our house with the same result. The majority of my videos are like this.
[IMG_0676.mov.zip](https://github.com/immich-app/immich/files/10315937/IMG_0676.mov.zip)

**Comment by alextran1502** [comment] 2022-12-28 19:17
Confirmed that I cannot play this video on Safari as well. Do you know of the device you used to capture this video? Might be some encoding that Safari doesn't like.

Safari is the new Internet Explorer 😛 . Nice capture of B17 BTW

**Comment by brent7320** [comment] 2022-12-28 19:41
it was captured on an iPhone 14, 4K - 30FPS, HDR. I can drag the file into safari and it plays it fine with QuickTime. 

Thanks, I was on vacation and saw it. I was not sure what it was when I saw it flying along the beach until I went back and did some research, but I knew it had to be something special.

**Comment by ZabejAga** [comment] 2023-03-16 13:45
I can confirm the issue with safari.
Whenever HDR is ON video won't play on Safari MacOSX. 
Tested with 4k and 1080p, 30fps, 60fps, HDR on/off.

**Comment by casabryant** [comment] 2023-03-31 20:03
I'm having the same issue and am happy to help test if needed.

**Comment by maxbraun91** [comment] 2023-06-01 10:24
I was about to file a new bug but this seems to be more or less the same thing. When hovering over 4K HDR files from my iPhone 14 Pro, Immich Web shows a red exclamation mark on the top right corner of the thumbnail and preview does not start (on macOS, Server version 1.59.1).
However, Google Chrome shows the preview fine (in HDR on MBP 14").
I set up immich from scratch yesterday and had all assets be transcoded again - without success.
Further examples, logs etc. can be provided upon request - happy to help :)

**Comment by maxbraun91** [comment] 2023-06-01 18:37
@alextran1502 yes, might be due to the Codec. Other videos (e.g. Timelapse or TikTok-Downloads) work fine.

**Comment by mertalev** [comment] 2023-08-16 04:50
This should be fixed as HDR videos are now tone-mapped for compatibility.

**Closed** 2023-08-16 04:50 UTC
Labels: bug, platform:ios
