### ISSUE TITLE
[BUG] Exif metadata 'Rotation: 180' ignored for videos on mobile app

### ISSUE THREAD

**Issue by andresbono** [immich-app/immich#2130] opened 2023-03-30 20:05 UTC
### The bug

Videos recorded in horizontal by turning the phone 90 degrees clockwise (how a left-handed would typically record the video with one hand) are reproduced upside down in the mobile app.

At least with my phone, the raw data of the videos is the same no matter the orientation of recording, except for the exif metadata `Rotation`, that would be `0`, `90` or `180` depending on the case.

Videos with `0`, `90` (even `270`) values are reproduced correctly, only `180` is buggy.

The thumbnail (web browser and mobile app), reproduction in the web browser and preview in the web browser are all displayed correctly for all videos.

### The OS that Immich Server is running on

Host is Debian amd64 (container images ghcr.io/immich-app/*)

### Version of Immich Server

v1.52.1

### Version of Immich Mobile App

v1.52.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/immich-app/immich/releases/download/v1.52.1/docker-compose.yml
```

### Your .env content

```Shell
https://github.com/immich-app/immich/releases/download/v1.52.1/example.env
```

### Reproduction steps

1. Prepare videos with different rotations. For example, download test video and set Rotation values with exiftool:

```bash
$ wget -O 0.mp4 https://freetestdata.com/wp-content/uploads/2022/02/Free_Test_Data_1MB_MP4.mp4
$ cp 0.mp4 90.mp4 
$ cp 0.mp4 180.mp4
$ cp 0.mp4 270.mp4
$ exiftool -Rotation=90 90.mp4
$ exiftool -Rotation=180 180.mp4
$ exiftool -Rotation=270 270.mp4
$ exiftool -Rotation *.mp4
======== 0.mp4
Rotation                        : 0
======== 180.mp4
Rotation                        : 180
======== 270.mp4
Rotation                        : 270
======== 90.mp4
Rotation                        : 90
    4 image files read
```
2. Play the videos in the mobile app (Android), after uploading them to the server or before backing-up, makes no difference.

**Comment by andresbono** [comment] 2023-06-08 05:55
@jrasm91 I think this is more of a https://github.com/immich-app/immich/labels/%F0%9F%93%B1mobile related issue.

Actually, it seems to be derived from flutter and the `video_player` package: https://github.com/flutter/flutter/issues/122276. Is pinning `video_player` to version `2.3.4` an option? At least until https://github.com/flutter/flutter/issues/122276 is resolved.

**Comment by uhthomas** [comment] 2023-07-09 20:12
Possibly resolved by #2908? Might need some adjustment to the transcoder too.

**Comment by waclaw66** [comment] 2023-07-26 09:53
Noticed that problem too, seems like player problem. Immich Web and other web/mobile players play such videos correctly.

**Comment by nguypaul** [comment] 2023-08-01 03:56
I also have this problem on the Android mobile app. Rotation 0 and 90 play correctly but 180 is upside down. When viewing on a web browser it plays correctly.

**Comment by kkmaslowski** [comment] 2024-02-04 18:00
Issue still exists on latest version.

**Comment by sbkg0002** [comment] 2024-03-22 19:39
Since it seems dead at the Flutter's end; can it be fixed at the Immich side of things?

**Comment by dgtal1** [comment] 2024-05-13 08:04
Same here - it's wrong only in the ****Android** mobile app; iOS is fine.

**Comment by Tywele** [comment] 2024-05-18 09:31
I experience the same bug on a Pixel 7

**Comment by m-GDEV** [comment] 2024-06-23 04:48
I'm also having this issue on a Samsung S22+ with the android immich client app

**Comment by ec0li82** [comment] 2024-06-24 12:58
Same here, S20FE.

**Comment by WizenThorne** [comment] 2024-07-28 22:37
I'm having this issue as well on the Fold 4.

**Comment by illmouse** [comment] 2024-08-03 04:35
Can confirm this on 1.111.0 with MiMix 2s with lineage 21 (android 14) onboard.

**Comment by AtmosphericIgnition** [comment] 2024-08-31 03:46
Same here on a Pixel 8 Pro with GrapheneOS, running Immich 1.113.0

**Comment by jrasm91** [comment] 2024-09-04 03:08
Can someone upload a zip of a file with this issue?

**Comment by jrasm91** [comment] 2024-09-04 03:10
Ah nevermind, I see this is reproducible with exiftool commands. Will try to reproduce.

**Comment by andresbono** [comment] 2024-11-14 13:37
I tried Immich on Android again after a while and it looks like this issue is gone 🎉  I'm using `1.120.2 build 167`.

Can someone else confirm the issue is fixed with the latest version of the Android app?

And just curious, any clue about what was the fix?

**Closed** 2024-12-04 21:03 UTC
Labels: 📱mobile, 🗄️server
