### ISSUE TITLE
Optionally disable date grouping for albums

### ISSUE THREAD

**Issue by nicokaiser** [immich-app/immich#14604] opened 2024-12-09 18:18 UTC
### The bug

The scrubbable scrollbar (`immich-scrubbable-scrollbar`) is very nice on the desktop – but it takes way too much room on mobile devices. This is already addressed in #10390 (and I also agree that is should be hidden on mobile devices).

For Immich users this might not be that much of an issue, since for mobile devices we have the wonderful Immich apps. However when sharing albums via links, recipients might want to view these albums on a mobile web browser, so a good mobile experience for the web frontend is preferable.

Additionally, shared albums typically cover rather short time ranges (and typically only contain a certain amount of images), so a timeline is not really needed at all.

Maybe it could be a solution to completely hide the scrubbable in all (or just shared) albums – or make this an option in the configuration.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.122.2

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

n/a

### Additional information

Here are two screenshots of a shared album opened in a 390x844 (iPhone) window, the first is the current implementation, the second is the same, with the scrollbar removed.

![shared-album-1](https://github.com/user-attachments/assets/2cdc4746-268b-4a6e-94bd-2a5770e81604)
![shared-album-2](https://github.com/user-attachments/assets/820d09a6-fac7-4c43-b6ff-5a43c3b74aac)

**Comment by nicokaiser** [comment] 2024-12-09 18:27
Thinking about it: maybe a (either global or per-album) option to disable grouping by day could be really helpful here.

**Comment by bo0tzz** [comment] 2024-12-09 18:29
Is this not a duplicate of that issue you linked?

**Comment by nicokaiser** [comment] 2024-12-09 18:33
> Is this not a duplicate of that issue you linked?

Regarding the padding it is, you are right.
But maybe the actual feature request is: "Disable date grouping for albums" – either optional per album or globally (or completely – but maybe it should be configurable). I did not really find something similar in the issues...

**Comment by bo0tzz** [comment] 2024-12-09 18:46
Feature requests go in https://github.com/immich-app/immich/discussions/categories/feature-request, so try searching there, and if you don't find anything feel free to open a new discussion.

**Closed by bo0tzz** 2024-12-09 18:46 UTC
