### ISSUE TITLE
[BUG] server: Repair doesn't work with symlinks

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#4507] opened 2023-10-17 06:43 UTC
### The bug

All files are reported as offline or untracked.

`UPLOAD_LOCATION=/var/lib/immich/upload`
`/var/lib/immich` is symlink to `/mnt/data/immich`

![obrazek](https://github.com/immich-app/immich/assets/15554561/51ad962d-0d29-4d11-aeff-edcd35fc36af)

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

v1.82.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by sigmaprojects** [comment] 2024-05-18 01:59
Glad I saw this before doing anything drastic, I have 45,758 files in my "offline paths" that may be due to this bug.  Should they be ignored for now?

**Comment by alextran1502** [comment] 2024-05-18 03:45
@sigmaprojects yes

**Comment by jrasm91** [comment] 2024-09-04 00:17
Duplicate of #12293

**Closed by jrasm91** 2024-09-04 00:17 UTC
