### ISSUE TITLE
[BUG] Web interface is missing a "View all" button for "Places" under "Explore"

### ISSUE THREAD

**Issue by BertSchel** [immich-app/immich#6092] opened 2024-01-01 16:24 UTC
### The bug

I can only see the first 6 thumbnails of the "Places" without the option of viewing more like "People" DOES have that option. This is not just on my server, I can see it in the online demo's as well.

### The OS that Immich Server is running on

Linux, Docker

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
-
```

**Comment by aisbergde** [comment] 2024-01-01 17:47
same issue: #5261 - I don't know why this other issue is closed, but the issue is still not solved. And then users are searching only for open issues, when they report issues.

Maybe it would be better not to close issues, when some PR fixes them, but when the code is available in a new release?
We have a lot of closed issues, which are closed in the code, but not for the user.

**Comment by drifter75** [comment] 2024-01-23 12:21
using v1.93.3 and it's still an issue.

For me it's showing only 9 places and the "View all" option for places is missing.

**Closed** 2024-01-26 18:11 UTC
Labels: bug, 🖥️web

**Comment by boenni23** [comment] 2024-01-26 19:50
Sorry for the pull request. I was working on the same thing today. Do you get more than 25 Elements in your merged branch? maybe I missed something but you just use `api.searchApi.getExploreData()` or did you change this behavior in an other commit?

**Comment by jrasm91** [comment] 2024-01-26 20:25
I don't think we changed anything about the result set length, so you could rename and propose additional changes for that part if it is a problem still.

**Comment by besanur** [comment] 2024-01-31 22:38
same issue on v1.94.1

**Comment by bo0tzz** [comment] 2024-02-01 16:27
@besanur it looks fine for me. Do you have enough places in your instance that there are more to view?

**Comment by besanur** [comment] 2024-02-01 16:28
> @besanur it looks fine for me. Do you have enough places in your instance that there are more to view?

Yes, all of them are displayed in the mobile app, which is around 30 places

**Comment by besanur** [comment] 2024-02-01 16:28
> @besanur it looks fine for me. Do you have enough places in your instance that there are more to view?

Yes, all of them are displayed in the mobile app, which is around 30 places

**Comment by besanur** [comment] 2024-02-01 16:32
@bo0tzz 
Yes, all of them are displayed in the mobile app, which are 125 places

**Comment by besanur** [comment] 2024-02-01 22:31
@bo0tzz Sorry if I confused you a bit. The problem with view all was also fixed for me. But I only see 12 entries in the web interface.

**Comment by bo0tzz** [comment] 2024-02-02 09:17
#6676
