### ISSUE TITLE
HDR videos look pale on mobile

### ISSUE THREAD

**Issue by s0nerik** [immich-app/immich#5120] opened 2023-11-18 05:20 UTC
### The bug

Looks like video_player package doesn’t support HDR colors in videos. The respective [issue](https://github.com/flutter/flutter/issues/91241) comments seem to suggest that an alternative package, called [media_kit](https://pub.dev/packages/media_kit), exists, which doesn’t have this problem.

### The OS that Immich Server is running on

Raspbian

### Version of Immich Server

v1.86.0

### Version of Immich Mobile App

v1.86.0 build.126

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Shoot an HDR video on any iPhone supporting it.
2. Sync it in original quality into Immich.
3. Open synced video in the Immich app on that same iPhone.
4. Colors in the video look pale.
```

**Comment by mertalev** [comment] 2023-11-18 05:47
We've been looking into media_kit as a better alternative for HDR and hope to switch to it. However, the impression we got was that while its color reproduction is definitely better, it still isn't HDR. Based on [this](https://github.com/media-kit/libmpv-darwin-build/blob/main/patches/ffmpeg-fix-ios-hdr-texture.patch) patch in their repo, it seems there's a hardware decoding limitation involved. HDR seems to be an open issue in the Flutter ecosystem, unfortunately.

**Comment by s0nerik** [comment] 2023-11-18 06:04
I think another alternative could be to use the native view for a video player on iOS, without copying frames into a texture. I guess [native_video_player](https://pub.dev/packages/native_video_player) does that, but not sure as I haven’t tried it.

**Comment by mertalev** [comment] 2023-11-18 08:06
I think platform views with Metal are the only way to get HDR on iOS. media_kit describes its player as native too, so there seems to be more to it than that. I'm not sure what this player uses.

**Comment by alexmercerind** [comment] 2023-11-22 19:26
I saw this discussion.

> Based on [this](https://github.com/media-kit/libmpv-darwin-build/blob/main/patches/ffmpeg-fix-ios-hdr-texture.patch) patch in their repo, it seems there's a hardware decoding limitation involved.

That patch addresses a regression. 4K HDR plays flawless on iOS from the feedback we have so far.

We have discussed few things in a new ticket:

https://github.com/media-kit/media-kit/issues/615

You can improve overall rendering result on normal displays with tone mapping.

I believe default one isn't best on iOS/macOS right now.

**Comment by mertalev** [comment] 2023-11-22 20:39
Thank you for clarifying that! I think the `--tone-mapping` flag can help as well here, but we already transcode and tone-map videos, so the problem only occurs when users want to view the original. Does this flag have any color or performance impact on SDR videos, or is it safe to enable universally?

I also wonder if there's any hope for hardware-decoded HDR using Flutter. From the discussion you linked, it seems the limitations are on Flutter textures along with libmpv. Am I right in thinking that platform views with Metal would allow for HDR? If so, are you aware of any player that takes this approach?

**Comment by yotis1982** [comment] 2023-12-27 04:50
Sorry if my knowledge is not at best to fully understand this issue, but is this topic being addressed on the roadmap or at least a fix expected in the future releases? Is a bit weird to look at my videos on iPhone and look like they are washed out.

Thank you!

**Comment by mertalev** [comment] 2023-12-27 05:07
Do you have transcoding disabled? HDR videos have to be transcoded for the colors to look normal on mobile.

We do have a PoC with media_kit that can render these videos better (albeit not HDR), but it has some other issues we haven't fixed yet.

**Comment by yotis1982** [comment] 2023-12-27 05:31
@mertalev thanks for fast reply, transcoding settings are pretty much the default ones; for the Trandcode Policy I have "Only videos not in desired format". Should I have it on "All videos" to transcode everything?

Thanks!

**Comment by mertalev** [comment] 2023-12-27 05:43
Hmm, it should be transcoding on default settings. Could you try running a "missing" job for transcoding? If that doesn't transcode anything then it might just be a bug.

**Comment by yotis1982** [comment] 2023-12-27 05:51
I tried your suggestion, the tasked went fast, I don't think anything was transcoded. I'll check more on. Thanks!

**Comment by yotis1982** [comment] 2023-12-29 01:18
I did a test today and it seems to work fine (aka colors looks fine in the HDR), but is interesting how it works at least for me. I'll do my best to explain and maybe somebody with more technical knowledge in this area will find it useful.

First the Immich server Settings for Transcode Policy is set to "Only videos not in desired format"; everything else is default as per installation.

I took a video on my iPhone and played the video through the Immich app.

1. **Video is only local on iPhone (backup icon is cloud cut) - colors are faded** (see below for details):

![IMG_8537](https://github.com/immich-app/immich/assets/1459159/bda0a2b3-e410-4ca3-9fce-b3985624121a)

The Info shows "is remote: false" and "storage : AssetState.local"

![IMG_8538](https://github.com/immich-app/immich/assets/1459159/bfe50313-e830-430e-ad44-2b37c2600812)

2. **Video is local on iPhone and backup to Immich (backup icon is cloud and checkmark) - colors are faded** (see below for details)

![IMG_8539](https://github.com/immich-app/immich/assets/1459159/464f2c88-b8d7-436e-92bf-7a6243c23ae5)

The Info shows "is remote: true" and "storage : AssetState.merged". 

![IMG_8540](https://github.com/immich-app/immich/assets/1459159/6296d102-fd23-43e2-87c2-a172116f54e6)

3. Video is only backup on Immich (backup icon is just cloud) and deleted from Iphone - colors are normal (see below for details).

![IMG_8542](https://github.com/immich-app/immich/assets/1459159/03cc448d-1958-4a77-a005-09d041fb453f)

The info shows "is remote: false" and "storage : AssetState.remote"

![IMG_8544](https://github.com/immich-app/immich/assets/1459159/5c2a1e5d-5dde-4745-965b-6031c4fb487b)

I think everything is fine, because my only concern was when I was about to check on backup videos that the colors will not look ok. If the video is still on my iPhone, I can play it via the native iOS app.

Thanks and sorry for the large images.

**Comment by benbeton** [comment] 2024-01-09 07:26
thank you for the testing an Details. Nevertheless in my opinion the colors should never be shown faded, other users may ask themselves the same questions and maybe worried about. But I think It's really helpful to have your analysis

**Comment by s0nerik** [comment] 2024-03-09 18:28
> Is this only an IOS issue?

I'm seeing the same issue on Android as well with HDR videos recorded on iPhone 13 mini.

**Comment by mertalev** [comment] 2024-03-11 00:12
I believe the issue affects both iOS and Android. The underlying native players for both platforms support HDR, but the way Flutter interacts with them doesn't allow for it.

**Comment by blue-kaleidoscope** [comment] 2024-04-01 13:15
Using Immich on iPadOS HDR looks good and not pale. 🤔

**Comment by s0nerik** [comment] 2024-04-01 13:18
> Using Immich on iPadOS HDR looks good and not pale. 🤔

You're probably viewing the processed videos (where HDR was converted to SDR). The problem is with viewing the original HDR video.

**Comment by blue-kaleidoscope** [comment] 2024-04-01 13:22
That is possible, as there was some time difference between watching an HDR video on my iPhone, and then on my iPad.

**Comment by sannidhyaroy** [comment] 2024-05-15 08:35
Yes, I'm facing this as well. HDR 10 videos (shot on Galaxy S23) looks washed out in the Immich mobile app that looks perfectly fine in the web app. Will this issue not be resolved unless the core Flutter team works on flutter/flutter#91241?

**Comment by mertalev** [comment] 2024-05-15 13:47
> Will this issue not be resolved unless the core Flutter team works on flutter/flutter#91241

We will probably switch to the media_kit player, which doesn't have the issue of washed out videos since it tone-maps them.

Of course it'd be better if we could get proper HDR, but that might require writing a native Swift implementation and nobody in the team has a background in that.

**Comment by serfriz** [comment] 2024-05-18 01:45
I just want to confirm that I'm having the same issue with my Pixel 8 Pro (Android 14). HDR videos look washed out.

**Comment by televisedBow** [comment] 2024-05-18 04:08
> > Will this issue not be resolved unless the core Flutter team works on [flutter/flutter#91241](https://github.com/flutter/flutter/issues/91241)
> 
> We will probably switch to the media_kit player, which doesn't have the issue of washed out videos since it tone-maps them.
> 
> Of course it'd be better if we could get proper HDR, but that might require writing native iOS / Android implementations and nobody in the team has a background in that.

Tone mapping would be a good stop gap solution until the proper solution can be achieved. It's a shame that the flutter problem is literally years old at this point. I would hope that the prevalence of HDR on almost all new phones would cause some activity.

**Comment by Austinzveare** [comment] 2024-06-06 21:47
I just started using Immich and ran into this problem immediately. I have somewhat of a niche, but high quality workflow where I shoot ProRes Log on my iPhone 15 Pro Max, export from Davinci Resolve in HDR10 with metadata, then view in Plex, but ultimately would prefer Immich. The video plays back with correct color in Safari Immich on my iPhone and MacBook, and is just the app that doesn't display HDR properly, I have video transcoding effectively disabled. I really hope this can be worked on because I'd say for most, if not all iPhone users it's kind of a deal breaker in terms of video playback through Immich.

Quick side note. I know true HDR photography is still barely supported in any OS/software, but ever since Adobe Lightroom had editing support I've been waiting for the day for ANY viewer to actually display HDR JXL/AVIF properly. One can only hope that the next MacOS & iOS improve this.

**Comment by rinlv** [comment] 2024-06-19 02:32
same with me, it only happens on the mobile app

**Comment by hkrob** [comment] 2024-07-03 07:08
+1 here, Samsung S24 - non-transcoded video looks washed out on mobile, fine in desktop (Windows) browser.
As a stop-gap, would it be possible to add an option to open the file in a local player on mobile?

**Comment by d1scolor** [comment] 2024-08-04 10:48
Not sure about technical implementations but -
I have a Jellyfin server which has some HDR videos taken by iPhones.
In the Jellyfin's iOS app there is a "Use Native Video Player" beta option. When enabled, the iOS app plays the untranscoded iPhone HDR videos flawlessly.

**Comment by d1scolor** [comment] 2024-08-06 02:52
In addition to the pale look, the framerate of video playback appear to be lower than the source.

**Comment by Titaniumtown** [comment] 2024-08-18 04:36
I've experienced something like this with photos as well. But I'm also setting up a new camera so it could be a configuration issue :p

**Comment by mertalev** [comment] 2024-08-18 05:08
Just to give a little update on this: we're experimenting with [native_video_player](https://github.com/albemala/native_video_player), which from a PoC actually renders HDR and at a higher frame rate than the current player. But there are a few issues with it that we still need to figure out: it frequently crashes in debug mode (but not in the release version), and it doesn't let you add HTTP headers for network requests (for e.g. authorization).

**Comment by joaopedrocg27** [comment] 2024-11-03 11:39
Hey @mertalev 

Did you guys have any progress on this?

Thanks

**Comment by mertalev** [comment] 2024-11-03 14:20
As a matter of fact, yes! I'm currently doing testing and polishing on iOS. There are no major issues, just smaller things left - wakelock doesn't get disabled when you leave the video, the video position widget gets choppy when you scrub, etc. I'm hoping to get it merged very soon.

**Comment by joaopedrocg27** [comment] 2024-11-03 14:25
That is awesome! Thank you very much!

**Comment by Austinzveare** [comment] 2024-11-03 14:29
This is great, thanks for the update! Slightly related, is there progress on HDR photo support? Ideally JXL, or AVIF, JPG gain map etc.

**Comment by mertalev** [comment] 2024-11-03 14:34
> This is great, thanks for the update! Slightly related, is there progress on HDR photo support? Ideally JXL, or AVIF, JPG gain map etc.

No, we still need to look into alternative photo viewers that can display HDR. This is on my mind, but I personally won't be able to work on it in the short-term.

**Comment by RdWing** [comment] 2024-11-04 20:42
Discovered the other day that viewing Photos via icloud.com renders photos in HDR, at least while using Edge on Windows. The gain maps are being properly displayed and interpreted. Glaringly, attempting the same task via Immich leads to disappointment as HDR photos are nowhere to be found. Now that ISO 21496-1 is a standard, that can be brought into Immich?

**Closed** 2024-12-04 21:03 UTC
Labels: 📱mobile

**Comment by mertalev** [comment] 2024-12-04 21:05
I'm excited to say that the next release will have HDR video playback on both Android and iOS!

**Comment by alxjsn** [comment] 2025-01-13 02:50
> I'm excited to say that the next release will have HDR video playback on both Android and iOS!

This is exciting! Do we have to force a re-encode of all videos to reap the benefits?

**Comment by mertalev** [comment] 2025-01-13 03:35
> > I'm excited to say that the next release will have HDR video playback on both Android and iOS!
> 
> 
> 
> This is exciting! Do we have to force a re-encode of all videos to reap the benefits?

No, but whether the video is HDR depends on where it's sourced. If the video exists on the phone locally, it will always play the (HDR) original. However, if the app needs to stream the video from the server and the server transcoded this video, it will serve this SDR transcode instead. 

This will change in the next release - you'll be able to prefer streaming the (HDR) original even if there's a transcode available. Later releases will likely adapt transcoding to be more HDR-friendly now that the client support is better.
