### ISSUE TITLE
[Feature]: Partner Sharing

### ISSUE THREAD

**Issue by sbkg0002** [immich-app/immich#931] opened 2022-11-05 13:27 UTC
### Feature detail

Allow sharing of all media with other user(s). 

Currently there is a dumy 'Partner Sharing' button in the UI. This button should show all other users with a checkbox which will make all media visible in the partner's media overview.

Fixes: https://github.com/immich-app/immich/discussions/592

### Platform

Server

**Comment by bo0tzz** [comment] 2022-11-25 15:11
Duplicate of #637

**Closed by bo0tzz** 2022-11-25 15:11 UTC
Labels: feature
