### ISSUE TITLE
1.98.0 web only first 12 places displayed in /places

### ISSUE THREAD

**Issue by bhugh** [immich-app/immich#7740] opened 2024-03-08 13:14 UTC
### The bug

Since 1.98.0, only the first 12 places are listed in https://immich.myserver.org/places

I have >100 places that usually display.

In the mobile version, all expected places display.

### The OS that Immich Server is running on

Ubuntu 22.04 (WSL under Windows 10)

### Version of Immich Server

v1.98.0

### Version of Immich Mobile App

(not relevant)

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
(not relevant to this)
```

### Your .env content

```Shell
(not relevant to this)
```

### Reproduction steps

```bash
1. Make sure the photo collection has more than 12 geographical places represented 
2. Open Immich web site
2. Go to  https://immich.myserver.org/places (or click Explore, then "Places . . . view all")
3. Note that only the 1st 12 places are shown

It looks like the error is viewable on the Demo site as well - only the first 12 places are shown at https://demo.immich.app/explore  (I assume it has more than 12 actually places).
...
```

**Comment by bo0tzz** [comment] 2024-03-08 13:20
Duplicate of #7070

**Closed by bo0tzz** 2024-03-08 13:20 UTC
