### ISSUE TITLE
[mobile] android: automatic upload is disabled if folder is empty

### ISSUE THREAD

**Issue by thegabriele97** [immich-app/immich#12095] opened 2024-08-28 15:54 UTC
### The bug

Hello,
I'm new to Immich and I think I've an issue with how the android mobile app works.

If I enable automatic upload for "Camera" album and it has one photo it gets uploaded. If I take a new photo, it gets uploaded. If I delete both photos, the "Camera" album disappear thus automatic upload is turned off. If I take a new photo, it doesn't get uploaded anymore.

### The OS that Immich Server is running on

Android 12

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

1.112.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
It is the reccomended one for the latest version
```

### Your .env content

```Shell
same as docker-compose.yml
```

### Reproduction steps

1.enable automatic upload for "Camera" album
2.delete all photos from camera album
3.camera album is no longer tracked
...

**Comment by elinskyj** [comment] 2024-09-19 01:25
I have the same issue. I have an automated task set up to move photos from the camera folder on my phone to an archive folder on my pc weekly. This leaves the folder empty and subsequent photos do not sync to immich. I tried to work around this by having a text file in the folder, but immich doesn't see the album unless there is a photo in the folder.

**Comment by caetanoange** [comment] 2024-11-25 16:01
I have the same problem.

**Comment by bo0tzz** [comment] 2024-11-30 11:51
dupe of #7711

**Closed by bo0tzz** 2024-11-30 11:51 UTC
