### ISSUE TITLE
[Feature]: Allow specifying the endpoints using env variables.

### ISSUE THREAD

**Issue by blmhemu** [immich-app/immich#726] opened 2022-09-20 08:21 UTC
### Feature detail

For example, at https://github.com/immich-app/immich/blob/953d18e795ea2dca27621da5b86bc17d3bb0ab7e/web/src/api/api.ts#L44

The server is hard-coded assuming that the runtime is docker-compose and this url / dns works. Ideally, the app should be independent of this. We should rather use env variables and / or `process.env` to pass this (similar to how we do for postgres / redis). The same goes for proxy as well.
See 
https://github.com/immich-app/immich/blob/7a807f72164a6fbe8a058dacb29e127e509ee065/nginx/nginx.conf#L90
https://github.com/immich-app/immich/blob/7a807f72164a6fbe8a058dacb29e127e509ee065/nginx/nginx.conf#L65

More instances where this needs to be fixed:
https://github.com/immich-app/immich/blob/ccf792f9d315821cc12bc08d5f5e41e6f32e4e4f/server/apps/microservices/src/processors/metadata-extraction.processor.ts#L194
https://github.com/immich-app/immich/blob/ccf792f9d315821cc12bc08d5f5e41e6f32e4e4f/server/apps/microservices/src/processors/metadata-extraction.processor.ts#L214
### Platform

Web, Nginx (proxy)

**Comment by bo0tzz** [comment] 2022-10-31 09:45
Duplicate of #647

**Closed by bo0tzz** 2022-10-31 09:45 UTC
Labels: feature, need triage
