### ISSUE TITLE
[Bug] Web Explore > Places > View All shows only first 12 places

### ISSUE THREAD

**Issue by justinhorton** [immich-app/immich#7070] opened 2024-02-13 02:22 UTC
### The bug

In the web client, under the `Explore` tab, the `Places` section initially shows 7 places. Clicking `View All` shows just 12 places, but there are 100s in the library. On the iOS mobile app, you can see all of the places.

Perhaps also worth noting that the places shown in both cases are the first N alphabetically, so all of my visible places in the web client start with `A`.

This bug has been mentioned in closed issues in a couple of places, but as far as I can tell there is no open issue for it. Related:
* #6092 which added the `View All` button, but didn't change the underlying API to surface > 12 places.
* #6676 which as of now has some changes requested and has no open issue tracking it.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

v.194.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Standard: https://github.com/immich-app/immich/releases/download/v1.94.1/docker-compose.yml
```

### Your .env content

```Shell
Standard: https://github.com/immich-app/immich/releases/download/v1.94.1/example.env
```

### Reproduction steps

```bash
1. Ensure the test library has more than 12 places in the DB.
2. In the web client, click Explore.
3. Click View All. Only 12 places are shown.
```

**Comment by onyxogen** [comment] 2024-02-13 14:03
I can confirm this bug.

**Comment by DeltaTango69** [comment] 2024-02-15 17:35
Same for me

**Comment by count00zero** [comment] 2024-02-15 20:26
absolutely the same with my immich docker installation

**Comment by Vandewaetere** [comment] 2024-02-16 08:10
Same here.

**Comment by Cirion75** [comment] 2024-02-20 09:49
Same here

**Comment by drifter75** [comment] 2024-02-21 09:54
Still an issue in 1.95.1, shows only 12 places.

**Comment by anooki-c** [comment] 2024-02-29 06:06
still an issue in 1.96.0, shows only 12 places.

**Comment by drifter75** [comment] 2024-02-29 08:10
> I can confirm this bug. For example https://demo.immich.app/places

why all comments are getting marked as duplicate?

**Comment by onyxogen** [comment] 2024-02-29 10:22
Maybe because everyone is basically saying the same. But that's like it is when a bug is quite nasty like this one...

**Comment by kramadana** [comment] 2024-03-12 16:44
Still a problem on latest version

**Comment by fofBdx** [comment] 2024-03-13 10:03
Same here with 
- mobile app: 1.98.2.128
- server: 1.98.2 (Docker Desktop / win 11)
Into the mobile app, I have 37 places. Into the web app I only have the first 12 discovered ones (doesn't change no matter how much places I add)

**Comment by hgpuke** [comment] 2024-03-16 18:16
Let me add to this the fact that Swedish letters are handled incorrectly. All swedish letters "looking like an A" are sorted like an a in the Places listing. The correct sort order for the swedish alphabet is a, b, c, ..., z, å, ä, ö.

**Comment by mertalev** [comment] 2024-03-17 04:17
I don't think there's an objective ordering of letters that's correct for every language. I believe you can change this by setting a Swedish collation in the Postgres database.

**Comment by hgpuke** [comment] 2024-03-17 10:37
> I don't think there's an objective ordering of letters that's correct for every language. I believe you can change this by setting a Swedish collation in the Postgres database.

Thank you meralev. Yes, you are right, there is no such thing as a correct ordering of letters that suits every language. Each language has its own ordering. Therefore, I would suggest that Immich implement some sort of language setting and passes that on to Postgres if that is what solves the problem.

**Comment by aisbergde** [comment] 2024-03-17 14:41
and the Collation setting should not be used for the whole database or for a table, but just for the query, used here in this specific case.

**Comment by hgpuke** [comment] 2024-03-17 16:11
I notice that in the immich-database container, there is a setting "LANG=en_us.utf8". Would changing this to "sv_se.utf8" change the sort-order?

**Comment by julianwachholz** [comment] 2024-03-17 16:14
Can you please stay on topic? Start a new discussion or issue about the collation.

**Comment by hgpuke** [comment] 2024-03-18 10:30
Sorry. My fault.

**Closed** 2024-03-20 03:23 UTC
