### ISSUE TITLE
[Feature]: Free up space on the device

### ISSUE THREAD

**Issue by pluja** [immich-app/immich#391] opened 2022-07-29 18:01 UTC
### Feature detail

Immich is awesome, I've been using it for the past weeks, and with the upcoming features, it will become even more awesome.

One feature that I would love to have is an option to "Free up space", which would automatically delete any photos that have already been backed up. This feature is present in Google Photos AFAIK. The expected behavior for this feature would be pretty much the same as Google Photos for what I saw in this Reddit post:

https://farside.link/libreddit/r/Android/comments/381rvo/google_photos_helps_you_free_up_storage_space_by/

Keep up the good work with Immich! You're doing an awesome contribution to the self-hosted world :)

### Platform

Mobile App

**Comment by bo0tzz** [comment] 2022-07-29 18:03
This is probably a duplicate of #356 and/or #165

**Comment by alextran1502** [comment] 2022-07-29 18:04
Hello, thank you for the kind words, this is currently on the road map, so I will close this to avoid duplication. 

Please follow issue #165 for the most recent update on this feature.

**Closed by alextran1502** 2022-07-29 18:04 UTC
Labels: feature, need triage

**Comment by pluja** [comment] 2022-07-29 18:11
Oh, thank you. I haven't been able to find any issue looking up "free space". I guess I was using the wrong words.
