### ISSUE TITLE
[BUG] Upload gets stuck on .DNG files

### ISSUE THREAD

**Issue by Sirtz** [immich-app/immich#773] opened 2022-10-02 17:46 UTC
I have the problem that the backup stops all the time. I have the IOS app open, and usually it backups a couple dozen photos fine, then it backups another photo to 100% and stops. It doesn't continue on its own anymore. Restarting the backup or restarting the app makes it continue until it gets stuck again. It's a little bit annoying since I want to upload a large collection overnight. Running the TestFlight IOS app, and the latest self-hosted docker on a fresh install and fresh volumes. The Backup directory is on an external HDD, the host is the latest Ubuntu server. This behavior has been happening for many months no matter the server/iOS/app version. 

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X ] I have read thoroughly the README setup and installation instructions.
- [X ] I have included my `docker-compose` file.
- [X ] I have included my redacted `.env` file.
- [X ] I have included information on my machine, and environment.

**To Reproduce**
1. Start Backup
2. Wait for .DNG file to get stuck

**Screenshots**
![immich-app](https://user-images.githubusercontent.com/26656736/193468283-5f154d34-4417-4309-bb80-0d6c4ac56b70.png)
![Camera settings 1](https://user-images.githubusercontent.com/26656736/193468335-e9c6447d-0570-49dd-ba62-b3e72195ebaf.png)
![Camera settings 2](https://user-images.githubusercontent.com/26656736/193468347-9129d2d6-9597-4dde-a2d9-a330a541e409.jpeg)

**System**
- IOS 16.0
- Latest, fresh instance from last week
- Latest from TestFlight

[docker-compose.yml.txt](https://github.com/immich-app/immich/files/9693116/docker-compose.yml.txt)
[env.txt](https://github.com/immich-app/immich/files/9693117/env.txt)

Example raw picture, I don't know if this specific one got stuck while uploading, but it is likely typical of the ones that get stuck 
https://upload.fritzcloud.eu/eNiTdA

Found a picture that got stuck, sadly can't share it here but the settings are: RAW, 12MP front camera 4032 x 3094, 31.9MB ISO 1000      Nothing different from my example picture from what I can see

**Comment by alextran1502** [comment] 2022-10-03 13:19
I took about 50 raw photos to test and I haven't been able to reproduce the issue yet.

Can you let me know if you are accessing your instance locally or through a DNS/Reverse Proxy? Could it be anything in your network setting causing this issue?

**Comment by Sirtz** [comment] 2022-10-03 13:37
I usually access through nginx-proxy-manager, just tried local access with the problem persisting. I am just wondering, once you upload, does the machine learning stuff kick in? Maybe my machine is getting overloaded and getting stuck? It's running on a 5 year old dualcore i7 laptop cpu which is not the fastest, but 16gb ram at least. I will check if I get any cpu overloading with glances.

**Comment by alextran1502** [comment] 2022-10-03 13:59
@Sirtz My machine learning stuff kicked in. Let's try to disable the machine learning container and try upload again to see if it is the cause.

**Comment by Sirtz** [comment] 2022-10-04 21:16
No that did not make a difference sadly

**Comment by Sirtz** [comment] 2022-10-04 21:16
That did not help sadly.

**Comment by Sirtz** [comment] 2022-10-09 08:32
I think this happens on high server CPU load. Experimenting with that currently

**Comment by alextran1502** [comment] 2022-10-09 13:05
@Sirtz what is the resource do you allocate for Immich? I can try replicate that on my end

**Comment by Sirtz** [comment] 2022-10-09 14:46
I used to not put any resource limits, now for testing I put immich-server at 0.1 cpu:

``` services:
  immich-server:
    deploy:
      resources:
        limits:
          cpus: '0.1'
```

**Comment by alextran1502** [comment] 2022-10-09 21:21
Is this safe to assume that the issue is not with the app but with the requirement of the system?

Can you help provide the information of your server so we can document this case?

**Comment by Sirtz** [comment] 2022-10-13 11:43
![image](https://user-images.githubusercontent.com/26656736/195586807-59cb8464-1839-40a2-886d-5eaa3c6a6f3c.png)

Not super powerful and I have quite a lot of services running. I hope you will be able to reproduce it, maybe try a high cpu load and then start backing up?

**Comment by alextran1502** [comment] 2022-11-30 16:28
Hello, to check in if this issue has been fixed with the recent releases?

**Comment by Sirtz** [comment] 2022-12-03 11:34
Sadly still open, on upload microservices take a lot of CPU, then stuck at 100%

![image](https://user-images.githubusercontent.com/26656736/205438935-7193d5e5-b39b-448d-aa6a-5e9e571160cf.png)

**Comment by Sirtz** [comment] 2022-12-19 19:58
Feeling pretty stupid rn, apparently the photos getting stuck were only on iCloud. I downloaded my whole library of photos, now the Immich backup works. Thanks for the help.

**Closed** 2022-12-19 19:58 UTC
Labels: bug, need triage

**Comment by alextran1502** [comment] 2022-12-19 20:09
No problem... I know there is a problem with iCloud photos, but I forgot to ask about it this issue.
