### ISSUE TITLE
[BUG] thumbnails colored after dismissing update announcement

### ISSUE THREAD

**Issue by XeroX1988** [immich-app/immich#2928] opened 2023-06-24 05:46 UTC
### The bug

Thumbnails are pink/purple after dismissing new update message.

### The OS that Immich Server is running on

Unraid Docker

### Version of Immich Server

V1.6.2

### Version of Immich Mobile App

V1.6.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not using compose
```

### Your .env content

```Shell
Not using compose
```

### Reproduction steps

```bash
1. Open mobile app
2. Browse announcement to see new goodies
3. Go back and acknowledge new update message
4. Thumbnails show up pink/purple

Got a screenshot, not able to upload at this moment.

Fully closing the app and reopening resolves the issue
```

**Comment by bo0tzz** [comment] 2023-06-24 07:26
Duplicate of #2827

**Closed** 2023-06-24 07:26 UTC
Labels: bug, need triage
