### ISSUE TITLE
Immich web translation 

### ISSUE THREAD

**Issue by PterX** [immich-app/immich#6920] opened 2024-02-05 15:47 UTC
### The bug

First of all, thank you very much for your efforts, but the localization of the web interface is still missing. If it can be implemented in code, we can help translate it.

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

v1.94.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
nothing
```

### Your .env content

```Shell
nothing
```

### Reproduction steps

```bash
First of all, thank you very much for your efforts, but the localization of the web interface is still missing. If it can be implemented in code, we can help translate it.
```

**Comment by bo0tzz** [comment] 2024-02-05 15:48
Duplicate of #1688. Please use the discussions for feature requests.

**Closed by bo0tzz** 2024-02-05 15:48 UTC
