### ISSUE TITLE
[BUG] loading timeline on mobile app needs optimization

### ISSUE THREAD

**Issue by thierrybla** [immich-app/immich#3029] opened 2023-06-29 14:02 UTC
### The bug

When I open the app it takes between 10-30 seconds to see my photos.
"Building the timeline" takes very long, I am not sure if it's only with my device but heard more people saying the same with Google pixel phones.

When I open it in a webpage it is instant.

I use a Google Pixel 7 Pro with Android 13

### The OS that Immich Server is running on

Truenas Scale, K3S, ghcr.io/imagegenius/immich:latest

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

v1.64.0 build.87

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - CUDA_ACCELERATION=false #optional
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_machine-learning:/config/machine-learning #optional
    ports:
      - 8080:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - path_to_postgres:/var/lib/postgresql/data
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Download app
2. Add server
3. Login
4. Setup albums
5. Close app
6. Open app
7. Building timeline (10-30 seconds)...
8. See photos
```

**Comment by alextran1502** [comment] 2023-06-29 14:04
This is a known issue and the work to optimization will take place in the future

**Comment by thierrybla** [comment] 2023-06-29 14:05
> This is a known issue, and the work for optimization will take place in the future

Do you want me to close this issue? Is it listed somewhere else? I couldn't find it.

**Comment by alextran1502** [comment] 2023-06-29 14:17
You can leave it open, I think we know about this internally but there is no opened issue to track

**Comment by jerrellmardis** [comment] 2023-07-12 04:30
Correct me if I’m wrong @alextran1502  but I believe part of the problem is that the API doesn’t support paging and is returning every asset instead of a subset when the timeline refreshes.

**Comment by alextran1502** [comment] 2023-07-12 04:32
@jerrellmardis correct, since the mobile app rendering mechanism is different from the web, and with offline support requirement for the mobile app. This is a harder issue to resolve, we are planning to refactor these parts in the future for the mobile app

**Comment by jho1670** [comment] 2023-08-23 22:51
Gentle nudge: This hits me every single time I open the app -- and is extremely painful. Given the impact is there anything that can be done sooner?

I appreciate all the work that everyone has put in :)

**Comment by alextran1502** [comment] 2023-08-23 23:44
@jho1670 fyi, an improvement is on the way to overcome this issue

**Comment by jerrellmardis** [comment] 2023-08-23 23:46
@alextran1502 is there a discussion or PR to follow the development of this improvement? I'm using the API and am curious if the improvement is with the introduction of a paged api endpoint or something else?

**Comment by alextran1502** [comment] 2023-08-23 23:47
This is PR https://github.com/immich-app/immich/pull/3824 will be a foundation for said improvement

**Comment by jrasm91** [comment] 2023-08-24 00:31
I think the idea is basically instead of redownloading the entire list of assets on each startup (a bigger problem for users with large collections), the mobile app can get a list of recent changes and only download an incremental delta.

**Comment by thierrybla** [comment] 2023-09-12 20:06
Hi, thanks for this work. Are we supposed to see the change already? Or is it scheduled for the next release? I have everything updated and don't see any difference yet.

**Comment by jrasm91** [comment] 2023-09-12 20:36
It is closed when implemented and then will be in the next release.

**Comment by jho1670** [comment] 2023-09-13 16:22
Server on 1.78.0, Android device running 1.78.0 build 101.

I've opened and closed Immich a few times, and each time, I continue to see the same (long duration) "Building timeline...If this is your first time using the app..." message appearing for 10-30 seconds.
[Immich_log_2023-09-13T09.20.19.629649.csv](https://github.com/immich-app/immich/files/12599825/Immich_log_2023-09-13T09.20.19.629649.csv)

**Comment by derekpurdy** [comment] 2023-09-13 16:27
> Server on 1.78.0, Android device running 1.78.0 build 101.
> 
> I've opened and closed Immich a few times, and each time, I continue to see the same (long duration) "Building timeline...If this is your first time using the app..." message appearing for 10-30 seconds. [Immich_log_2023-09-13T09.20.19.629649.csv](https://github.com/immich-app/immich/files/12599825/Immich_log_2023-09-13T09.20.19.629649.csv)

Pixel 5 here. Mine is instant now. Feels like Google Photos!

**Comment by fyfrey** [comment] 2023-09-13 19:59
Could you all say how many assets you have 1. on the server and 2. on the device. Also please provide the app logs directly after the long timeline building. Thank you.

**Comment by derekpurdy** [comment] 2023-09-13 20:06
Device: Backup 2042 assets, Total 1649 assets, Remainder -393 assets
Server: 97,928 photos, 105 videos

```
created_at,level,context,message,stacktrace
2023-09-13 16:04:55.569307,LogLevel.INFO,"AssetNotifier","Load assets: 526ms",""
2023-09-13 16:04:55.569123,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-09-13 16:04:55.568211,LogLevel.INFO,"AlbumService","'Recents' is not selected, keeping only selected albums",""
2023-09-13 16:04:55.568116,LogLevel.INFO,"AlbumService","Found 19 device albums",""
2023-09-13 16:04:55.107127,LogLevel.INFO,"BackupNotifier","Found 19 local albums",""
2023-09-13 16:04:55.045285,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
2023-09-13 16:04:29.920446,LogLevel.INFO,"AssetNotifier","Load assets: 263ms",""
2023-09-13 16:04:29.920295,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-09-13 16:04:29.899724,LogLevel.INFO,"AlbumService","'Recents' is not selected, keeping only selected albums",""
2023-09-13 16:04:29.899566,LogLevel.INFO,"AlbumService","Found 19 device albums",""
2023-09-13 16:04:29.887096,LogLevel.INFO,"AlbumService","refreshDeviceAlbums is already in progress",""
2023-09-13 16:04:29.725314,LogLevel.INFO,"BackupNotifier","Found 19 local albums",""
2023-09-13 16:04:29.660854,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
```

**Comment by zsolt-donca** [comment] 2023-09-13 20:38
Device: Total 1426, Backup 1698, Remainder: -272
Server: 68213 photos, 2864 videos

```
created_at,level,context,message,stacktrace
2023-09-13 23:36:43.020909,LogLevel.INFO,"AssetNotifier","Load assets: 276ms",""
2023-09-13 23:36:43.020631,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-09-13 23:36:43.014811,LogLevel.INFO,"AlbumService","'Recents' is not selected, keeping only selected albums",""
2023-09-13 23:36:43.014668,LogLevel.INFO,"AlbumService","Found 31 device albums",""
2023-09-13 23:36:42.980923,LogLevel.INFO,"AlbumService","refreshDeviceAlbums is already in progress",""
2023-09-13 23:36:42.816292,LogLevel.INFO,"BackupNotifier","Found 31 local albums",""
2023-09-13 23:36:42.707006,LogLevel.INFO,"BackupNotifier","[_resumeBackup] Start back up",""
```

**Closed** 2023-09-28 03:43 UTC
Labels: enhancement, 📱mobile

**Comment by gomme600** [comment] 2024-02-27 10:09
Hi, I'm still experiencing this on the latest version. Is it supposed to be fixed ? Have about 500gb or assets on the server and 12gb on device.

**Comment by gomme600** [comment] 2024-02-27 10:20
https://github.com/immich-app/immich/assets/35890638/9f5f8204-8af5-42eb-a77e-e3c19d41ece5

![Screenshot_20240227_111037_edit_109662407727385](https://github.com/immich-app/immich/assets/35890638/65f0a440-3e6b-4426-8bb7-408c269c9e1b)

**Comment by alextran1502** [comment] 2024-02-27 15:16
@gomme600, that is pretty slow for 500GB. Were you using a proxy? what is your internet connection is like and what phone model is that?

**Comment by bergerx** [comment] 2024-11-17 04:01
I'm using v1.118.2.
I have 1.3T photos + 500G external library (postgres data folder is 10G).
Using the mobile app on on my Pixel 7 on internal wifi that i watch 4k videos without issues.
It takes **more than a minute** to get passed the "Building the Timeline" screen.

I use the app pretty much only for the auto-upload feature, and using the web interface even on my phone to view the photos.

**Comment by eKristensen** [comment] 2024-12-24 12:53
I have the same issue. About 800GB, a bit more than 100.000. The app is always quite slow to open always building the timeline over and over again
