### ISSUE TITLE
[BUG] Asset dates incorrect

### ISSUE THREAD

**Issue by dankasak** [immich-app/immich#4492] opened 2023-10-16 04:15 UTC
### The bug

My understanding ( based on reviewing other immich bugs ) is that immich should attempt to parse the creation date from EXIF tags, and if this fails, it should fallback to the file creation date. I have quite a few examples where the date in immich is neither of these dates. For example:

![IMG_20231013_145224](https://github.com/immich-app/immich/assets/7410307/1217fe11-678a-4d21-82b2-ef2cee0f6dce)

The date as showing in immich is 14 Oct 2023 Sat, 1:52 am GMT+11:00

If I extract metadata ( which appears correct ) with imagemagick's "identify", I can see:

  Properties:
    exif:DateTime: 2023:10:13 14:52:26
    exif:DateTimeDigitized: 2023:10:13 14:52:26
    exif:DateTimeOriginal: 2023:10:13 14:52:26

Full command/output:

[dankasak@mercury 2023-10-13]$ identify -verbose IMG_20231013_145224.jpg
Image:
  Filename: IMG_20231013_145224.jpg
  Permissions: rw-r--r--
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Mime type: image/jpeg
  Class: DirectClass
  Geometry: 3648x2736+0+0
  Resolution: 72x72
  Print size: 50.6667x38
  Units: PixelsPerInch
  Colorspace: sRGB
  Type: TrueColor
  Base type: Undefined
  Endianness: Undefined
  Depth: 8-bit
  Channels: 3.0
  Channel depth:
    Red: 8-bit
    Green: 8-bit
    Blue: 8-bit
  Channel statistics:
    Pixels: 9980928
    Red:
      min: 0  (0)
      max: 255 (1)
      mean: 116.015 (0.454962)
      median: 123 (0.482353)
      standard deviation: 55.0101 (0.215726)
      kurtosis: -0.679831
      skewness: -0.171618
      entropy: 0.963029
    Green:
      min: 0  (0)
      max: 251 (0.984314)
      mean: 104.081 (0.408161)
      median: 104 (0.407843)
      standard deviation: 55.6608 (0.218278)
      kurtosis: -0.720299
      skewness: 0.252223
      entropy: 0.965084
    Blue:
      min: 0  (0)
      max: 250 (0.980392)
      mean: 89.4371 (0.350734)
      median: 82 (0.321569)
      standard deviation: 55.9944 (0.219586)
      kurtosis: -0.535097
      skewness: 0.569715
      entropy: 0.955618
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 103.178 (0.404619)
      median: 103 (0.403922)
      standard deviation: 55.5551 (0.217863)
      kurtosis: -0.819718
      skewness: 0.202407
      entropy: 0.961244
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33,0.03)
    green primary: (0.3,0.6,0.1)
    blue primary: (0.15,0.06,0.79)
    white point: (0.3127,0.329,0.3583)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 3648x2736+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 97
  Orientation: Undefined
  Profiles:
    Profile-app7: 28532 bytes
    Profile-app8: 35122 bytes
    Profile-app9: 21562 bytes
    Profile-exif: 42684 bytes
  Properties:
    date:create: 2023-10-15T07:26:26+00:00
    date:modify: 2023-10-15T07:26:24+00:00
    date:timestamp: 2023-10-16T03:57:01+00:00
    exif:ApertureValue: 135/100
    exif:BitsPerSample: 8, 8, 8
    exif:BrightnessValue: 0/1
    exif:ColorSpace: 1
    exif:ComponentsConfiguration: ...
    exif:CompressedBitsPerPixel: 95/100
    exif:Contrast: 0
    exif:CustomRendered: 1
    exif:DateTime: 2023:10:13 14:52:26
    exif:DateTimeDigitized: 2023:10:13 14:52:26
    exif:DateTimeOriginal: 2023:10:13 14:52:26
    exif:DeviceSettingDescription: ipp
    exif:DigitalZoomRatio: 100/100
    exif:DocumentName:
    exif:ExifOffset: 284
    exif:ExifVersion: 0210
    exif:ExposureBiasValue: 0/10
    exif:ExposureMode: 0
    exif:ExposureProgram: 2
    exif:ExposureTime: 16667000/1000000000
    exif:FileSource: .
    exif:Flash: 0
    exif:FlashPixVersion: 0100
    exif:FNumber: 160/100
    exif:FocalLength: 5560/1000
    exif:FocalLengthIn35mmFilm: 27
    exif:GainControl: 0
    exif:ImageDescription: rpt
    exif:ImageLength: 2736
    exif:ImageWidth: 3648
    exif:InteroperabilityOffset: 1310
    exif:LightSource: 1
    exif:Make: HUAWEI
    exif:MakerNote: ####.
    exif:MaxApertureValue: 135/100
    exif:MeteringMode: 5
    exif:Model: VOG-L29
    exif:PhotographicSensitivity: 100
    exif:PixelXDimension: 3648
    exif:PixelYDimension: 2736
    exif:Saturation: 0
    exif:SceneCaptureType: 0
    exif:SceneType: .
    exif:SensingMethod: 2
    exif:Sharpness: 0
    exif:ShutterSpeedValue: 298973/10000
    exif:Software: VOG-L29 12.0.0.169(C636E1R1P1)
    exif:SubjectDistanceRange: 0
    exif:SubSecTime: 280916
    exif:SubSecTimeDigitized: 280916
    exif:SubSecTimeOriginal: 280916
    exif:thumbnail:Compression: 6
    exif:thumbnail:ImageLength: 384
    exif:thumbnail:ImageWidth: 512
    exif:thumbnail:InteroperabilityIndex: R98
    exif:thumbnail:InteroperabilityVersion: 0100
    exif:thumbnail:JPEGInterchangeFormat: 1470
    exif:thumbnail:JPEGInterchangeFormatLength: 41208
    exif:thumbnail:Orientation: 0
    exif:thumbnail:ResolutionUnit: 2
    exif:thumbnail:XResolution: 72/1
    exif:thumbnail:YResolution: 72/1
    exif:WhiteBalance: 0
    exif:YCbCrPositioning: 1
    jpeg:colorspace: 2
    jpeg:sampling-factor: 2x2,1x1,1x1
    signature: 37a0638fd0154d34ba9e27ad7be7d938a62a88f0d5c8001d7271aa0dbce39655
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 6.33305MiB
  Number pixels: 9.98093M
  Pixel cache type: Memory
  Pixels per second: 147.342MP
  User time: 0.060u
  Elapsed time: 0:01.067
  Version: ImageMagick 7.1.1-15 Q16-HDRI x86_64 21298 https://imagemagick.org

I did not edit any of these on my device, so I can't see how the image "creation" date would be different from the date in exif metadata.

### The OS that Immich Server is running on

Fedora / podman

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

1.80.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${PHOTOPRISM_LOCATION}:/photoprism:ro
    env_file:
      - .env
    depends_on:
      - redis
#      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${PHOTOPRISM_LOCATION}:/photoprism:ro
    env_file:
      - .env
    depends_on:
      - redis
#      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${MODEL_CACHE_LOCATION}:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - ${TYPESENSE_LOCATION}:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

#  database:
#    container_name: immich_postgres
#    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
#    env_file:
#      - .env
#    environment:
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_DB: ${DB_DATABASE_NAME}
#    volumes:
#      - ${PG_LOCATION}:/var/lib/postgresql/data
#    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/array0/immich/uploads
PG_LOCATION=/mnt/array0/immich/postgres
MODEL_CACHE_LOCATION=/mnt/array0/immich/model-cache
TYPESENSE_LOCATION=/mnt/array0/immich/typesense

#PHOTOPRISM_LOCATION=/mnt/array0/photoprism/originals
PHOTOPRISM_LOCATION=/mnt/array0/photoprism-christel/originals

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=aaaaa
DB_PASSWORD=bbbbb

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=192.168.1.128
DB_USERNAME=immich
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

# Custom Ports
#PORT=3100
#SERVER_PORT=3101
#MICROSERVICES_PORT=3102
#MACHINE_LEARNING_PORT=3103
```

### Reproduction steps

```bash
1. Import photos
2. Observe some have the wrong datetime - often 1 day later than when taken
```

**Comment by deiop** [comment] 2023-10-16 06:07
Timezone difference ?

**Comment by jrasm91** [comment] 2023-10-16 14:37
Timezone is inferred from exif, unless it doesn't have any timezone information, then it defaults to the local time zone. Not a whole lot more we can do. You can fix your metadata and re-upload the image though.

**Comment by dankasak** [comment] 2023-10-17 00:00
> You can fix your metadata and re-upload the image though.

Yes I've considered this - but to be honest, I can't imagine this being a palatable option for most people.

> then it defaults to the local time zone

Yes that was what I expected, however I'm seeing inconsistent behaviour in this respect. For example, the following image has the correct timestamp:

![IMG_20230924_151422](https://github.com/immich-app/immich/assets/7410307/23ea94d1-8554-4852-a83b-d6a6545b5a0e)

I see the following metadata from imagemagick:

  Properties:
    date:create: 2023-10-16T23:34:43+00:00
    date:modify: 2023-10-16T23:34:40+00:00
    date:timestamp: 2023-10-16T23:35:02+00:00
...
    exif:DateTime: 2023:09:24 15:14:24
    exif:DateTimeDigitized: 2023:09:24 15:14:24
    exif:DateTimeOriginal: 2023:09:24 15:14:24

In this case, the correct timestamp is 2023:09:24 15:14:24 - and immich is showing "details":
 24 Sept 2023 Sun, 3:14 pm GMT+10:00
 
 I have **not** been altering my TZ, or anything else on the server running immich. So it seems that sometimes this timezone detection is working, and others it is not.

**Comment by jrasm91** [comment] 2023-10-17 00:25
The image has gps coordinates that indicate it was taken in the `Australia/Sydney` and it assumes `2023:09:24 15:14:24` is local time in that timezone. So again, working as designed.

BTW, we don't use imagemagick, we use `exiftool <filename>` more or less.

**Comment by jrasm91** [comment] 2023-10-17 00:26
> Yes I've considered this - but to be honest, I can't imagine this being a palatable option for most people.

Well, the available options include:
- Use XMP sidecar files to correct the data (https://immich.app/docs/features/xmp-sidecars)
- Delete and re-upload the file
- Wait until we build a full metadata editor, which is probably not going to happen any time soon.

**Comment by dm3010** [comment] 2023-10-17 07:27
Found the same problem.
There are two photos taken with the same phone on the same day (3 hours apart):

IMG_20230822_150057.jpg
IMG_20230822_180153.jpg

Uploaded via mobile app
Before uploading to the server, the info section in the app shows the correct time for all photos and videos
After uploading the first photo shows +3 hours, i.e. 18:00:57 GMT+03:00.
The second photo is set correctly for my time zone, 18:01:53 GMT+03:00.
Exif data in both photos are made by the same camera

VID_20230822_145410.mp4
Video uploaded from the same series of photos time set to -3 hours
11:57:10 UTC, i.e. seems to be correct, but not in my time zone

**Comment by jrasm91** [comment] 2023-10-17 11:52
Going to close this as everything is currently working as designed and there are no action steps to be taken.

@dm3010 you can open a new issue if you want me to take a look at your files. Please post the exif of the file in question, which should include date time values and optionally gps data if available.

**Closed** 2023-10-17 11:52 UTC
Labels: bug, need triage

**Comment by psyciknz** [comment] 2024-07-02 00:28
> Found the same problem. There are two photos taken with the same phone on the same day (3 hours apart):
> 
> IMG_20230822_150057.jpg IMG_20230822_180153.jpg
> 
> Uploaded via mobile app Before uploading to the server, the info section in the app shows the correct time for all photos and videos After uploading the first photo shows +3 hours, i.e. 18:00:57 GMT+03:00. The second photo is set correctly for my time zone, 18:01:53 GMT+03:00. Exif data in both photos are made by the same camera
> 
> VID_20230822_145410.mp4 Video uploaded from the same series of photos time set to -3 hours 11:57:10 UTC, i.e. seems to be correct, but not in my time zone

With reference to XMP files.   I have an image where I've recently created an XMP file for it.
When it has been rescanned by immich in the external library, the photo has been dated the XMP creation time and the file exif date/time has been ignored.
