### ISSUE TITLE
jobs can get stuck until a server restart

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3178] opened 2023-07-09 15:58 UTC
### The bug

Maybe related to #2877. I imported a large amount of assets and most of them were missing thumbnails. It didn't matter how many times I would ask Immich to try regenerating thumbnails and extract metadata it didn't help until I restarted the server and microservice containers. Only then could I ask Immich to regenerate the thumbnails, which did work. I verified the assets with missing thumbnails had exif data, so it wasn't stuck on that.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.66.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by isaaclyman** [comment] 2023-08-01 04:39
See also #2957. I think it may have the same root cause.

**Comment by mertalev** [comment] 2024-03-10 23:02
Closing this since it's old and I don't think I've seen this in a very long time. Feel free to re-open if it's still relevant.

**Closed by mertalev** 2024-03-10 23:02 UTC
Labels: bug, 🗄️server
