### ISSUE TITLE
Searching for albums does not work on mobile

### ISSUE THREAD

**Issue by Johnny-755** [immich-app/immich#14951] opened 2024-12-27 11:49 UTC
### The bug

Searching albums does return the entire list of all albums for all search-queries. This happens only on mobile, in the browser-version the search does indeed return only the albums that match the query

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.123

### Version of Immich Mobile App

1.123

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. Navigate to Albums page on mobile
2. enter (part) of the name of one of the albums
3. result should now show only matching albums, but currently it shows all
...

**Comment by bo0tzz** [comment] 2024-12-27 12:43
I can't reproduce this. Can you share a screen recording?

**Comment by Johnny-755** [comment] 2024-12-27 13:12
ok very interesting, now that I wanted to recreate this (I had this issue on 3 different phones), its working. 

Its related to some caching. I didnt open the albums on all phones for a long time and it felt slow when working in it. After waiting for several minutes all phones seem to have cached all albums and then the search worked.

When deleting the app and installing it again the problem occures again until the cache is build up again. 

does it still count as a bug?

**Comment by bo0tzz** [comment] 2024-12-27 13:53
I can't reproduce this even by wiping app cache, so I'll close this issue for now. If you have a working reproduction we can reopen it of course.

**Closed by bo0tzz** 2024-12-27 13:53 UTC

**Comment by Johnny-755** [comment] 2024-12-27 20:23
The precondition for the working reproduction is a sizeable library so that the initial creation of the cache will take some time.

In my case I have many hundred albums and almost 100k images. It looks like as for every album there is a thumbnail being created on the device? That process takes a few minutes and in this time its impossible to search. 


A simple bugfix could be to indicate this in the search-bar (disable it or show an hour-glass icon)

**Comment by alextran1502** [comment] 2024-12-29 14:55
There is an opened issue regarding this bug, so it won't get lost

**Comment by Johnny-755** [comment] 2024-12-29 18:32
> There is an opened issue regarding this bug, so it won't get lost

oh sorry, I didnt found it. Thank you very much :) 
could you link the other issue here? please

**Comment by alextran1502** [comment] 2024-12-29 19:33
#13466
