### ISSUE TITLE
[BUG] Can't launch Android app anymore after updating to 1.47.0

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#1815] opened 2023-02-21 14:46 UTC
### The bug

When launching the app, it is stuck on the logo loading.
It does not launch anymore.

### The OS that Immich Server is running on

Synology DSM 7.2

### Version of Immich Server

v1.47.3

### Version of Immich Mobile App

v1.47.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
# I don't think the docker-compose.yml is relevant for this issue, but here it is anyway

version: "3.8"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    networks:
      - traefik_proxy
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_proxy
      traefik.http.services.immich-api-svc.loadbalancer.server.port: "3001"
      traefik.http.routers.immich-api-rtr.rule: "Host(`immich.$DOMAINNAME`) && Pathprefix(`/api`)"
      traefik.http.routers.immich-api-rtr.priority: 20
      traefik.http.middlewares.immich-api-strip.stripprefix.prefixes: "/api"
      traefik.http.routers.immich-api-rtr.middlewares: immich-api-strip,chain-basic@file
      traefik.http.routers.immich-api-rtr.service: immich-api-svc
      traefik.http.routers.immich-api-rtr.tls: true
      traefik.http.routers.immich-api-rtr.tls.certresolver: dns-cloudflare
      traefik.http.routers.immich-api-rtr.entrypoints: https

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    build:
      context: $DOCKERDIR/immich/immich-ml
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - default
      - traefik_proxy
    env_file:
      - .env
    restart: always
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_proxy
      traefik.http.services.immich-svc.loadbalancer.server.port: "3000"
      traefik.http.routers.immich-rtr.rule: "Host(`immich.$DOMAINNAME`)"
      traefik.http.routers.immich-rtr.priority: 10
      traefik.http.routers.immich-rtr.service: immich-svc
      traefik.http.routers.immich-rtr.middlewares: chain-basic@file
      traefik.http.routers.immich-rtr.tls: true
      traefik.http.routers.immich-rtr.tls.certresolver: dns-cloudflare
      traefik.http.routers.immich-rtr.entrypoints: https

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - default
    command: redis-server /etc/redis.conf
    volumes:
      - sockets:/sockets
      - $DOCKERDIR/immich/redis.conf:/etc/redis.conf
      - /etc/TZ:/etc/timezone:ro
      - $DOCKERDIR/immich/redisdb:/db

  database:
    container_name: immich_postgres
    image: postgres:14-bullseye
    user: 1026:100
    command: postgres -c unix_socket_directories='/var/run/postgresql/,/sockets/'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
      PGPORT: ${DB_PORT}
    volumes:
      - $DOCKERDIR/immich/pgdata:/var/lib/postgresql/data
      - sockets:/sockets
    restart: always

volumes:
  sockets:
    external: true
```

### Your .env content

```Shell
# I don't think the .env file is relevant, but here it is anyway

DB_HOSTNAME=/sockets
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
DB_PORT=5433
REDIS_PASSWORD="redispassword"
REDIS_SOCKET=/sockets/immich_redis.sock
UPLOAD_LOCATION=/uploads
JWT_SECRET=jwtsecret
REVERSE_GEOCODING_PRECISION=3
```

### Reproduction steps

```bash
1. Launch app.
2. See error
```

### Additional information

**Logcat**
```
2-21 15:39:02.489  4557  4557 W alextran.immich: type=1400 audit(0.0:53): avc: denied { read } for name="max_map_count" dev="proc" ino=60321 scontext=u:r:untrusted_app:s0:c170,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=app.alextran.immich
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: QUALCOMM build                   : 9fb8420ccd, I4cee0650f2
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: Build Date                       : 05/17/21
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.12
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: Local Branch                     :
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: Remote Branch                    :
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: Remote Branch                    :
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: Reconstruct Branch               :
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
02-21 15:39:02.502  4557  4557 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
02-21 15:39:02.506  4557  4557 I AdrenoGLES-0: PFP: 0x016ee197, ME: 0x00000000
02-21 15:39:02.574  4557  4557 D BackupWorker: startWork
02-21 15:39:02.574  4557  4586 W FlutterJNI: FlutterJNI.loadLibrary called more than once
02-21 15:39:02.574  4557  4581 W FlutterJNI: FlutterJNI.prefetchDefaultFontManager called more than once
02-21 15:39:02.576  4557  4575 I WM-Processor: Moving WorkSpec (de6711dc-ebf9-498f-9db6-b1137dcc67de) to the foreground
02-21 15:39:02.589  4557  4557 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=app.alextran.immich/androidx.work.impl.foreground.SystemForegroundService (has extras) }
02-21 15:39:02.590  4557  4557 W FlutterJNI: FlutterJNI.init called more than once
02-21 15:39:02.652  4557  4587 I flutter : Enabled high refresh mode
02-21 15:39:02.657  4557  4587 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Could not initialize IsarCore library for processor architecture "android_arm64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
02-21 15:39:02.657  4557  4587 E flutter : Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
02-21 15:39:02.657  4557  4587 E flutter : #0      initializeCoreBinary (package:isar/src/native/isar_core.dart:78)
02-21 15:39:02.657  4557  4587 E flutter : #1      openIsar (package:isar/src/native/open.dart:81)
02-21 15:39:02.657  4557  4587 E flutter : #2      Isar.open (package:isar/src/isar.dart:107)
02-21 15:39:02.657  4557  4587 E flutter : #3      loadDb (package:immich_mobile/main.dart:82)
02-21 15:39:02.657  4557  4587 E flutter : <asynchronous suspension>
02-21 15:39:02.657  4557  4587 E flutter : #4      main (package:immich_mobile/main.dart:38)
02-21 15:39:02.657  4557  4587 E flutter : <asynchronous suspension>
02-21 15:39:02.657  4557  4587 E flutter :
02-21 15:39:02.764  4557  4557 D BackupWorker: stopEngine result=Success {mOutputData=Data {}}
02-21 15:39:02.766  4557  4584 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=de6711dc-ebf9-498f-9db6-b1137dcc67de, tags={ app.alextran.immich.BackupWorker } ]
02-21 15:39:02.781  4557  4557 I WM-SystemFgDispatcher: Stopping foreground service
```

**Extra info** 
Android version 12.
Fairphone 4
Installed from F-droid.
There are no Google Play Services on my phone. I'm using /e/ OS (a fork of LineageOS) with MicroG.

**Comment by JVT038** [comment] 2023-02-21 14:48
I'm guessing this is caused by #1416.

Anyway, please fix this, because I can no longer use the mobile app.

**Comment by alextran1502** [comment] 2023-02-21 14:54
You will need `DB_HOSTNAME=immich_postgres` in your `.env`

I believe your server is not starting up correctly

**Comment by JVT038** [comment] 2023-02-21 15:23
It is. I can visit the web interface of the server and there are no error logs in docker about the database connection.

I don't connect Postgres with TCP, but with the unix socket.
That is why this is the command `postgres -c unix_socket_directories='/var/run/postgresql/,/sockets/'`, and why I have mounted the `/sockets` directory.

**Comment by alextran1502** [comment] 2023-02-21 15:28
Would reinstalling the app help?

**Comment by alextran1502** [comment] 2023-02-21 15:28
@zoodyy I saw that the app failed to initialize Isar, do you have any thoughts/suggestions?

**Comment by michelheusschen** [comment] 2023-02-21 18:08
Other users of Isar are having a similar problem https://github.com/isar/isar/issues/1080 with reports of crashes only happening in production builds. They've recently released a development version with a potential fix, but not confirmed.

**Comment by JVT038** [comment] 2023-02-22 19:31
I tested, and the apk files in the github releases do work.
So there's something wrong with the F-droid builds, because this error only occurs when installing the app from F-Droid.

**Comment by C9Glax** [comment] 2023-02-22 20:24
> I tested, and the apk files in the github releases do work. So there's something wrong with the F-droid builds, because this error only occurs when installing the app from F-Droid.

PlayStore as well.

When not starting from the appdrawer, not even the icon will show up.
Release 1.48.0. from Github works flawlessly.

**Comment by SNThrailkill** [comment] 2023-02-23 17:42
Also seeing this error with F-Droid version. Reinstalling the app does not help. The opening icon appears and hangs indefinitely.

**Comment by myanesp** [comment] 2023-02-24 10:07
Same here since a couple of days with the F-Droid version. Updated and reinstalled but doesn't work. Didn't tested Play Store, as I use a degoogled android. Donwloaded and installed v1.49.0 from GitHub Releases and it works

**Comment by l0l67** [comment] 2023-02-24 16:11
Same for me on a Pixel 6 and the F-Droid version

**Comment by alextran1502** [comment] 2023-02-25 14:31
@zoodyy this is very strange. Do you have any suggestions?

**Comment by zoodyy** [comment] 2023-02-25 15:18
It seems Isar 3.0.5 is not fully compatible with Flutter 3.7.
We could try to upgrade to Isar 3.0.6-dev.0 nd hope it fixes this incompatibility.

However, the root cause is probably related to the build (script) that works differently for our Github releases / F-Droid / Play store. Our GitHub releases work fine (as do all Play Store builds for me). Maybe F-Droid does something funky to the APK regarding the native code of Isar (shared library)

**Comment by manuke42** [comment] 2023-02-25 21:24
I found a new entry in the yml file of f-droid since version 1.47.0
[scandelete](https://gitlab.com/fdroid/fdroiddata/-/blob/4a08b257ccb4da1916565ea0df82a4f652e5d36b/metadata/app.alextran.immich.yml#L985)

It seems to delete binary files in the mobile/.pub-cache where the isar .so library is also located. In the f-droid build logs the library .so file is being deleted by the scandelete command. Maybe that is related, but just a guess:

`2023-02-24 19:34:38,844 INFO: Removing shared library at mobile/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.0.5/android/src/main/jniLibs/arm64-v8a/libisar.so`

**Comment by sbkg0002** [comment] 2023-02-26 09:08
Same issue with 1.49 from f-droid.

**Comment by zoodyy** [comment] 2023-02-26 11:41
> I found a new entry in the yml file of f-droid since version 1.47.0 [scandelete](https://gitlab.com/fdroid/fdroiddata/-/blob/4a08b257ccb4da1916565ea0df82a4f652e5d36b/metadata/app.alextran.immich.yml#L985)
> 
> It seems to delete binary files in the mobile/.pub-cache where the isar .so library is also located. In the f-droid build logs the library .so file is being deleted by the scandelete command. Maybe that is related, but just a guess:
> 
> `2023-02-24 19:34:38,844 INFO: Removing shared library at mobile/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.0.5/android/src/main/jniLibs/arm64-v8a/libisar.so`
> 
> [f-droid build log file](https://monitor.f-droid.org/builds/log/app.alextran.immich/72#site-footer)

@alextran1502 can you edit that file or somehow configure I to remove that scandelete entry? That should fix the Fdroid isar problem.

**Comment by palitu** [comment] 2023-02-28 02:58
I too have this issue.  I have just installed the APK directly from github and it loads as expected. 

 I am awaiting a full sync (which seems like a bit problem, as it looks like it is uploading everything again).

**Comment by alextran1502** [comment] 2023-02-28 04:08
> I too have this issue. I have just installed the APK directly from github and it loads as expected.
> 
> I am awaiting a full sync (which seems like a bit problem, as it looks like it is uploading everything again).

@palitu Uploading from different sources will create a different device ID (this is how device ID is generated and out of our control). I am hoping to fix the F-Droid issue soon

**Comment by adamaze** [comment] 2023-03-06 15:17
Any chance there is an ETA on a fix? I would rather not go back and forth between GitHub apk and fdroid, as I know there can be some weirdness...

**Comment by aadityadhruv** [comment] 2023-03-09 18:38
Updated to 1.50.1, the bug still persists.

**Comment by zoodyy** [comment] 2023-03-12 16:06
This is an F-Droid specific issue and needs to be resolved in the F-Droid build process. I've created a PR in F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12735

**Comment by palitu** [comment] 2023-03-27 04:47
Is there any updates to this?

**Comment by manuke42** [comment] 2023-03-28 12:47
I think I found a solution, but don't know whom to ask. I don't know by whom and how the F-Droid build script is managed. Maybe @fyfrey?

**Comment by fyfrey** [comment] 2023-03-28 12:53
The solution is to update the F-Droid build script to build `libisar.so` from source (now included as git submodule in the immich repo) and copy it to the correct location etc.
@manuke42 you can make a pull request to the F-Droid repository (I did so to disable all broken versions: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12736)

Some more information what needs to be done, can be found in the discussion of the following PR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12735

**Comment by manuke42** [comment] 2023-04-18 09:41
v1.53.0 is now available on f-droid with libisar included. For me it's working. You might try and report, so this issue can be closed.

**Comment by adamaze** [comment] 2023-04-18 14:25
I cant speak for OP, but I installed this version days ago and it didn't work. I just uninstalled, and then re-installed, and it is finally opening and started uploading the backlog of pictures from the past 2 months. thanks!

**Comment by manuke42** [comment] 2023-04-18 19:08
Yes there was a wrong version released some days ago, but the version released today should work without reinstalling. Maybe one needs to clear cache of f-droid if the old apk is still cached. I think this issue can be closed then.

**Closed** 2023-04-18 22:48 UTC
Labels: bug, need triage
