### ISSUE TITLE
excessive daily thumbnail generation job for external library since v1.98(.1)

### ISSUE THREAD

**Issue by traktuner** [immich-app/immich#7843] opened 2024-03-11 08:07 UTC
### The bug

I've noticed the following behaviour since v1.98(.1):

my library scan (refresh) is set to run every day at 7am.
And now, every day immich starts to process thousands of images/videos (thumbnail and encode jobs) with the same asset IDs although nothing changed. All assets belong to an external library which is an archive-style library where no assets get added/deleted. It's not only the thumbnail jobs but all relevant jobs in the chain which get triggered, like if it's adding thousands of new assets.
I have no errors, but success messages in the docker log

I don't know if this is related to 1.98 or 1.98.1 but it was definetely not the case for 1.97.x

Can this be related to a change made in the new version?

The external library has short off 100k assets.

### The OS that Immich Server is running on

Synology docker

### Version of Immich Server

1.98.1

### Version of Immich Mobile App

1.98.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
imagegenius AIO image (alpine)
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
see my description above
```

**Comment by PancakeZik** [comment] 2024-03-11 08:23
Same issue here, I have lots of photos so my NAS stays at 100% cpu for hours.

**Comment by antontanderup** [comment] 2024-03-11 08:37
I have the same issue and for some reason the new thumbnails get indexed as new photos and completely messes up the library. I'm going to pause my immich for now so my library does not get more messed up.

**Comment by messi0501** [comment] 2024-03-11 08:56
I can confirm this behaviour

**Comment by cslucian** [comment] 2024-03-11 08:57
I have this issue too!

**Comment by zlsl** [comment] 2024-03-11 09:56
same issue
seems generation of thumbnails on thumbnails and so on...
plus library scan, storage template migration, face recognition, video transcoding (in lib ~1500 videos, shows > 7000 videos in transcode)

**Comment by andyxpert** [comment] 2024-03-11 09:56
same here - it seems like Immich "forgot" the hashes for existing media and needs to re-scan everything... everywhere... all at once :)
Is there a simple process of making Immich "see" the newly added files (as most of use use the external libraries as backups) without rescanning everything all the time ?
I tried the new scan options, but they don't seem to do anything... 
Also I'm eagerly waiting for a stabilization of the experimental "auto-scan" feature...

**Comment by etnoy** [comment] 2024-03-11 11:16
> @etnoy do you think this relates to #7533 🤔?

I'll try to investigate tonight. But the changes should only have affected the file watcher, nothing else

**Comment by etnoy** [comment] 2024-03-11 11:17
@mertalev this can't be due to the optimizations to crawling, right?

**Comment by bo0tzz** [comment] 2024-03-11 11:30
Can someone who is seeing this issue set their log level to verbose and post a complete set of logs from around the time the issue happens?

**Comment by bo0tzz** [comment] 2024-03-11 11:35
And for the folks who are mentioning that "thumbnails get indexed as new photos" - please make sure that you do not have (parts of) `UPLOAD_LOCATION` somehow included in an external library - that's a common issue that would cause this sort of behaviour.

**Comment by etnoy** [comment] 2024-03-11 11:39
Yes, please paste the debug log here. Also let us know the upload location variable as well as the import paths for the troublesome library

**Comment by etnoy** [comment] 2024-03-11 11:53
Is anybody here using the automatic file watcher feature?

**Comment by traktuner** [comment] 2024-03-11 11:58
> Is anybody here using the automatic file watcher feature?

no!
also, upload location (volume/docker/immich/upload) is very different from the import path (/import/externallibrary1,...).

**Comment by etnoy** [comment] 2024-03-11 12:03
> > Is anybody here using the automatic file watcher feature?
> 
> no! also, upload location (volume/docker/immich/upload) is very different from the import path (/import/externallibrary1,...).

Can you enable debug logging and send the log to us?

**Comment by traktuner** [comment] 2024-03-11 12:14
> > > Is anybody here using the automatic file watcher feature?
> > 
> > 
> > no! also, upload location (volume/docker/immich/upload) is very different from the import path (/import/externallibrary1,...).
> 
> Can you enable debug logging and send the log to us?

Enabled verbose logging and re-run the library refresh.
Lots of "Marking previously-offline asset as online" which is odd because no exclusion pattern changed.

Here are parts of the log:
https://drive.proton.me/urls/N4PEV0Y56M#TbJwzVsSkGYU

**Comment by vmirage** [comment] 2024-03-11 12:39
Could this also be related to #7814. I notice I have that same problem and it starts marking my assets as offline

**Comment by mertalev** [comment] 2024-03-11 13:05
> @mertalev this can't be due to the optimizations to crawling, right?

It could be. Does everyone with this issue have a library with over 65k assets?

**Comment by etnoy** [comment] 2024-03-11 13:07
> > > > Is anybody here using the automatic file watcher feature?
> > > 
> > > 
> > > no! also, upload location (volume/docker/immich/upload) is very different from the import path (/import/externallibrary1,...).
> > 
> > 
> > Can you enable debug logging and send the log to us?
> 
> Enabled verbose logging and re-run the library refresh. Lots of "Marking previously-offline asset as online" which is odd because no exclusion pattern changed.
> 
> Here are parts of the log: https://drive.proton.me/urls/N4PEV0Y56M#TbJwzVsSkGYU

Thanks. Can you provide the log that happens when you initiate a library refresh? I want to see the count of online/offline assets that is printed then

**Comment by traktuner** [comment] 2024-03-11 13:18
@etnoy 
do you mean this part?
after that, it starts with lots of

`Asset already exists in database and on disk, will not import` ....

```
[Nest] 187  - 03/11/2024, 2:11:52 PM   DEBUG [LibraryService] Refreshing all external libraries: force=false

[Nest] 187  - 03/11/2024, 2:11:52 PM   DEBUG [LibraryService] Cleaning up any pending library deletions

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: 37d84ae2-1771-418d-a218-b45816a6acce

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: d48bcd35-bea5-4778-be8e-7ac4af19e0cf

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: 8fbcc34d-c989-41c8-8d30-8262fffafa64

[Nest] 187  - 03/11/2024, 2:11:52 PM   DEBUG [LibraryService] Found 0 asset(s) when crawling import paths 

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: 24cffb7b-3630-42e8-b880-38b1f26905e2

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: 8fb2c16d-75f6-4f86-a430-86b640f31bfa

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: da9adb64-e205-423c-8c34-3860bca8375a

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: 7f26da84-596a-4618-9556-a3ae5adff82a

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: 384cc9d2-32eb-4f6d-b337-97575df80bf0

[Nest] 187  - 03/11/2024, 2:11:52 PM VERBOSE [LibraryService] Refreshing library: 557c4c17-58ac-48e6-ae40-d650748be7fd

[Nest] 187  - 03/11/2024, 2:12:00 PM   DEBUG [LibraryService] Found 96675 asset(s) when crawling import paths /import//PATH-ANONYMIZED/library1/

[Nest] 187  - 03/11/2024, 2:12:01 PM   DEBUG [LibraryService] Found 3150 asset(s) when crawling import paths /import//PATH-ANONYMIZED/library2/

[Nest] 187  - 03/11/2024, 2:12:01 PM   DEBUG [LibraryService] Found 7587 asset(s) when crawling import paths /import//PATH-ANONYMIZED/library3/

[Nest] 187  - 03/11/2024, 2:12:04 PM   DEBUG [LibraryService] Found 4996 asset(s) when crawling import paths /import/PATH-ANONYMIZED/library4/

```

**Comment by PancakeZik** [comment] 2024-03-11 13:21
> > @mertalev this can't be due to the optimizations to crawling, right?
> 
> It could be. Does everyone with this issue have a library with over 65k assets?

I do, 100k here.

**Comment by cslucian** [comment] 2024-03-11 13:23
> > @mertalev this can't be due to the optimizations to crawling, right?
> 
> It could be. Does everyone with this issue have a library with over 65k assets?

I have about 69k

**Comment by traktuner** [comment] 2024-03-11 13:25
@mertalev so probably #7759 will fix this?

**Comment by zlsl** [comment] 2024-03-11 13:51
> > @mertalev this can't be due to the optimizations to crawling, right?
> 
> It could be. Does everyone with this issue have a library with over 65k assets?

> 300k

**Comment by mertalev** [comment] 2024-03-11 14:19
> @mertalev so probably #7759 will fix this?

I believe so. We're making a release soon so it'll be fixed with that.

**Comment by alextran1502** [comment] 2024-03-11 15:28
Hello everyone, please update to `1.98.2` and check if this issue is fixed

**Comment by zlsl** [comment] 2024-03-11 16:09
> Hello everyone, please update to `1.98.2` and check if this issue is fixed

updated to 1.98.2 - no rescans in logs

seems to be fixed

**Comment by cslucian** [comment] 2024-03-11 16:30
Updated to 1.98.2 - all the rescan activities are back to normal

**Comment by mertalev** [comment] 2024-03-11 16:42
Thanks for checking!

**Closed by mertalev** 2024-03-11 16:42 UTC

**Comment by andyxpert** [comment] 2024-03-11 19:18
Great work guys !!
Scan speed is back, no more endless running jobs.
Btw, tried experimental file system monitoring, errors because of small limit of monitored files on the OS, but since I have a low-RAM machine I won't increase it to 100k (as i have a lot of media files). Maybe when i upgrade the server...
