### ISSUE TITLE
Files wrongly reported as untracked

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#7436] opened 2024-02-26 19:50 UTC
### Discussed in https://github.com/immich-app/immich/discussions/7435

<div type='discussions-op-text'>

<sup>Originally posted by **stumpylog** February 26, 2024</sup>
After updating to 1.95.1, approximately half my images are reported as being "untracked" on the repair page.  However, I can locate the images in question from the main timeline and they are viewable and downloadable.

Taking a single image as an example:

The repair page lists `/usr/src/app/upload/library/me/2023/01-January/2023-01-14/PXL_20230114_222814182.jpg` as untracked.
The image page lists the file as `upload/library/me/2023/01-January/2023-01-14/PXL_20230114_222814182.jpg`
The image downloads as PXL_20230114_222814182.jpg and the SHA matches the stored image on the server.
</div>

**Comment by stumpylog** [comment] 2024-02-26 23:53
Perhaps related: #7333, however these images are not archived and never have been (I don't use that feature).

There are 6239 files being reported as untracked, though I've only checked a few at this point I assume the issue is the same with all of them.

**Comment by abangtor** [comment] 2024-02-28 03:03
Same Issue here.
Repair is reporting 36624 untracked files of a total of 40735 stored pictures...

**Comment by bshep** [comment] 2024-02-28 21:44
I have 64940 untracked files... the repair page is barely able to load and display the list, i'm not sure how to clean this up... they all seem to be thumbnails....

**Comment by alextran1502** [comment] 2024-02-28 21:45
@bshep Hi, just for some data point, how old is this Immich instance?

**Comment by stumpylog** [comment] 2024-02-28 21:58
My instance is roughly 2 years old at this point, those I recently re-created all the thumbnails (probably withing the last 6 months) to clear the issues list of umtracked files, which were all thumbnails then.

This time, some actual assets are reported as untracked

**Comment by bshep** [comment] 2024-03-01 12:28
Is there any way to get a list of the untracked files as json or plain file? If so I can grep the output and rm the untracked thumbs and clear out most if not all the untracked files.  As it is the 'repair' page can barely be loaded as it is very large.

**Comment by Allram** [comment] 2024-03-01 12:56
I had 16k untracked files (which can't be true as they can be found in Immich itself), then i reran all the Thumbs. Now i have 55k assets which are untracked of which ~40k is thumbs.

1.97.0

**Comment by adminmat** [comment] 2024-03-04 14:30
I'm showing 52K Untracks Files. Mostly thumbs and encoded videos. Hosting 33K photos. v1.97.0

**Comment by ejbastine** [comment] 2024-03-12 05:03
> Is there any way to get a list of the untracked files as json or plain file? If so I can grep the output and rm the untracked thumbs and clear out most if not all the untracked files. As it is the 'repair' page can barely be loaded as it is very large.

On the repair page, click "export" in the top right. Or you can export via api at http://your_immich_address/api/audit/file-report

I'm having a related issue where the values on this repair page aren't updating. None of the extra files report, nor the orphan files, actually exist in my filesystem. When I try to run the Remove Offline Files script (https://immich.app/docs/guides/remove-offline-files) it gives me a 400 error on the orphan files, which seems to be correct as I can't find any of the orphans in the immich postgres. I've removed the untracked files but the file report won't update, even after restarting all containers, refreshing, etc.

**Comment by Chuckame** [comment] 2024-03-14 22:44
Same

**Comment by TransRapid** [comment] 2024-05-12 08:18
Export o text,  rplace text that replaces the path to your directory, with "rm" in front of it. Save the file as a simple bash script, and then run that as your immich user.

**Comment by malavolti** [comment] 2024-05-16 22:49
I think to have the same issue.

![IMMICH-offline-paths](https://github.com/immich-app/immich/assets/3010502/62c71b42-810f-4e26-a664-5c5a6046ff31)

![IMMICH-untracked-files](https://github.com/immich-app/immich/assets/3010502/d19759d8-43c6-4f03-bc38-26536d0a7f01)

And I suspect that they are appeared from the usage of the External Libraries in my first instance.

Can you help me to understand how to clean this?

Thank you!

**Comment by Chuckame** [comment] 2024-05-17 06:52
Be REALLY attentive when removing files, I've loosen a lot of photos when a bug occurred with thumbnails and made a high amount of untracked files (700k+ for 35k assets).

**Comment by pfouto** [comment] 2024-05-31 16:01
Having a similar issue. Had around 19k untracked files (with 26k pictures), most of them thumbnails but also lots of pictures.

Used [immich-tools](https://github.com/clumsyCoder00/Immich-Tools) to move the untracked files away with the intent of re-uploading  them, and the result was both all of those files being now shown as offline paths _and_ 11k new files appearing as untracked.

I restored the files, which cleared all "offline paths" and confirmed that the files showing as untracked (at least the few ones I checked) are indeed viewable and downloadable from the timeline.

I also noticed that the number of untracked files is different whenever I open the repair page, varying from ~16k to ~22k.

If it helps, my instance is around 1 year old, and I have never used external libraries.

**Comment by wardwygaerts** [comment] 2024-09-02 15:57
I also have 12692 untracked files.
* 1 from my actual library (file is available on the location and displayed correctly in Immich)
* 1136 thumbs (some of them are no longer there...)
* 40 encoded video's (the ones I checked are there)
* 11515 in the upload folder, this folder should be empty actually, because I work with the storage template.
  * Most of them are video's, I think leftover of not completely uploaded files, which are retried afterwards.

**Comment by jrasm91** [comment] 2024-09-04 00:17
Duplicate of #12293

**Closed by jrasm91** 2024-09-04 00:17 UTC
