### ISSUE TITLE
Mouse browser navigation (back/forward) doesn't work when cursor is over image viewer

### ISSUE THREAD

**Issue by Snowknight26** [immich-app/immich#9272] opened 2024-05-05 19:57 UTC
### The bug

Viewing an image in the image viewer causes any mouse events that the browser is supposed to handle natively (back/forward bound to mouse4/5 for example) to not fire. This prevents mouse navigation when the cursor is over the image container.

Hovering the cursor over the Info panel, the previous/next image elements, etc., correctly allows navigation.

Only tested Chrome 124 and Firefox 125, and of the two, only Chrome is affected.

### The OS that Immich Server is running on

Windows 10 22H2 (19045.4291)

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Navigate to a photo in Chrome
2. Move the cursor over the image and/or the element that contains the image
3. Press the back navigation button a mouse
```

### Additional information

Not sure why Firefox isn't affected (maybe it doesn't fire pointerdown events by default) but I think the issue stems from the following:

When the `PhotoViewer` is rendered, `createZoomImageWheel` is called.

https://github.com/immich-app/immich/blob/cf79bc9ed74a8f6579b327d029a9c8cacea15469/web/src/lib/components/asset-viewer/photo-viewer.svelte#L37

This calls `@zoom-image/core`'s `_createZoomImageWheel`:
https://github.com/willnguyen1312/zoom-image/blob/5c8bcc09bd1eabb8909d01751bbfaca916f3bfec/packages/svelte/src/useZoomImageWheel.ts#L18

This creates a listener for the `pointerdown` event here:
https://github.com/willnguyen1312/zoom-image/blob/5c8bcc09bd1eabb8909d01751bbfaca916f3bfec/packages/core/src/createZoomImageWheel.ts#L412

This effectively calls `_handlePointerDown` here which prevents the default event behavior, which I assume is browser navigation.
https://github.com/willnguyen1312/zoom-image/blob/5c8bcc09bd1eabb8909d01751bbfaca916f3bfec/packages/core/src/createZoomImageWheel.ts#L347

**Comment by sierikov** [comment] 2024-05-09 17:40
I tried to take this issue and have found weird behavior. So I can partially reproduce this error. You can see the corresponding testing tables below.

Results for MacOS `14.4.1`

|Browser | Version | Works |
|:------ | :------ | :----: |
| Firefox | `125.0.3` | ✅  |
| Chrome | `124.0.6367.119` | ✅ |

So in the MacOS, I can't reproduce the bug in general. 

Results for Windows 11 `23H2 (22631.3447)`

|Browser | Version | Works | 
|:------ | :------ | :----: |
| Firefox | `125.0.2` | ✅  |
| Chrome | `124.0.6367.156` | ❌  |
| Edge | `124.0.2478.80` | ❌ |

Looks like it is only a Windows problem. I will update this comment with the Linux result a little bit later.

**Comment by Snowknight26** [comment] 2024-05-09 18:25
I tested on Ubuntu 24 and saw the same issue in Chrome.

**Comment by sierikov** [comment] 2024-05-09 19:02
I have updated the results. So indeed something in the Chromium-based `event.preventDefault` is wrong. I'll try to look into this deeper.

**Comment by danieldietzler** [comment] 2024-09-18 21:44
Closing this as it seems to be a browser issue

**Closed by danieldietzler** 2024-09-18 21:44 UTC
Labels: good first issue, 🖥️web
