### ISSUE TITLE
[BUG] Cannot use the app in iOS and android without storage permission

### ISSUE THREAD

**Issue by newness0** [immich-app/immich#1927] opened 2023-03-03 13:23 UTC
### The bug

I prefer to use immich as a front end for my photo collections and do not want it to scan my phone storage. However, without storage permission to my phone, app is not allowing me to login and the only other option is to logout.

please allow the user to continue using the application without storage permission

### The OS that Immich Server is running on

Debian

### Version of Immich Server

V1.49.0

### Version of Immich Mobile App

V15.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Na
```

### Your .env content

```Shell
Na
```

### Reproduction steps

```bash
1. Install and open app from store
2. Login to app and do not give storage permission 
3. App wouldn’t allow to login
```

**Comment by martyfuhry** [comment] 2023-03-03 13:30
I'll close this as a duplicate of #1905. We'd like to support this usage directly in an upcoming release. In the meantime, there's a workaround in the other issue you could try. Sorry for the inconvenience; I had no idea people liked Immich enough to only use it as an image viewing app!

**Closed by martyfuhry** 2023-03-03 13:30 UTC
Labels: bug, need triage
