### ISSUE TITLE
Some videos are playing upside down (180 degrees rotated) 

### ISSUE THREAD

**Issue by mike12806** [immich-app/immich#13519] opened 2024-10-16 20:54 UTC
### The bug

Some videos are playing upside down (180 degrees rotated) 

Video was taken on an iphone 15 pro max (1080 x 1920 resolution; .mov file type)

### The OS that Immich Server is running on

Kubernetes / Docker

### Version of Immich Server

V1.118.2

### Version of Immich Mobile App

V1.118.2

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Helm Chart
```

### Your .env content

```Shell
See above; I'm using helm
```

### Reproduction steps

Unclear - only happening for some videos, not sure why it's selective

### Relevant log output

```shell
None
```

**Comment by bo0tzz** [comment] 2024-10-17 09:51
Seems like a dupe of #2130

**Comment by mike12806** [comment] 2024-10-17 10:00
> Seems like a dupe of #2130

That issue is on mobile app? This only occurs on web for me, not mobile.

**Closed** 2024-10-20 11:15 UTC

**Comment by alextran1502** [comment] 2024-10-28 19:17
@mike12806 you will need to re-transcode the problem videos. Let me know if it helps

**Comment by Tumist76** [comment] 2024-11-18 15:04
> @mike12806 you will need to re-transcode the problem videos. Let me know if it helps

If I'm not using transcoding at all, what can be the problem here? I'm still seeing all my videos from Pixel 7 upside-down on Web on v1.120.2.
