### ISSUE TITLE
[BUG] Negative remaining photos

### ISSUE THREAD

**Issue by EnochPrime** [immich-app/immich#1265] opened 2023-01-07 02:41 UTC
**Describe the bug**
Remaining files to backup can be negative.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
Unknown at the moment.

**Expected behavior**
Remainder should never be less than zero.

**Screenshots**
![Screenshot_2023-01-06-21-36-49-79_d8aea95ef633eb6b7eb1cae13c34b40e](https://user-images.githubusercontent.com/1175190/211127842-e5aef4dd-1e86-471f-94ff-9cb67789b8e6.jpg)

**System**
- Phone OS [iOS, Android]: `Android 13`
- Server Version: `1.40.0`
- Mobile App Version: `1.40.0 build 63`

**Additional context**

**Comment by alextran1502** [comment] 2023-01-07 02:56
Duplicate of #968

**Closed by alextran1502** 2023-01-07 02:56 UTC
Labels: bug, need triage
