### ISSUE TITLE
[BUG] Some faces not shown in face overview

### ISSUE THREAD

**Issue by Inrego** [immich-app/immich#3450] opened 2023-07-28 11:20 UTC
### The bug

When clicking `View All` under peopler in `Explore`, it doesn't show all faces.

By coincidence, I noticed my dead grandfather is not in the list. He's only in 2 photos if that has anything to say.
I went and manually found the photos in my library, and he was indeed correctly tagged on both photos.

Also, when searching for his name in the search bar, I get some results, but all of them irrelevant (not photos of him).

### The OS that Immich Server is running on

Docker on Ubuntu

### Version of Immich Server

1.70.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
Not sure how to reproduce
```

**Comment by bo0tzz** [comment] 2023-07-28 11:22
Duplicate of #3390

**Closed by bo0tzz** 2023-07-28 11:22 UTC
Labels: bug, need triage
