### ISSUE TITLE
[Feature]: Using a local connection on known Wi-Fi connections

### ISSUE THREAD

**Issue by RealFascinated** [immich-app/immich#1083] opened 2022-12-10 06:16 UTC
### Feature detail

This feature would allow the app to connect to the immich instance using a different IP/domain when connecting to the instance locally to bypass slow upload speed/rate limits from the domain provider (eg: Cloudflare).

### Platform

Mobile App

**Comment by bo0tzz** [comment] 2022-12-10 09:36
Duplicate of #308

**Closed by bo0tzz** 2022-12-10 09:36 UTC
Labels: feature, need triage

**Comment by jpmiller25** [comment] 2022-12-12 15:41
You're not alone. If it helps:

https://github.com/immich-app/immich/issues/1097#issuecomment-1346700476

**Comment by alextran1502** [comment] 2022-12-12 21:16
@jpmiller25 Thank you for the reference. I will put it in the documentation

**Comment by RealFascinated** [comment] 2022-12-13 08:27
Thanks. I did not even think of doing that lol
