### ISSUE TITLE
[BUG] Immich iOS app cannot upload, stuck

### ISSUE THREAD

**Issue by handonam** [immich-app/immich#5445] opened 2023-12-02 10:16 UTC
### The bug

I took a bit of a break since around November 5th through November 17th, in which I didn't have immich running. So, I started immich again on Nov 17th, updating to 1.87.0. I forgot what I was on when it was November 5th and prior.  

But, fact is, iOS hasn't been uploading images since 1.87.0.  And checking the app, the server storage says "0 of 0 used"
![IMG_5214](https://github.com/immich-app/immich/assets/455463/d25b7e00-d540-4845-b91a-c466476253b4)

In the backup screen, none of the numbers in "Backup" and "Remainder" have moved:
![IMG_5215](https://github.com/immich-app/immich/assets/455463/208fe958-3065-400d-bf7c-d0bb05b3b818)

Most notably, this "Uploading file info" section does not move at all. Even if you click "Cancel" followed by "Start Backup"
![IMG_5216](https://github.com/immich-app/immich/assets/455463/60085f71-4616-451e-9e53-49ae2f4960ce)

Singularly uploading images do not change anything as well.

Attempted to check iOS app for any logs (including Troubleshooting mode on with finest log settings), but nothing came up. Logs are fairly blind to this issue.

### The OS that Immich Server is running on

docker-compose via Unraid

### Version of Immich Server

1.89.0 and 1.88.2

### Version of Immich Mobile App

1.89.0 build.129

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  portainer_agent:
    ports:
      - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: 'portainer/agent:2.19.1'
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml # this is in /boot/config/plugins/compose.manager/projects/immich/hwaccel.yml
      service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    ports:
      - 3003:3003
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

      
volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/Documents/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<REDACTED>
DB_PASSWORD=<REDACTED>


# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
See screenshots.
```

**Comment by steve5355** [comment] 2023-12-02 21:04
I am having the same problem.  Every time i check the status, it shows the same number of pending uploads.  I manually start and it shows all the images uploading.... but the counter is not counting down to zero, it stuck at the same number.  I then check my SMB share for the uploads folder and i dont see any new files actually uploading there.   I tried background upload, manual upload, its stuck pretending to upload but not actually doing anything it seems.  

I can do further testing and troubleshooting if needed.

**Comment by steve5355** [comment] 2023-12-05 17:00
I can't use the app until there is a fix. I'm not sure its worth it to reinstall, I will just wait for the next release.

**Comment by alextran1502** [comment] 2023-12-05 17:07
@steve5355 if you are using iCloud with optimized storage turned on, this is expected behavior because the app hasn't handled this use case properly yet

**Comment by steve5355** [comment] 2023-12-05 19:04
@alextran1502 Yes, this is the issue... you're right, I'm not sure how i missed this.  It wasn't obvious to me and now i feel dumb.  

For anyone else using iCloud: The iphone puts the image in the cloud and removes the original from the device, so immich can't grab the source file, even though you can see the thumbnails and previews on device.   I have been using the manually selected photos option for testing, not ready to "allow all" to my camera roll, so few days ago, i selected photos from a few months ago on my camera roll and those must not be on my device.  

So what are folks doing to work around this issue for now (until there is solution)?

**Comment by alextran1502** [comment] 2023-12-05 20:44
@steve5355 I am experimenting with a solution for this. I will try to include it in the next release #5508

**Comment by KertzmannPerry** [comment] 2023-12-06 00:38
The same issue has occurred with Android version 1.89.0, unable to synchronize, and the remaining backup quantity has not changed

**Comment by joestump** [comment] 2023-12-07 14:28
I don't know if this is entirely related, but I'm running into a situation where Immich will not fully complete the backup and no longer allows me to even select albums for backup. I'm on the latest version, fresh install (1.89). 

I've ran into multiple issues:

* Syncs will just stop. At first I would hit Cancel and then Start Backup to get it to start again. Eventually this stopped working and I had to kill the app and restart it. This too has ended up failing as a workaround.
* Very large video files are not completing uploads. I've had videos as small as 1GB fail, though the common failure size seems to be around 4GB. I'm on an iPhone 16 Pro Max (8GB of RAM) uploading to Intel NUCs (16GB of RAM) so I'm unsure why these continue to fail. 
* I'm now at the point where Immich logs shows it sees local albums, but the sync UI shows 0 albums on device. This has persisted despite me logging out/back in *and* deleting/reinstalling the app. Immich simply fails to see any local albums.

I'm now left in a state where I can't even kick off a manual backup nor can I turn on background syncing. Immich managed to upload about 29,000 of my 32,000 photos before becoming unusable. 

Here are the workarounds I've attempted – all have failed: 

* Log out and back in.
* Delete app and reinstall.
* Remove videos it was struggling with from Photos on the desktop.
* Clip raw b-roll videos down to be smaller.

Logs show nothing on these video failures. Progress bar gets to 70-80%, then "completes", only for the next backup to start over again at the large failed video file. Nothing in the server logs either. 

Ironically, the logs on the device *do* show Immich finding my local albums. The UI just doesn't reflect that fact. 

A few things that would really help those of us with large libraries/sync issues would be:

1. Keep track of the number of times Immich has attempted to upload a file. If you've tried to upload a file 5 times and it's still not backed up, mark it as failed.
2. Show file size in the upload/sync UI. 
3. Add a "skip" button so problematic files can be manually skipped over.
4. Either change the algorithm to prioritize images/smaller files or add a setting that allows the user to do so.

See attached screen shot – logs show it found 90 local albums and then 11 seconds later "Not found albums": 

![Screenshot 2023-12-07 at 06 09 39](https://github.com/immich-app/immich/assets/37667/61816b33-59ff-4fd9-9128-95275f14ffb6)

**Comment by alextran1502** [comment] 2023-12-07 14:39
@joestump just for information, are you using iCloud, with Optimized Storage turned on and Share Albums feature of iCloud?

**Comment by joestump** [comment] 2023-12-07 16:11
Turning the logs up you can see the following timeline:

* Immich finds 90 albums.
* Immich receives a "ping" that is `null`.
* Immich reports finding no albums or assets to back up.

![Screenshot 2023-12-07 at 08 09 59](https://github.com/immich-app/immich/assets/37667/a563cb7d-8104-471e-9e5b-8ce46284df43)

**Comment by handonam** [comment] 2023-12-12 04:08
> @steve5355 I am experimenting with a solution for this. I will try to include it in the next release #5508



Checking in, after more updates (including this one above), still not able to upload.  I don't use icloud for photos fyi

**Comment by alextran1502** [comment] 2023-12-12 05:51
@handonam Do you use reverse proxy to access your instance on the mobile app? Does the proxy set the body size allowance large enough for the file to be accepted?

**Comment by steve5355** [comment] 2023-12-14 17:07
update: 

1. turning off icloud storage fixed for me, luckily i had enough room on my phone to store all of the photos on device. so that fixes that issue. 

2. my next issue was proxy was using default values which blocked large files from transferring. updated proxy config and that fixed it.

3. now the only issue with "files not uploading" from my iphone camera roll, is that, no matter what options i select in background refresh, the phone will stop / stall uploading once the phone screen turns off or i switch to another app.   


Therefore, there must still be an issue on the background uploading, logic. the only way the images are uploaded from my iphone is if i keep the screen on by touching it every few minutes.   This also kills the battery while uploading, the phone gets hot, but it is uploading very fast on my local wifi.  I believe this is a known issue so I can wait for a fix in a future release. At least its working for me after doing items 1 and 2 above.

**Comment by alextran1502** [comment] 2023-12-14 17:19
@steve5355 we solved a few issues in the next release. Let's see how it goes

**Comment by handonam** [comment] 2023-12-14 21:01
> @handonam Do you use reverse proxy to access your instance on the mobile app? Does the proxy set the body size allowance large enough for the file to be accepted?

I don’t have Reverse Proxy set up. should I be?

**Comment by notflip** [comment] 2023-12-15 01:00
> @steve5355 we solved a few issues in the next release. Let's see how it goes

What issues did you solve? Just so I know which steps to take, will disabling iCloud still be required for the uploads to work? Thanks!

**Comment by alextran1502** [comment] 2023-12-15 05:33
@notflip We solved the issue of uploading files from iCloud that causes the process to be hung. And potentially solving an issue of the album selection for backup doesn't load the albums

**Comment by PitchAbyss** [comment] 2023-12-16 20:44
> @notflip We solved the issue of uploading files from iCloud that causes the process to be hung. And potentially solving an issue of the album selection for backup doesn't load the albums

hi sir on android device when screen gets locked uploads pause is there any way to fix this too

**Comment by alextran1502** [comment] 2023-12-16 20:48
@PitchAbyss you can enable background backup, backup process will then run periodically

**Comment by PitchAbyss** [comment] 2023-12-16 20:51
> @PitchAbyss you can enable background backup, backup process will then run periodically 

Sir when i activate it has error

![Screenshot_20231217_022105.jpg](https://github.com/immich-app/immich/assets/13099434/9e2d1edc-dcf7-4ea5-b99a-b1220079d89a)

![Screenshot_20231217_022119.jpg](https://github.com/immich-app/immich/assets/13099434/87f78c38-8f6a-44d0-892a-67c8011bbec6)

**Comment by alextran1502** [comment] 2023-12-16 20:55
@PitchAbyss 
![image](https://github.com/immich-app/immich/assets/27055614/51fcab90-3af4-4748-aac1-2b12e2e56109)

**Comment by PitchAbyss** [comment] 2023-12-16 20:57
> @PitchAbyss ![image](https://private-user-images.githubusercontent.com/27055614/291015164-51fcab90-3af4-4748-aac1-2b12e2e56109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NjA0NzYsIm5iZiI6MTcwMjc2MDE3NiwicGF0aCI6Ii8yNzA1NTYxNC8yOTEwMTUxNjQtNTFmY2FiOTAtM2FmNC00NzQ4LWFhYzEtMmIxMmUyZTU2MTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDIwNTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NjA5YTVmMDE2OTBjZjczYmIyZDFjYzkxNTk1MDAwYWI2OWY3NzY5YTliZDEzZGIyZjJkZWY0MDZkOGY4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6wHMOlCZKlayt0lmjPwYgB6sivgo7jeaigvQyCO-Bmo)

my appologise i just check it working, thankyou sir , i hope there could be a folder view in app in future

**Comment by PitchAbyss** [comment] 2023-12-16 21:02
> @PitchAbyss 
> ![image](https://github.com/immich-app/immich/assets/27055614/51fcab90-3af4-4748-aac1-2b12e2e56109)
> 

I just set albums to upload then it got stuck at 1 video i exit the app and now it shows empty

![Screenshot_20231217_023112.jpg](https://github.com/immich-app/immich/assets/13099434/543a319c-8661-453f-bbbe-e4ce51f3f293)

**Comment by handonam** [comment] 2023-12-24 08:05
on 1.91.4, still reporting with this being stuck.

**Comment by bloodyburger** [comment] 2024-01-02 09:04
same here, proxy body size set enough to handle big uploads, but my uploads keeps restarting, using immich behind SWAG.

**Comment by markwien** [comment] 2024-01-13 06:01
Same here bigger videos don't upload (longer than 2 minutes)

Service is behind a reverse proxy.

Log file:

Failed to get file for asset FCEBA96B-2B92-4E11-A9F4-60DC70CD34AC/L0/001, skipping

All iCloud foto data is downloaded to the iPhone.

**Comment by alextran1502** [comment] 2024-01-13 06:53
@markwien Your reverse proxy probably doesn't set up to accept large files. Try local IP to confirm the issue

**Comment by markwien** [comment] 2024-01-13 07:40
> @markwien Your reverse proxy probably doesn't set up to accept large files. Try local IP to confirm the issue

omg u right I was thinking i did - I changed client max body size to 16G now it works. 

Thank you !

**Comment by bennesp** [comment] 2024-01-27 20:18
I have:

- iCloud optimization turned off
- Immich deployed behind traefik (which does not have a max body size by default)
- 2000 (over a total of 2700) photos and videos already backed up
- the backup stuck

I managed to find the incriminated video: a 2m34s video in a **shared** album. I am **not** the owner of the shared album. File size is reported to be "Zero kB" by Photo on MacOS (with cmd+i) while I can't find a way of showing file size on iOS.

**Comment by handonam** [comment] 2024-03-08 06:26
@alextran1502 

So my dum self realized my storage was full. I had to check the docker logs to find out that it was the case.  I could have sworn i tried to look at docker before, and never seeing this error.  But digging into the logs recently, it was very clear: `insufficient space`.

the mobile app doesn't really describe that as a failure to upload, it just hangs.  Not quite ideal (as i spent months churning on why).  

**In my case, I wouldn't mind if we close this issue.**  But, I would say: a more verbose failure message for mobile app (either in the UI, or even the logs) would be valuable for triaging faster, and to separate some of these issues people are having into different threads.

**Closed** 2024-03-19 03:51 UTC
Labels: bug, 📱mobile

**Comment by bennesp** [comment] 2024-03-19 09:15
Has these somehow been solved? I am still having this problem unfortunately

**Comment by notflip** [comment] 2024-03-19 09:21
Same for me, issue is still there on Ios

**Comment by handonam** [comment] 2024-03-20 17:16
> Has this somehow been solved? I am still having this problem unfortunately

i would suggest to open a new issue if it's not related to the free storage issue i had. that way, the devs can triage it better

**Comment by napisani** [comment] 2024-04-06 13:50
> @handonam Do you use reverse proxy to access your instance on the mobile app? Does the proxy set the body size allowance large enough for the file to be accepted?

this saved me, thank you 

for anyone using nginx-ingress on their k8s cluster, this annotation fixed the issue for me
```
        'nginx.ingress.kubernetes.io/proxy-body-size': '999m',

```

**Comment by Whamp** [comment] 2024-06-05 16:36
I'm having the same issue but not using a reverse proxy, instead i'm using cloudflare tunnel. Are there similar file size constraints that people are aware of there? I never can seem to get a reverse proxy working on my unraid config.

**Comment by alextran1502** [comment] 2024-06-05 16:55
@Whamp yes CF limit to 100MB file, we don't have chunk upload implemented yet so the request is rejected by CF

**Comment by onstring** [comment] 2024-06-09 13:51
I got the same issue, which seems due to the unsupport file type. And the upload stuck with repeated logs as following:

```
[Nest] 8  - 06/09/2024, 1:39:52 PM   ERROR [ImmichServer] [AssetService] Unsupported file type 29583.pic
[Nest] 8  - 06/09/2024, 1:40:14 PM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: qVBCnJEgmxCmxGOyAAAz
[Nest] 8  - 06/09/2024, 1:40:44 PM     LOG [ImmichServer] [EventRepository] Websocket Connect:    1TOKP-FZM7SCaeXnAAA1
[Nest] 8  - 06/09/2024, 1:40:46 PM   ERROR [ImmichServer] [AssetService] Unsupported file type 29554.pic
[Nest] 8  - 06/09/2024, 1:40:59 PM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: 1TOKP-FZM7SCaeXnAAA1
[Nest] 8  - 06/09/2024, 1:41:22 PM     LOG [ImmichServer] [EventRepository] Websocket Connect:    3PlQvgY1IMQkUFmvAAA3
```

The upload only started again after I deleted the files immich complainted.
Maybe it is needed some improvement on this?

**Comment by telpalbrox** [comment] 2024-07-30 15:38
This happened to me as well. In my case it seems that the error was that I have photos synced via macOS and they do not have a name.

There were the logs I was getting in the client:
```
flutter: Error(400) uploading BA9AC325-DC3D-480D-98C0-874FBBC58F7E/L0/001 |  | Created on 2021-12-31 17:28:00.000 | Bad Request
flutter: Error(400) uploading 127E1410-7322-436C-AF13-79B9B148D62D/L0/001 |  | Created on 2021-12-31 16:25:28.000 | Bad Request
flutter: Error(400) uploading livePhoto for assetId | .000000_o_(null) | Bad Request
```
And in the server:
```
[Nest] 30  - 07/30/2024, 3:33:36 PM   ERROR [Api:AssetMediaService] Unsupported file type .000000_o_(null)
[Nest] 30  - 07/30/2024, 3:33:57 PM   ERROR [Api:AssetMediaService~wn3qnwjt] Unsupported file type .000000_o_(null)
[Nest] 30  - 07/30/2024, 3:34:11 PM   ERROR [Api:AssetMediaService] Unsupported file type .000000_o_(null)
[Nest] 30  - 07/30/2024, 3:34:19 PM   ERROR [Api:AssetMediaService] Unsupported file type .000000_o_(null)
```

I think the root cause is that the client is doing an invalid request to the server and it is not recovering correctly.
I hacked my way around the code to get it to work. Here you can see how I managed to fix it https://github.com/telpalbrox/immich/commit/7de365988905a7a2689c3e78aead572abe50dc74 .

This is just a hack, and I do not think it can be merged. Probably a more elegant solution has to be found.
If I can be of any help to fix it let me know!

**Comment by doublebubblemethod** [comment] 2025-11-29 17:25
i has a similar  error: "Bad state: cannot use ref after the widget was disabled" when i freshly set up my docker lab. So what i have done:
1. reverse proxy config: "client_max_body_size 0;"
2. reverse proxy config: enabled Websockets support (i ignored that when i accessed my immich domain (like http://immich.examplehomelab.domain) i had "Server offline" ) 
3. immich mobile app: enabled media upload when on cellular network 

so with these 3 steps, upload started working
