### ISSUE TITLE
[Feature]: Different storage location for thumbs

### ISSUE THREAD

**Issue by Peda1996** [immich-app/immich#1411] opened 2023-01-24 18:30 UTC
### Feature detail

As far as I can tell, thumbnails are currently created for all images, which are then used for showing the image in the app and in the browser.

Would it be possible to create a THUMB_LOCATION just like the UPLOAD_LOCATION where all thumbnails are stored?

This would have the advantage that you can store thumbnails on the SSD, for example, and you can access the images while the Hdd remains spun down.

### Platform

Server

**Comment by bo0tzz** [comment] 2023-01-24 18:33
Duplicate of #418

**Closed by bo0tzz** 2023-01-24 18:33 UTC
Labels: feature, need triage
