### ISSUE TITLE
[ENHANCEMENT] Show placeholder for unloaded thumbnail on Firefox instead of image id

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#646] opened 2022-09-08 20:50 UTC
**Describe the bug**
When I scroll really fast through hundreds of images, they don't load instantly and instead show a white panel with the item ID. Look at screenshot below for an example.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to the timeline.
2. Scroll through the images.
4. Briefly see error.

**Expected behavior**
I expected the images to briefly be a white / blank panel and to then load the image. Instead, it shows a blank panel with an item ID, like the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/47184046/189216668-69928643-e3f2-4e8a-b9a8-9333d46908f9.png)
So if you look closely in this image, you can see the gutter between the panels, and it shows the item IDs. Is it possible to have a temporary icon / image that shows instead of the ID? 

**System**
- Phone OS [iOS, Android]: `Android 11`
- Server Version: `1.27.0`
- Mobile App Version: `1.27.0`

**Additional context**
I'm using Firefox 104.0.2 on Windows 10

**Comment by bo0tzz** [comment] 2022-11-02 10:48
Duplicate of #564

**Closed by bo0tzz** 2022-11-02 10:48 UTC
Labels: enhancement
