### ISSUE TITLE
[BUG] Minutes and seconds are use as timezone offset

### ISSUE THREAD

**Issue by szerencl** [immich-app/immich#4290] opened 2023-09-30 21:23 UTC
### The bug

When uploading some photos either through CLI, website, or mobile app the time zone shows up as UTC+MM:SS.
Does not happen with all images, but I could not find any pattern that would differentiate between them.
E.g.:
![kép](https://github.com/immich-app/immich/assets/57007996/0d9d8444-c993-4e94-8d3d-768c9881b085)
Metadata of image:
```
---- ExifTool ----
ExifTool Version Number         : 12.64
Warning                         : [minor] Overlapping MakerNoteSamsung2 values
---- File ----
File Name                       : 09233507.JPG
Directory                       : .
File Size                       : 5.5 MB
File Modification Date/Time     : 2023:09:23 18:10:44+02:00
File Access Date/Time           : 2023:09:30 23:13:06+02:00
File Creation Date/Time         : 2023:09:30 17:57:28+02:00
File Permissions                : -rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Image Width                     : 4592
Image Height                    : 3056
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:2 (2 1)
---- EXIF ----
Make                            : SAMSUNG
Camera Model Name               : NX100
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : 01.02
Modify Date                     : 2023:09:23 18:10:41
Y Cb Cr Positioning             : Co-sited
Exposure Time                   : 1/25
F Number                        : 3.5
Exposure Program                : Program AE
ISO                             : 1600
Exif Version                    : 0221
Date/Time Original              : 2023:09:23 18:10:41
Create Date                     : 2023:09:23 18:10:41
Components Configuration        : Y, Cb, Cr, -
Exposure Compensation           : 0
Max Aperture Value              : 3.5
Metering Mode                   : Multi-segment
Light Source                    : Other
Flash                           : Off, Did not fire
Focal Length                    : 20.0 mm
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 4592
Exif Image Height               : 3056
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Focal Plane X Resolution        : 6652
Focal Plane Y Resolution        : 6652
Focal Plane Resolution Unit     : inches
Sensing Method                  : One-chip color area
File Source                     : Digital Camera
Scene Type                      : Directly photographed
Exposure Mode                   : Auto
White Balance                   : Auto
Digital Zoom Ratio              : 1
Focal Length In 35mm Format     : 30 mm
Scene Capture Type              : Standard
Contrast                        : Normal
Saturation                      : Normal
Sharpness                       : Normal
Subject Distance Range          : Close
Compression                     : JPEG (old-style)
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Thumbnail Offset                : 34000
Thumbnail Length                : 10732
Thumbnail Image                 : (Binary data 10732 bytes, use -b option to extract)
---- MakerNotes ----
Maker Note Version              : 0100
Device Type                     : High-end NX Camera
Samsung Model ID                : NX100
Smart Album Color               : n/a
Picture Wizard Mode             : Standard
Picture Wizard Color            : 0
Picture Wizard Saturation       : 0
Picture Wizard Sharpness        : 0
Picture Wizard Contrast         : 0
Local Location Name             : 
Location Name                   : 
Camera Temperature              : 24.2 C
Raw Data CFA Pattern            : Roll
Face Detect                     : On
---- MPF ----
MPF Version                     : 0100
Number Of Images                : 2
MP Image Flags                  : Dependent parent image
MP Image Format                 : JPEG
MP Image Type                   : Baseline MP Primary Image
MP Image Length                 : 5444953
MP Image Start                  : 0
Dependent Image 1 Entry Number  : 2
Dependent Image 2 Entry Number  : 0
MP Image Flags                  : Dependent child image
MP Image Format                 : JPEG
MP Image Type                   : Large Thumbnail (VGA equivalent)
MP Image Length                 : 63793
MP Image Start                  : 5444953
Dependent Image 1 Entry Number  : 0
Dependent Image 2 Entry Number  : 0
Preview Image                   : (Binary data 63793 bytes, use -b option to extract)
---- Composite ----
Aperture                        : 3.5
Image Size                      : 4592x3056
Megapixels                      : 14.0
Shutter Speed                   : 1/25
Light Value                     : 4.3
Scale Factor To 35 mm Equivalent: 1.5
Circle Of Confusion             : 0.020 mm
Field Of View                   : 61.9 deg
Focal Length                    : 20.0 mm (35 mm equivalent: 30.0 mm)
Hyperfocal Distance             : 5.71 m
```
![09233507](https://github.com/immich-app/immich/assets/57007996/c4bc67d6-b41e-4f55-9a3d-83074fac2534)

### The OS that Immich Server is running on

DSM 7.1.1

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Same as https://github.com/immich-app/immich/releases/download/v1.79.1/docker-compose.yml
```

### Your .env content

```Shell
(standard)
```

### Reproduction steps

```bash
1. Upload attached image
2. Reload page
3. Check image information
```

**Comment by jrasm91** [comment] 2023-09-30 21:33
Duplicate of #4166

**Closed by jrasm91** 2023-09-30 21:33 UTC
Labels: bug, need triage
