### ISSUE TITLE
[Feature]: Allow configuring internal DNS for services to allow for non-Docker-compose deployments

### ISSUE THREAD

**Issue by rounakdatta** [immich-app/immich#805] opened 2022-10-10 18:04 UTC
### Feature detail

Hello, I'm trying to deploy Immich via Hashicorp Nomad. While the docker-compose examples were quite helpful, I realized I wouldn't be able to get up running 100% due to the fact that the DNS names for the intra-service communication is hardcoded to the service-name-based DNS (like it happens in Docker).

- Nomad of course has integration with Consul, but that too poses various challenges like `-` in DNS names are converted into `_`. Hence setting up Consul also probably wouldn't help me much.
- I think the best way out would be to expose an environment variable that allows for exposing specific endpoints (the protection of the endpoints can be left out to the administrator?) to 0.0.0.0 / localhost. It would be lovely if the ports were also configurable.
- The first blocker I faced was while setting up the proxy (https://github.com/immich-app/immich/blob/main/nginx/nginx.conf#L65 essentially is invalid for my Nomad cluster).

I'm very excited to be migrating from Photoprism to Immich! Thanks for all the hard work behind this.

### Platform

Server

**Comment by Cellivar** [comment] 2022-10-11 07:18
Huge +1 to this, I'd love to deploy this into my Nomad cluster (across multiple raspis and x64 machines) to give it a whirl and this is a hard brick wall to adopting.

**Comment by PixelJonas** [comment] 2022-10-12 06:27
The effort to make every DNS Name configurable is tracked at https://github.com/immich-app/immich/pull/657
Feel free to contribute to that PR. We are still facing some issues regarding the NodeJS Clients and implementing a proper way to pass the configuration of different Hostnames between clients without having "normal" users to configure everything

**Comment by bo0tzz** [comment] 2022-10-17 18:20
Closing this as a duplicate of #647

**Closed by bo0tzz** 2022-10-17 18:20 UTC
Labels: feature, need triage
