### ISSUE TITLE
[Feature]: Bulk export of photo archive

### ISSUE THREAD

**Issue by RaffaeleCu** [immich-app/immich#751] opened 2022-09-25 14:32 UTC
### Feature detail

I find the way asset management on the server has been implemented annoying.
At the moment, in fact, it is not really feasible to view photos, except from the web interface, because they are saved without exif data and without an understandable name.
It would be nice to be able to save the photos divided into folders sorted by months or days or to develop a "bulk download" function that creates a sorted archive when requested (Apple does a similar thing with the Photos app on MacOS).
<img src="https://support.content.office.net/en-us/media/fe06facb-9abd-0ca9-6a60-20a2934532c8.png">

### Platform

Server

**Comment by bo0tzz** [comment] 2022-09-25 14:36
Duplicate of #34 and #403/#543

**Closed by bo0tzz** 2022-09-25 14:36 UTC
Labels: feature, need triage
