### ISSUE TITLE
[BUG] Raspberry Pi Server crashes when is uploading

### ISSUE THREAD

**Issue by srlamin19** [immich-app/immich#503] opened 2022-08-20 14:18 UTC
Uploading photos from App to my server doesn't seem to work. The uploading starts and after this, the server crash, only few photos were uploaded. Actually I have like 4 thousands photos from phone to upload. Please let me know how to extract a better log (logfile if exists).

To Reproduce
Go to app.
Select a Backup;
Wait for automatic upload

Expected behavior:
Image should be uploaded correctly.

Issue:
The server crash and reboot

Additional Info:
Server: Raspberry PI 4 (4Gb)
Operating System: Debian bullseye (kernel 5.15.56-v8+)
App Version: 1.24.0 build.48
Server Version 1.24.0

![IMG_1520](https://user-images.githubusercontent.com/111645772/185750202-7053e4f9-8401-46e3-962a-6de1224d10ed.PNG)

**Comment by alextran1502** [comment] 2022-08-20 14:23
Can you monitor the log from `immich-server` container?

**Comment by srlamin19** [comment] 2022-08-20 14:33
> 

Sure, here we are ...

[_immich_immich-server_1_logs.txt](https://github.com/immich-app/immich/files/9387300/_immich_immich-server_1_logs.txt)
.

**Comment by alextran1502** [comment] 2022-08-20 15:06
Hhmm, it doesn't indicate any error. I saw that it somehow restarted the server. Can you help me answer the following questions?

1. Which installation method did you do?
2. Did you change anything in the `docker-compose.yml` file?
3. Can you try restart the whole stack and try again to see if the issue is still there?

**Comment by srlamin19** [comment] 2022-08-20 15:11
> 



> Hhmm, it doesn't indicate any error. I saw that it somehow restarted the server. Can you help me answer the following questions?
> 
> 1. Which installation method did you do?
> 2. Did you change anything in the `docker-compose.yml` file?
> 3. Can you try restart the whole stack and try again to see if the issue is still there?

1. Docker (.env file)
2. No changes
3. I have restarted the server several times (also whole containers list)

Some another option to capture logs ?

[docker-compose.txt](https://github.com/immich-app/immich/files/9387496/docker-compose.txt)

**Comment by alextran1502** [comment] 2022-08-20 15:50
The log from the server is all I need but it doesn't indicate any problem there

Let's try removing the immich-machine-learning container and try again.

**Comment by srlamin19** [comment] 2022-08-20 17:25
> The log from the server is all I need but it doesn't indicate any problem there
> 
> Let's try removing the immich-machine-learning container and try again.

Same problem ..

**Comment by srlamin19** [comment] 2022-08-20 17:43
I can assume, there are many possibilities of issues, maybe we can wait for more cases like that , coming from others users.. I can wait for more comment similar :)

**Comment by srlamin19** [comment] 2022-08-21 08:32
Today, I'm testing again and I started the RPI in **CLI only** and now the backup is working, the files are send to server _without crash_. The process [**ffmpeg**] is more higher as usual, maybe they crash together with another process running in the server [_Kodi_ per example],  the _**temperature**_ increased a lot as well.

So far, the backup were concluded successfully! I hope help some one with these information's.

Thanks again!



https://user-images.githubusercontent.com/111645772/185782686-84f6deae-37b1-4729-8f0c-bd5925404002.mov

![IMG_0672](https://user-images.githubusercontent.com/111645772/185782684-07107809-69db-49b4-9823-75d8a0e20324.PNG)



.

**Comment by alextran1502** [comment] 2022-08-21 16:45
THe FFmpeg process is not higher than usual, it is just working during the uploading process to generate the thumbnail images or video encoding. After the work is done, it will mostly stay idle during operation

**Comment by alextran1502** [comment] 2022-08-21 16:45
I assume this issue is resolved I will close this issue, please feel free to reopen if needed

**Closed by alextran1502** 2022-08-21 16:45 UTC
Labels: bug, need triage
