### ISSUE TITLE
[Feature]: Programmatic pseudo albums

### ISSUE THREAD

**Issue by The-Noah** [immich-app/immich#962] opened 2022-11-12 22:53 UTC
### Feature detail

Organizing your content is important but having to always put items into albums is annoying and trying to organize years of content into albums is not realistic. I would love to be able to define a set of rules, and all content matching those rules are organized into a fake "album" where they are not in that album, but rather that "album" is just a view of all items that match its rules.

For example, I could create one for TikToks and say something like:
```
format: video
width: <= 1080
height: <= 1920
bitrate: <= 5000Kbps
```

Some ideas for filters would be: `file format` (image/video/raw/gif/etc), `width`, `height`, `file size`, `bitrate` (for videos), `video length`, `EXIF data` (camera, camera settings etc)

### Platform

Web

**Comment by bo0tzz** [comment] 2022-11-13 09:37
Duplicate of #570

**Closed** 2022-11-13 09:37 UTC
Labels: feature, need triage

**Comment by fivestones** [comment] 2023-09-24 05:04
@bo0tzz Is this really completed? How can I do this? Maybe I missed it in the documentation but I can't figure out how.

**Comment by bo0tzz** [comment] 2023-09-25 09:44
@fivestones it's not completed, it was closed as a duplicate.
