### ISSUE TITLE
[BUG] Video Upload fails 

### ISSUE THREAD

**Issue by IronBeardKnight** [immich-app/immich#4208] opened 2023-09-25 00:16 UTC
### The bug

It appease the app is having issues uploading videos from my Samsung galaxy ultra s21
![Screenshot_20230925_101113](https://github.com/immich-app/immich/assets/57257152/5fd6c3f2-1311-48ce-b19a-06b909141789)

### The OS that Immich Server is running on

Docker Unraid

### Version of Immich Server

1.79.1

### Version of Immich Mobile App

1.79.0 build 103

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by eeezae** [comment] 2023-09-25 01:15
Do you use Nginx as a proxy? Is it only one video that cannot be uploaded or all videos cannot be uploaded?

**Comment by IronBeardKnight** [comment] 2023-09-25 02:30
> Do you use Nginx as a proxy? Is it only one video that cannot be uploaded or all videos cannot be uploaded?

I do use Traefik but have bypassed the api subfolder part for that I picked up that the app was using push through and have had no issues with other short video and photos. 

I'm not sure that the error that I posted in the screenshot is directly related to the upload failure as I have noticed that if my sceen locks or I go out of the app not closing it at all then the transfer stops and goes back to zero transferred again its almost like it wants me to keep the app open and not allow any locks or changes of app.

**Comment by IronBeardKnight** [comment] 2023-09-25 02:59
Yeah definitely seems like background services are not working on Android 13

**Comment by IronBeardKnight** [comment] 2023-09-25 05:15
So after digging a whole lot through android system settings and even forcing to stay active via the samsung battery settings the issue still persists so it would appear that the background process settings and even the foreground settings don't seem to be working.

Happy to help testing in any way I can guys.

**Comment by IronBeardKnight** [comment] 2023-09-25 05:50
Update: followed samsug battery guide thing and it appears to now be uploading at least but still hase some sort of visual bug as seen here:

**Comment by alextran1502** [comment] 2023-09-25 07:36
Please try to connect to your instance with your local IP. I suspect that the proxy you are using has a size limitation.

**Comment by IronBeardKnight** [comment] 2023-09-25 07:41
> Please try to connect to your instance with your local IP. I suspect that the proxy you are using has a size limitation.

I will try this however it only stops uploading only when the app is closed, screen goes off, or I navigate to another app and then come back to check its stopped and reset to 0% with nothing in the logs to state why.


I have checked debug logs of traefik, Authelia, crowdsec and all seems to be well. 

If I leave the app open and keep tapping the screen to not let it sleep or time out then the percentage of upload rises as expected but as soon as it locks or anything the upload is cancelled it seems.

**Comment by alextran1502** [comment] 2023-09-25 07:53
The foreground and background tasks are two different mechanisms when you switch the app i.e. putting it into the background, foreground upload will stop running, and the OS will schedule background tasks to run at a later time. So what you are describing is working as intended.

We are trying to solve the issue you are facing which is video files are not uploading while images are uploading succesfully, this indicates a proxy issue.

**Comment by IronBeardKnight** [comment] 2023-09-25 08:00
> The foreground and background tasks are two different mechanisms when you switch the app i.e. putting it into the background, foreground upload will stop running, and the OS will schedule background tasks to run at a later time. So what you are describing is working as intended.
> 
> We are trying to solve the issue you are facing which is video files are not uploading while images are uploading succesfully, this indicates a proxy issue.

That is not an issue as stated here :)
 https://github.com/immich-app/immich/issues/4208#issuecomment-1732811567 

Oh ok then that makes sense that working in foreground and background but is it not possible to cache progress as it moves accross the tasks as I have never seen that before on the likes of nextcloud etc? anyway.

So the only thing I have seen in terms of notification is Upload failed without any further information, can you advise what the background upload time frame is from task swtich to upload or is that set in the notify background  backup failures sections of the app settings ?

**Comment by IronBeardKnight** [comment] 2023-09-25 08:11
> Are you asking about when will the background task get invoked?

Yep :)

**Comment by IronBeardKnight** [comment] 2023-09-25 09:32
So all the power saving features I can find are off. I have not opened the app since this last comment and the file is still not synced. The file is around 1gb in size.

**Comment by alextran1502** [comment] 2023-09-25 10:22
Are you still connecting to the instance over dns or local ip?

**Comment by IronBeardKnight** [comment] 2023-09-25 13:01
Still the same issue running with the local ip:port/api.

Still nothing showing in background apps.

**Comment by IronBeardKnight** [comment] 2023-09-25 13:02
> Are you still connecting to the instance over dns or local ip?

sorry for the delay  mate had to get some tukker etc. as above

**Comment by alextran1502** [comment] 2023-09-25 13:15
Hello, I just double check with the team members who use Android and background backup works on their phone, so most likely this is Samsung's known issue of preserving battery strategy to kill background task. Do you see other photos get uploaded on your phone?

**Comment by IronBeardKnight** [comment] 2023-09-25 14:01
> Hello, I just double check with the team members who use Android and background backup works on their phone, so most likely this is Samsung's known issue of preserving battery strategy to kill background task. Do you see other photos get uploaded on your phone?


Ok so background uploads for smaller files seem to be working however the app still does not show up in background running services dispite still uploading.

It does not seem to want to upload this 1gb video file though which is very strange its like it only wants to do it in the forground  when the app is open

**Comment by alextran1502** [comment] 2023-09-25 14:11
@IronBeardKnight ah I got the full picture now. We actually put in a mechanism to upload photos first then videos because photos usually have smaller size than videos and most of the time will successfully upload.

**Comment by alextran1502** [comment] 2023-09-25 14:50
I will close this issue now since it has been cleared up

**Closed by alextran1502** 2023-09-25 14:50 UTC
Labels: bug, need triage

**Comment by IronBeardKnight** [comment] 2023-09-25 23:58
@alextran1502 thats not what I am getting at or an issue in my opinion. The issue is that wen photos are finished or smaller stuff is done I'm still left with a 1 > gb  video file that won't upload in the background and resets upload when ever I exit the app.

Background Upload is not working from device for larger files in the it seems.

Woke up this morning and everything seems to be uploaded except for the larger video files so something is defiantly wrong as this was setup as per your documentation with local ip.

If I can provide my input on the whole foreground, background upload process, its diffidently a better solution to see uploads persisting across these two states and not being reset when transitioning from foreground to background  visa versa as it is confusing seeing a file constantly ready and restarting upload when its of bigger size. 
I think it would be much better and a huge win to see persistent upload when crossing processing level. Perhaps chunking is the way to achieve this.

To summaries:

- Smaller videos and photos <1gb seem to upload fine over local ip and proxy using both background and foreground.

These two next points somewhat stall the upload process making it hard to believe everything is backed up not just bits and pieces.

- Larger video files don't seem to be uploading in the background process.

- Larger video files will reset upload if not complete during the foreground if you leave the app. 

- On rare occasion the upload progress bar seems to wig out and flashes between two different percentages almost like its trying to upload the same file twice or is trying to display multipule upload percentages which is i'm assuming a gui bug I have a video of this if you like.

On a side not I appreciate the feedback on this issue greatly and think the application you have put together guys is amazing and what the open world needs in terms of new age photo storage. 

Thank you.
