### ISSUE TITLE
App won't launch - Android 10

### ISSUE THREAD

**Issue by patienttruth** [immich-app/immich#14593] opened 2024-12-09 04:58 UTC
### The bug

Just wiped an older phone to give to my son (Samsung S9).

It's updated, but that means Android 10.

I had Immich on it before the reset, but I'm not sure if it was updated. I had installed it a few months ago (September).

So sometimes the URL screen shows up, sometimes it's just the Immich logo, sometimes a black screen. When I get the URL screen I can't click into the box, although a keyboard shows up sometimes, and I can't type into it.

Most other apps work fine...

Any ideas? Unfortunately trying other APKs isn't easy as it's set up with parental controls so I'm limited there. Perhaps I can use ADB, but I haven't tried yet.

### The OS that Immich Server is running on

Ubuntu / Docker

### Version of Immich Server

1.120.2

### Version of Immich Mobile App

1.122.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

I can shoot a video, but can't even reliably see the logs page, so not sure I can help much other than say something is up with it...

**Comment by mmomjian** [comment] 2024-12-09 05:00
This is duplicate of #8917

**Closed by mmomjian** 2024-12-09 05:00 UTC

**Comment by patienttruth** [comment] 2024-12-09 05:03
> This is duplicate of #8917

Thanks!

**Comment by patienttruth** [comment] 2024-12-09 05:03
> > This is duplicate of #8917

Is there a way to flag the app in playstore so it won't install on older devices?

**Comment by patienttruth** [comment] 2024-12-09 05:06
> This is duplicate of #8917

Is it actually a duplicate of that? It downloads and installs fine which is my understanding of what the target API relates to.

Here's a screenshot from last time I tried and it actually opened to the logs screen after I tried to launch.

![PXL_20241209_050121151~2](https://github.com/user-attachments/assets/6e923c7d-c7d1-4d38-8951-ae5273da39e4)

**Comment by patienttruth** [comment] 2024-12-09 05:21
In any case, thanks for the lead @mmomjian. I'll see if I can download an older release and side load it.

Fwiw, I'm unsure if duplicate is appropriate at this point considering that Android 10 is API 29, and that discussion and thread are referencing API 24 as the solution for Android 7. Further, the current release is minimum API 26 which is Android 8.

Just dropping some keywords for anyone else searching like I was.

**Comment by alextran1502** [comment] 2024-12-09 13:37
Please try the new apk from the latest release which fixed some rendering glitches on v1.122.2

**Comment by patienttruth** [comment] 2024-12-13 14:06
> Please try the new apk from the latest release which fixed some rendering glitches on v1.122.2

Good morning @alextran1502 and @mmomjian, that did the trick! 

Initially it logged in normally, then started giving server/app mismatch errors so I updated the server from v1.20.2 and now we're good to go. 

Thank you so much! That old phone's useful life continues. 🙂
