### ISSUE TITLE
Viewing stacked images breaks navigation

### ISSUE THREAD

**Issue by buengese** [immich-app/immich#14475] opened 2024-12-04 12:57 UTC
### The bug

When viewing a stacked image navigating to the next or previous image breaks. See reproduction steps for details.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default template
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. Go to the timeline
2. Open any stacked image
3. Use or hover over the stack selected to view a different image in the stack.
4. Click right arrow (or use the arrow keys) to browse to next image ("View next asset")

Expected outcome: next image is displayed

Actual outcome: nothing happens

**Comment by bo0tzz** [comment] 2024-12-04 13:07
Dupe of #14101

**Closed by bo0tzz** 2024-12-04 13:07 UTC
