### ISSUE TITLE
[BUG] Unsupported file type

### ISSUE THREAD

**Issue by 1karu5** [immich-app/immich#3351] opened 2023-07-20 16:31 UTC
### The bug

I have some photos from my dji drone on the iPhone and they fail to upload.
The Immich iOS app reports just failed with a bad request.
The server log containts:

```
immich_server            | [Nest] 1  - 07/20/2023, 4:16:28 PM   ERROR [AssetService] Unsupported file type dji_fly_20230617_132158_978_1687006741843_photo_optimized
```

Exiftool reports the following on the image:

```
ExifTool Version Number         : 12.60
File Name                       : dji_fly_20230617_132158_978_1687006741843_photo_optimized.JPG
Directory                       : .
File Size                       : 6.7 MB
File Modification Date/Time     : 2023:06:17 14:59:01+02:00
File Access Date/Time           : 2023:07:20 18:22:06+02:00
File Inode Change Date/Time     : 2023:07:20 18:22:04+02:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 72
Y Resolution                    : 72
Exif Byte Order                 : Big-endian (Motorola, MM)
Make                            : DJI
Camera Model Name               : FC7203
Orientation                     : Horizontal (normal)
Exposure Time                   : 1/120
F Number                        : 2.8
ISO                             : 100
Aperture Value                  : 2.8
Max Aperture Value              : 2.8
Color Space                     : sRGB
Exif Image Width                : 4000
Exif Image Height               : 2250
Image Width                     : 4000
Image Height                    : 2250
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.8
Image Size                      : 4000x2250
Megapixels                      : 9.0
Shutter Speed                   : 1/120
Light Value                     : 9.9
```

Other jpg images are working fine.

### The OS that Immich Server is running on

Linux

### Version of Immich Server

v1.68.0

### Version of Immich Mobile App

v1.67.0 build.107

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/some/location
IMMICH_VERSION=v1.68.0
```

### Reproduction steps

```bash
1. Start immich with docker compose
2. Install iOS app, try to backup some foto from the dji app/drone
3. Fails in iOS app, error message in docker logs
```

**Comment by alextran1502** [comment] 2023-07-20 16:32
Can you update the mobile app and try again? If it still not working, can you include a test file in this issue so we can reproduce and troubleshoot?

**Comment by uhthomas** [comment] 2023-07-20 16:32
Duplicate of #2719

**Comment by 1karu5** [comment] 2023-07-20 20:14
![dji_fly_20230207_101604_864_1675881689822_photo_optimized](https://github.com/immich-app/immich/assets/4019270/571a8e42-1d08-48b8-8299-c356141b03f1)
I updated the app (to 1.68.0 build.108). Error is still the same.

I think github changes the filename. Original was `dji_fly_20230207_101604_864_1675881689822_photo_optimized.JPG`. I am not sure if the metadata will be the same 🤔 

And yes, looks like a duplicate. Sorry for that.

**Comment by 1karu5** [comment] 2023-07-20 20:32
Just a guess, but it looks like as if the filename is `dji_fly_20230207_101604_864_1675881689822_photo_optimized` (without extension) on the phone.
![IMG_2023-07-20T22-27-50](https://github.com/immich-app/immich/assets/4019270/7e5ef141-c6eb-4dce-9a25-1ea03da110e3)

Immich (and also google photos) reports it without `.JPG`. 
That would also explain why the server is reporting the filename as an filetype in the logs: there is simply no extension.
I guess iOS will add a extension as soon as I export the image to some app/pc.

**Comment by uhthomas** [comment] 2023-07-20 20:37
That might explain it. We're looking into detecting the file type from the content automatically so it may fix this. Though really it should have an extension, I wonder why it doesn't.

**Comment by bo0tzz** [comment] 2023-07-24 11:09
Closing as this is a duplicate

**Closed by bo0tzz** 2023-07-24 11:09 UTC
Labels: bug, need triage

**Comment by mitchross** [comment] 2023-12-21 14:14
I am in this same bucket. My CLI and app breaks too. Can the CLI just skip images/files without file extensions? Google photos has a ton of "files" without extensions.

**Comment by oldwang12** [comment] 2024-04-06 03:10
Both v1.100.0 and v1.101.0 have this issue

```txt
[Nest] 1  - 04/06/2024, 2:58:59 AM   ERROR [AssetService] Unsupported file type FullSizeRender.livp
[Nest] 1  - 04/06/2024, 2:59:08 AM   ERROR [AssetService] Unsupported file type FullSizeRender.livp
```

**Comment by jeff15110168** [comment] 2024-04-10 02:41
i'm also having this issue. is there any fix for this?

**Comment by alextran1502** [comment] 2024-04-10 02:46
@jeff15110168 which file type are you trying to upload?

**Comment by jeff15110168** [comment] 2024-04-10 03:03
> @jeff15110168 which file type are you trying to upload?

Just a normal picture - it might be detecting no file extension? I went into photos and hit "duplicate" then deleted the original and instead of the exclamation error, it now is stuck at 0.25mb and not moving. But either way it's not uploading

![IMG_8177](https://github.com/immich-app/immich/assets/9892738/00ce9d28-45e0-4bed-beb1-48d1c519160c)

**Comment by alextran1502** [comment] 2024-04-10 03:05
@jeff15110168 yeah it could be because there is no file extension there. For these specific photos, try to move them to your computer, add the correct file extension and upload via the web UI

**Comment by jeff15110168** [comment] 2024-04-10 03:18
> @jeff15110168 yeah it could be because there is no file extension there. For these specific photos, try to move them to your computer, add the correct file extension and upload via the web UI

Okay - I ran each of the 20-30 pictures through an exif metadata app and just saved a new copy / deleted older version which added the .jpg.

Of note - all these files I downloaded were from a family members shared immich library that I added to my own phone. Is there a planned fix to make these files uploadable? It would be extremely cumbersome for me to add extensions to files downloaded from immich partner library

**Comment by jrasm91** [comment] 2024-04-10 03:23
Are these downloaded from an external library or an upload library? I believe the former was due to a bug they had since been fixed, although it might require another library scan.

**Comment by jeff15110168** [comment] 2024-04-10 03:31
> Are these downloaded from an external library or an upload library? I believe the former was due to a bug that has since been fixed, although it might require another library scan.

All the pictures with the issue are from an external library (old cannon family pictures mounted on a share on my unRAID server) that are then assigned to a family member's account as owner and then shared with me (owner of server) where I can navigate on iOS app -> sharing -> partner -> [family member's photos] then can download files from their library onto my local iphone (which then get backed up to my own immich account)

**Comment by timmillwood** [comment] 2024-12-29 09:31
I have the same issues with DJI front photos.

**Comment by effzeh1720** [comment] 2025-03-03 15:24
I have the same problem. Is there anything new about this?
