### ISSUE TITLE
[BUG] Search API only returns 250 results with no way of paging

### ISSUE THREAD

**Issue by agross** [immich-app/immich#3805] opened 2023-08-20 20:04 UTC
### The bug

Calling `curl -L -X GET '<server>/api/search?type=VIDEO' -H 'Accept: application/json' -H 'x-api-key: the-key'` returns just 250 results.

```sh
$ curl ... | jq '.assets.items | length'
250

$ curl ... | jq '.assets.total'
789
```

Limiting results without the possibility to page is not useful if you have a lot of videos in your collection.

### The OS that Immich Server is running on

Linux

### Version of Immich Server

v1.74.0

### Version of Immich Mobile App

v1.74.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
unrelated
```

### Your .env content

```Shell
unrelated
```

### Reproduction steps

```bash
See above.
```

**Comment by jrasm91** [comment] 2023-08-20 20:34
It's more useful than 0 results 😁

**Comment by bo0tzz** [comment] 2023-08-20 20:37
Duplicate of #3072. This limit is in place because of browser performance concerns. Some work has been done recently to improve that across the app, but this hasn't reached the search results page yet.

**Closed by bo0tzz** 2023-08-20 20:37 UTC
Labels: bug, need triage
