### ISSUE TITLE
[BUG] iOS app crashes when switching to landscape orientation

### ISSUE THREAD

**Issue by CNpunkt** [immich-app/immich#1259] opened 2023-01-05 19:39 UTC
**Describe the bug**
First of all, thank you for this great software!

Unfortunately, I have a bug in the iOS app. I have my phone in portrait orientation and open a photo from an album. As soon as I turn the phone to landscape orientation, the app crashes completely.

I only have this problem on the iPhone (iPhone 13). It works fine on the iPad. I can therefore pretty much rule out a problem with the server. I think it's more of a resource management problem.

Number of photos: almost 20,000
Number of albums: 81

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [X] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Open a photo from an album in the iOS app on the iPhone in portrait orientation
2. Rotate the iPhone to Landscape orientation

**Expected behavior**
The app should not crash

**System**
- Phone OS [iOS, Android]: iOS 16.2 (iPhone 13)
- Server Version: `1.40.0`
- Mobile App Version: `1.40.0 build.77`

**Comment by alextran1502** [comment] 2023-01-05 19:45
Hmm interesting, I cannot reproduce this behavior on my iPhone 12 Pro. Granted I only have about 6000 photos/videos stored on the phone.

**Comment by CNpunkt** [comment] 2023-01-05 19:55
I was afraid of that :-)
Also a reinstallation of the app unfortunately leads to the same result.

**Comment by alextran1502** [comment] 2023-01-15 20:04
I am closing this issue as I cannot reproduce the issue at the moment to troubleshoot

**Closed by alextran1502** 2023-01-15 20:04 UTC
Labels: bug, need triage
