### ISSUE TITLE
[BUG] Backup page pretends there is nothing when a backup is running

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#889] opened 2022-10-29 13:58 UTC
**Describe the bug**
When I'm uploading assets, close the app, and re-open it, the backup page pretends like there are no items.
So the amount of items for 'total' is 0, the amount for 'back upped items' is 0, and the remaining amount is also zero.
Additionally, when scrolling down, the 'server storage' says 'Used 0 of 0' and the info about the current file that is being uploaded, is empty. The progress bar is on 0%, filename is '... [...]', and ID is '...'. Strangely enough, the 'taken on' date says 'October 4, 2020'.
Also, it says that there are no selected albums, which is weird, because I have selected albums (the album 'recent' which uploads everything)
It's like nothing is being uploaded, despite the notifications clearly stating that there are items being uploaded.

Perhaps this has something to do with the fact that thousands of the images have already been uploaded? So that there are thousands of duplicates, rejected by the server, causing this error?

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to 'Backup page'
2. Start the backup
3. Close the application and open it again
4. Visit the backup page
5. See the backup page, pretending there is nothing being uploaded

**Expected behavior**
I expected the backup page to show the correct values for total, uploaded, and remaining items. Additionally, I expected these values to change accordingly to the backup status. So if an item gets uploaded, the 'uploaded' items should be upped with 1, whereas the 'remaining items' should decrease by 1.
Also, I expect the file information to contain the information about the currently uploaded file. 

**System**
- Phone OS [iOS, Android]: `11`
- Server Version: `1.33.0`
- Mobile App Version: `1.33.0 build.52`

**Additional context**
When running `adb shell "logcat --pid=$(pidof -s app.alextran.immich)"` with my phone attached, I see this line a lot in my logs:
```
WM-Processor: Moving WorkSpec (b78faf6a-d7e3-439a-8405-7d1eaea8c007) to the foreground
```
I don't know if this has anything to do with the errors.

**Comment by bo0tzz** [comment] 2022-10-29 14:01
I think this might actually be a duplicate of #834

**Comment by JVT038** [comment] 2022-10-29 14:02
Oops, if that's the case, you may close this issue.
I didn't know that issue was related to this one, because I'm not familiar with the terminology used in that issue.

**Closed** 2022-10-29 14:08 UTC
Labels: bug, need triage
