### ISSUE TITLE
Bug(Web): Stacked images are not refreshing

### ISSUE THREAD

**Issue by JW-CH** [immich-app/immich#14339] opened 2024-11-25 15:19 UTC
### The bug

When selecting (or hovering) over a stacked image (1.) and then switching to another image with the previous or next arrow (2.) the image new image is not displayed. Compare UUIDs in the steps 3. / 4.

![image](https://github.com/user-attachments/assets/70d08599-50d7-468a-81f6-62ec8a4530a9)
![image](https://github.com/user-attachments/assets/767af17f-1d4b-414d-92f1-9c0e6928a51a)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not needed
```

### Your .env content

```Shell
not needed
```

### Reproduction steps

1. Display stacked image
2. Select (sub-)item in stack.
3. Switch to another image
4. Image not refreshed, compare UUIDs

### Relevant log output

```shell
not needed
```

**Comment by michelheusschen** [comment] 2024-11-25 16:06
Duplicate of #14101?

**Closed** 2024-11-25 16:34 UTC
Labels: good first issue, 🖥️web

**Comment by JW-CH** [comment] 2024-11-25 16:37
> Duplicate of #14101?

Was not sure if this was the exact same. Nevertheless, Alex was faster 🚀
