### ISSUE TITLE
[BUG] iOS live photos which have been rotateed or an effect are shown as separate images and videos in immich

### ISSUE THREAD

**Issue by philw07** [immich-app/immich#5473] opened 2023-12-03 20:58 UTC
### The bug

When uploading a live photo from iOS which has either been rotated or an effect (bounce, loop, etc.), it will be displayed as separate photo and video in immich.
In case of rotated photos, the video has the original orientation.
I would expect it to show as a regular live photo in immich (without any effect, but ideally rotated correctly).

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.89.0

### Version of Immich Mobile App

v1.89.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      - default
      - web
    labels:
      <traefik labels>

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "microservices"]
    volumes:
      - photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


networks:
  web:
    external: true


volumes:
  pgdata:
  model-cache:
  tsdata:
  photos:
    <nfs share options>
```

### Your .env content

```Shell
IMMICH_VERSION=release

TYPESENSE_API_KEY=<pw>
DB_PASSWORD=<pw>

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Take a live photo on iOS device
2. Rotate it or add an effect (bounce, lopp, etc.)
3. Upload the photo to immich
4. Immich will show a separate photo and video
```

**Comment by philw07** [comment] 2023-12-03 21:43
@shenlong-tanwen It’s also not linked in the web interface.

**Comment by shenlong-tanwen** [comment] 2023-12-03 21:47
> @shenlong-tanwen It’s also not linked in the web interface.

Odd. Does this happen only for live photo with edits? Also, is it possible to share such live photo as a file to reproduce the issue?

You can also check the following things:
- Ensure that the Meta data extraction job is running and refresh the metadata manually for the still and motion part of the live photo from the web app
- Check if both the photo and motion part of the live photo has the `livePhotoCID` EXIF tag set and to be equal for both the assets.

**Comment by mike12806** [comment] 2023-12-04 16:45
I'm seeing the same issue but without editing the photo, I'm still getting a video and the photo uploaded. Not sure if it's silently editing the file in the background, but I also have the nextcloud app uploading photos too....

**Comment by shenlong-tanwen** [comment] 2023-12-05 03:47
> For me, it's fine in the web interface (they are linked)....

If they are linked in the web app, Kindly swipe twice in the main timeline of the mobile app to trigger a full sync of assets which would link them in the mobile app as well. Your issue where the asset is linked in the web-app and not in the mobile app would be fixed in the next release.

**Comment by philw07** [comment] 2023-12-05 11:53
So after some reading, I took a live photo and uploaded it to immich and checked the exif using exiftool afterwards.
The image was correctly displayed as a live photo in immich and both the HEIC image and MOV video had the same identifier.

```
$ exiftool -a -u -g1 IMG_4331.HEIC | grep UUID
Media Group UUID                : 0B62DBD0-DF75-4CBC-8F33-EDEAD7F3E5DF

$ exiftool -a -u -g1 IMG_4331.MOV | grep Identifier
Content Identifier              : 0B62DBD0-DF75-4CBC-8F33-EDEAD7F3E5DF
```
Afterwards, I deleted the photo and rotated it in iOS, then uploaded it again.
This time, it was displayed as separate photo and video in immich.
I checked the exif data again and indeed the identifier of the image was changed, but the identifier of the video stayed the same.

```
$ exiftool -a -u -g1 IMG_4331.HEIC | grep UUID
Media Group UUID                : 8CC62E05-CA31-49F8-A114-C3FFD2FEBD6F

$ exiftool -a -u -g1 IMG_4331.MOV | grep Identifier
Content Identifier              : 0B62DBD0-DF75-4CBC-8F33-EDEAD7F3E5DF
```

This seems to explain why immich can't link them.
Unfortunately, I could neither find the new ID in the video metadata, nor the old one in the image metadata.
Hence I'm not sure if it's possible to link them after the image has been edited.

**Comment by mike12806** [comment] 2023-12-05 11:55
I'm seeing this without having edited the photo. Re-running metadata extraction fixes it.

**Comment by ChristopherFunk** [comment] 2023-12-07 01:42
I'm seeing this without editing the photos, and re-running metadata extraction does not fix it for me

**Comment by shenlong-tanwen** [comment] 2023-12-07 07:29
> I'm seeing this without editing the photos, and re-running metadata extraction does not fix it for me

Are your assets not linked in the web app as well? If so, Can you share the original photo and video asset that are supposed to be linked together? If they have sensitive or personal info, Can you try reproducing it with a new Live photo and share it with us for troubleshooting?

**Comment by ChristopherFunk** [comment] 2023-12-08 04:32
Hello, yes it is happening in web, I have older photos where this happens too, starting December 1st (which is weird I don't think it happened around a release).
Also confirming I went to the web and under admin re-ran EXTRACT METADATA on ALL photos

This is from today
- Photos in the web, it's hard to tell but the right photo has the 0:01 Play button icon in it
![live photo split into 2 on web](https://github.com/immich-app/immich/assets/8630493/0dfe500c-bebd-404b-a185-1e10310a4047)

- Photo
![photo-from-live-photo](https://github.com/immich-app/immich/assets/8630493/4073ca66-45af-4106-b5fc-85c213105b73)

- Video
![video-from-live-photo](https://github.com/immich-app/immich/assets/8630493/6f4ec803-3683-4d27-a478-c93b23d9c0b9)

and here they are downloaded from immich web:
- https://drive.google.com/file/d/1C27Wt_yvoZsU2iW_53JHlmwrNkIpQUPE/view?usp=sharing
- https://drive.google.com/file/d/1pZCYzCyMJ4LTtKgAlOswoASA50X19A2-/view?usp=sharing

and the original photo:
- https://share.icloud.com/photos/051pCTfyr2RUy6sbq2w47sAsA

This is coming from an iPhone 14 Pro, and I just checked the app version is up to date, v1.89.0, server on same version

Let me know if you need anything else, happy to help!

**Comment by shenlong-tanwen** [comment] 2023-12-11 18:15
@philw07 / @ChristopherFunk Both of your issues should be fixed in the next version of the app. We'll keep this issue open until the next release.

**Comment by philw07** [comment] 2023-12-11 18:39
Fantastic, thanks so much.
I will check when the update is available.

**Comment by ChristopherFunk** [comment] 2023-12-13 05:09
Woohoo! Thanks so much! I'm assuming we'll need to do another metadata refresh to fix existing photos?

**Comment by smndtrl** [comment] 2023-12-17 19:15
@shenlong-tanwen In which commit was this fixed? I'm curious how this was solved.
I might have a few hundred of those images where the tag in EXIF does not match and there are no "originals" available on the phone anymore.

**Comment by philw07** [comment] 2023-12-17 21:08
I updated my server and app and re-uploaded several live photos as well as taking and editing some new photos.
Everything seems to be linked correctly, so from my point of view this ticket can be closed.
I’m keeping it open for @ChristopherFunk to confirm it’s working on his side.

@shenlong-tanwen Thanks again.

@smndtrl I think that would be #5602.

**Comment by smndtrl** [comment] 2023-12-17 21:28
Interesting. I'm wondering if that change lead to the other issue I'm seeing.
A live photo (bounce effect) export is correctly matched, yet the file metadata and quality is hugely affected. See the second image with resolution, filesize and missing metadata like GPS.

My app version is `1.91.2` and the server runs on `1.90.2`

The following image shows `IMG_6086 (1)`, which is the export from Apple Photos vs `IMG_6086`, the download from the immich server.
![image](https://github.com/immich-app/immich/assets/9169479/a3f47eae-d25e-40a3-8e07-7d8644615941)

The live photo is matched fine since the update.
![image](https://github.com/immich-app/immich/assets/9169479/07030bc4-c91a-4516-841d-5d2b81a78430)

If switching off the live photo effect, the same photo is displayed like this.
![image](https://github.com/immich-app/immich/assets/9169479/c8a9fc0a-fd45-41df-8014-02ec50fdfd8f)
With more similar file sizes to the Apple Photos export.
![image](https://github.com/immich-app/immich/assets/9169479/b4862726-e9db-4d1f-aefe-f32fb3f3139d)



@philw07 Did you notice something similar for recent live photos with effects? If not, I'm going to have to open up a new issue to figure this out.

**Comment by alextran1502** [comment] 2023-12-17 21:46
@smndtrl hello, do you know if those LivePhotos get edited anyway after being taken?

**Comment by smndtrl** [comment] 2023-12-17 22:01
The only thing I did was to 

1. switch from `Live` to `Bounce`
2. Then sync from iOS to the server
3. Download them (small HEIC)
4. Switch from `Bounce` to `Live`
5. Delete image from server
6. Sync again from iOS

All looks good on the server

No cropping, painting, rotating or anything else. I didn't even use the `Edit` menu but the quick switcher.

**Comment by philw07** [comment] 2023-12-17 22:09
I didn’t notice it before, but I can confirm it also happens on my side.

**Comment by WolfgangDpunkt** [comment] 2023-12-18 14:01
How can we identify photos that need to be deleted and re-uploaded?
I uploaded thousands of iOS-photos during this specific period and have them backed up in iCloud. However, I want to locate the photos that require deletion and re-upload to be properly linked. Is there a search string specifically for iOS photos? 
(Crosspost from [Reddit](https://www.reddit.com/r/immich/comments/18jy24v/q_how_to_identify_live_photos_uploaded_with/), sorry, but I was not sure if it will be noticed there)

**Comment by shenlong-tanwen** [comment] 2023-12-18 15:46
> @philw07 Did you notice something similar for recent live photos with effects? If not, I'm going to have to open up a new issue to figure this out.

Can you raise this as a separate issue?

**Comment by shenlong-tanwen** [comment] 2023-12-18 15:52
> How can we identify photos that need to be deleted and re-uploaded? I uploaded thousands of iOS-photos during this specific period.

You can check the comment by [Christopher](https://github.com/ChristopherFunk) - https://github.com/immich-app/immich/issues/5473#issuecomment-1846533152

The still and motion photos are getting displayed as two different assets in the thumbnail. Which means that the live photo is not properly linked

**Comment by ChristopherFunk** [comment] 2024-01-05 00:56
> I updated my server and app and re-uploaded several live photos as well as taking and editing some new photos. Everything seems to be linked correctly, so from my point of view this ticket can be closed. I’m keeping it open for @ChristopherFunk to confirm it’s working on his side.
> 
> @shenlong-tanwen Thanks again.
> 
> @smndtrl I think that would be #5602.

Hi sorry! It's all working on my end! Been uploading photo's like crazy and no issue on my end! 😄

**Closed** 2024-01-05 00:57 UTC
Labels: bug

**Comment by CarterMoody** [comment] 2024-04-28 03:09
Still an issue for me on 1.102.3 I have the exact same symptoms as this. This has not been fixed? :

> Hello, yes it is happening in web, I have older photos where this happens too, starting December 1st (which is weird I don't think it happened around a release). Also confirming I went to the web and under admin re-ran EXTRACT METADATA on ALL photos
> 
> This is from today
> 
> * Photos in the web, it's hard to tell but the right photo has the 0:01 Play button icon in it
>   ![live photo split into 2 on web](https://private-user-images.githubusercontent.com/8630493/288961038-0dfe500c-bebd-404b-a185-1e10310a4047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzM5MjIsIm5iZiI6MTcxNDI3MzYyMiwicGF0aCI6Ii84NjMwNDkzLzI4ODk2MTAzOC0wZGZlNTAwYy1iZWJkLTQwNGItYTE4NS0xZTEwMzEwYTQwNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDMwNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRlYjc5NDBiNzAxYmM4ZmRiZjEzNGE0YjE5MGQ1ZWY0OGM0OGM2ZGRjMTBlZWNmYTMxNGNmYjYzNmM3YzlkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mSd3pRV0FUnDKE3jMU7hszEr3rcl_PA6cacBt2l-jlI)
> * Photo
>   ![photo-from-live-photo](https://private-user-images.githubusercontent.com/8630493/288959454-4073ca66-45af-4106-b5fc-85c213105b73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzM5MjIsIm5iZiI6MTcxNDI3MzYyMiwicGF0aCI6Ii84NjMwNDkzLzI4ODk1OTQ1NC00MDczY2E2Ni00NWFmLTQxMDYtYjVmYy04NWMyMTMxMDViNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDMwNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVhNjU0ODRhYjI0NTY5NzMyZTJlM2FhNTNjMTQzOTliMzFkODIwMGUxZWJkYzQ3MzkzM2Y1ODM3ZDQ0MTIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tU6xADleZsh3RHlamoy6TqPszHvOmrX4tXfptbhyOvc)
> * Video
>   ![video-from-live-photo](https://private-user-images.githubusercontent.com/8630493/288959461-6f4ec803-3683-4d27-a478-c93b23d9c0b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzM5MjIsIm5iZiI6MTcxNDI3MzYyMiwicGF0aCI6Ii84NjMwNDkzLzI4ODk1OTQ2MS02ZjRlYzgwMy0zNjgzLTRkMjctYTQ3OC1jOTNiMjNkOWMwYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDMwNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThlMmNjYzgwM2FhZDJkNzJhYzJkNjNhY2IwMjFiODhkMDhmM2NlNTU2NTJiNWYzZTZlMzRkNGYyODY0MjA3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3rQV6nh_eZhcTSXqnBKKELFRs7wlZNxqkcf-dAzNh5s)
> 
> and here they are downloaded from immich web:
> 
> * https://drive.google.com/file/d/1C27Wt_yvoZsU2iW_53JHlmwrNkIpQUPE/view?usp=sharing
> * https://drive.google.com/file/d/1pZCYzCyMJ4LTtKgAlOswoASA50X19A2-/view?usp=sharing
> 
> and the original photo:
> 
> * https://share.icloud.com/photos/051pCTfyr2RUy6sbq2w47sAsA
> 
> This is coming from an iPhone 14 Pro, and I just checked the app version is up to date, v1.89.0, server on same version
> 
> Let me know if you need anything else, happy to help!

**Comment by alextran1502** [comment] 2024-04-28 03:42
@CarterMoody if a LivePhotos is modified, it will lose the information that we need to link the two files together... and this is due to how Apple handles file editing, unfortunately

**Comment by CarterMoody** [comment] 2024-04-28 18:22
@alextran1502 I have not modified any of these photos yet they still show up this way. I have run the metadata extraction job on my entire library and they still show up as both a still and a live photo separately. What do I need to do to fix this?

**Comment by afonsofrancof** [comment] 2024-07-14 20:31
I also have this issue. I don't edit any of my live photos yet some are uploaded correctly and others are uploaded as video+photo. It's a bit annoying, and at the moment I have disabled live photos on my phone.
Would be nice to have a way to manually link them

**Comment by 7122435** [comment] 2024-07-25 17:59
Hello. Same problem here. On 1.109.2 version of Immich (iOS 17.5.1) Live Photos are not uploaded properly. Some photos taken with my iPhone are separated into two elements - a 1s long video and an image. The video is correctly synchronized with the server, but the image is not synchronized at all. This only happens with some Live Photos. The remaining Live Photos are synchronized correctly. None of them were edited on iPhone before syncing.
