### ISSUE TITLE
Opening bottom drawer causes reload

### ISSUE THREAD

**Issue by haenoe** [immich-app/immich#11916] opened 2024-08-19 20:38 UTC
### The bug

Hey, first of all thank you for this amazing piece of software!

https://github.com/user-attachments/assets/45201184-0a79-4f04-a722-a03631f7bf90

Sadly this is not something that only happens with the demo server.
Hope I'm not missing anything here, thanks for any tips or hints.

Maybe I'll find some time to look at this -- but probably not. So feel free to investigate :D

Thank you!

### The OS that Immich Server is running on

demo

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
see demo.immich.app
```

### Your .env content

```Shell
see demo.immich.app
```

### Reproduction steps

```bash
1. Search for a keyword
2. Select images and try to open the bottom drawer
3. App seems to do some sort of reload, which closes drawer making it practically unusable.
```

### Additional information

I'm using Android 14 with One UI 6.1 on my Samsung Galaxy A52s 5g

**Comment by picarica** [comment] 2024-08-20 06:09
dupe of #10651  and #8635 
waiting for fix for a while

**Closed** 2024-08-20 06:29 UTC
