### ISSUE TITLE
[BUG] iOS app forever loading backup page

### ISSUE THREAD

**Issue by Harris-KA** [immich-app/immich#2677] opened 2023-06-06 17:35 UTC
### The bug

When I try to open the select folders menu on the ios app to backup they just will not load, I only have this problem on an iphone 13 pro, samsung phones are working fine. The phone has around 10,000 photos but another with more uploaded fine. iCloud storage optimization is off and not sure what to do. Some of the photos are uploaded to icloud does that mean that it won't load?

Log: 
[Immich_log_2023-06-06T18_24_29.606833.csv](https://github.com/immich-app/immich/files/11667539/Immich_log_2023-06-06T18_24_29.606833.csv)

### The OS that Immich Server is running on

Docker in unraid

### Version of Immich Server

v1.60.0

### Version of Immich Mobile App

v1.60.0 build 100

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/phoneupload


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=some-random-text
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1. Open backup menu
2. Select photos menu
3. Doesn't load
```

**Comment by alextran1502** [comment] 2023-06-06 17:50
even thought storage optimization is off, are the files on the phone or are they still on iCloud?

**Comment by Harris-KA** [comment] 2023-06-06 19:35
Some are on the phone and some are on iCloud but the select folders to backup loads indefinitely, I don't mind about the icloud ones not backing up but no albums load.

**Comment by alextran1502** [comment] 2023-06-06 19:41
I haven't tested the situation where some files are on iCloud, and some are on the device. Would it be possible to download the files from iCloud back to your phone?

**Comment by alextran1502** [comment] 2023-06-06 20:32
Can you try to navigate back to the select album page to see if it loads? I sometimes run into state management bug that it doesn't update the list but navigating back to the backup page and then to the album selection page helped

**Comment by mike-lloyd03** [comment] 2023-06-08 22:07
I'm having the same issue with my wife's iPhone Xs. Tapping on "Backup Albums" produces and endlessly spinning spinner. Going to "Library", under "Albums on Device", nothing is listed. 

Force quitting the app or navigating backwards and forwards makes no difference. 

Some photos are on icloud and some are on device.

**Comment by Harris-KA** [comment] 2023-06-11 13:00
Sorry for the late reply, the photos are on the phone and iCloud. Is there anything else I can try

**Comment by 0fbcb238c0** [comment] 2023-06-20 13:11
I have the same issue, iCloud cannot be turned of, necause the phone does not have enough storage.

**Comment by alextran1502** [comment] 2023-06-20 13:58
> I have the same issue, iCloud cannot be turned of, necause the phone does not have enough storage.

@0fbcb238c0 Yeah I think this is the current limitation. Let's see if we can solve this issue by getting the file directly from iCloud in the future.

**Comment by mike-lloyd03** [comment] 2023-06-20 16:00
What I'm hoping to achieve with my wife's phone is to upload everything that is on her phone, delete those images, and then pull what it can from iCloud. Rinse and repeat until everything is backed up. But I'm blocked because I cannot pick a backup album at all right now.

**Comment by YeePongWong** [comment] 2023-06-25 03:27
same issue. upgraded to the latest ios and server, but there are still problems

**Comment by alextran1502** [comment] 2023-06-25 03:30
@YeePongWong What is your phone model?

**Comment by YeePongWong** [comment] 2023-06-27 05:59
> @YeePongWong What is your phone model?

iPhone13Pro and iOS16.2(20c65)

**Comment by bo0tzz** [comment] 2023-07-13 17:46
Is this a duplicate of #834?

**Comment by ndepaola** [comment] 2023-08-10 00:57
> What I'm hoping to achieve with my wife's phone is to upload everything that is on her phone, delete those images, and then pull what it can from iCloud. Rinse and repeat until everything is backed up. But I'm blocked because I cannot pick a backup album at all right now.

+1 for this issue - i'm in a similar situation where my phone (iPhone SE 2020) has a mixture of:

* images saved on iCloud where the full-res image is not stored on my phone
* images saved on iCloud where the full-res image happens to also be stored on my phone
* images which are not saved on iCloud (because it's full)

and i'm encountering the same problem where i cannot select any albums to backup because the loading spinner is shown indefinitely

**Comment by geoffgarside** [comment] 2023-08-14 21:07
I've got similar situation with my iPhone 13 Mini, I've managed to debug locally and found an error coming out which isn't being caught

```
[ImageManager] [RM]: 1-210-1 Image request failed with error: Error Domain=PHPhotosErrorDomain Code=3303 "No resource found matching image request spec" UserInfo={NSDebugDescription=No resource found matching image request spec}
```

It seems to be coming from https://github.com/immich-app/immich/blob/main/mobile/lib/modules/backup/providers/backup.provider.dart#L227-L228 when its hitting a file which seems to be in iCloud but is also corrupted. It seems when this case is hit, the `try/catch` doesn't stop the loop from bailing. Unfortunately I'm not that familiar with dart to offer any suggestions on how to resolve it.

**Comment by BigCheeZ** [comment] 2023-10-11 15:37
I have updated and no longer encounter this issue.

App Version: 1.80.0 build.120
Server Version: 1.81.1

**Comment by bo0tzz** [comment] 2023-10-11 16:09
Fixed by #3905

**Closed by bo0tzz** 2023-10-11 16:09 UTC
Labels: bug, need triage, 📱mobile, platform:ios

**Comment by mike-lloyd03** [comment] 2023-10-27 05:31
I'm still having this issue on 1.82.0 build.121.

**Comment by dh91779** [comment] 2024-02-24 17:05
I am having this issue on an iPhone 11 Pro Max version 17.2.1. Spinning loading screen when trying to backup or search for folders
