### ISSUE TITLE
[BUG] Thumbnails missing on recently uploaded files

### ISSUE THREAD

**Issue by jalin2** [immich-app/immich#3100] opened 2023-07-03 15:40 UTC
### The bug

For the recently uploaded photos it seems like the thumbnails are not being generated.  When I try to generate the thumbnails manually through the job-->generate thumbnails, it doesn't seem to be working either (shows 1 active but nothing happening).  In the past I've encountered something similar and when I restart the immich docker stack it would work again.  However, this time around I've restarted a handful of times with no success.

From jobs it is reporting 5 errors:
![image](https://github.com/immich-app/immich/assets/56244277/cffd3693-7258-436b-940a-89ee845cb00e)

The logs from the microservice container shows the following error:
![image](https://github.com/immich-app/immich/assets/56244277/54bbf6eb-f82b-440c-bbda-8c3829463f7f)

### The OS that Immich Server is running on

Ubuntu 22.04.2

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

v1.65.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    #depends_on:
    #  - database
    restart: always
    deploy:
      placement:
        constraints: [node.labels.host-speed == fast]

  immich-web:
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    environment:
      # Rename these values for svelte public interface
      - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /mnt/dfs/fast-pool/docker-data/immich/tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    #image: redis:6.2
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    #image: postgres:14
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /mnt/dfs/fast-pool/docker-data/immich/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    #logging:
    #  driver: none
    depends_on:
      - immich-server
      - immich-web
    restart: always

#volumes:
#  pgdata:

#use a global network called docker-lan so services can see each other
networks:
  default:
    external:
      name: docker-lan
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

#DB_HOSTNAME=immich_postgres
DB_HOSTNAME=database
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

#REDIS_HOSTNAME=immich_redis
REDIS_HOSTNAME=redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/mnt/dfs/ecpool-hdd/fam_docs/Pictures/immich

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=simple

###################################################################################
# JWT SECRET
###################################################################################

# This JWT_SECRET is used to sign the authentication keys for user login
# You should set it to a long randomly generated value
# You can use this command to generate one: openssl rand -base64 128
JWT_SECRET=some_key_i_changed_for_github_issue

###################################################################################
# Typesense
###################################################################################
#TYPESENSE_API_KEY=some-random-text
TYPESENSE_API_KEY=ThisIsMyKey
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
####################################################################################

DISABLE_REVERSE_GEOCODING=false

# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM

REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
####################################################################################

# Custom message on the login page, should be written in HTML form.
# For example PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"

PUBLIC_LOGIN_PAGE_MESSAGE="Immich on Jamella domain"

####################################################################################
# Alternative Service Addresses - Optional
####################################################################################

# This is an advanced feature for users who may be running their immich services on different hosts. It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001


###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```

### Reproduction steps

```bash
1. Deploy immich stack as per docker-compose.yml
2. Thumbnails will be missing.  Click on administration->Jobs->"Missing" for Generate Thumbnails

...
```

### Additional information

I am using docker stack to deploy immich

**Comment by jalin2** [comment] 2023-07-03 15:51
Here is a screenshot of what my timeline looks like
![image](https://github.com/immich-app/immich/assets/56244277/7aa6ac53-36bb-42b6-8784-cf6176f46ab0)

**Comment by alextran1502** [comment] 2023-07-03 16:27
Can you bring down the stack, make sure to remove the `redis` container. Then bring the stack backup and run the thumbnail generation job again?

**Comment by alextran1502** [comment] 2023-07-03 16:29
@jrasm91 Any thoughts on the error message, looks like `registerHandlers` failed somehow

**Comment by jrasm91** [comment] 2023-07-03 16:31
It looks like it is processing a job that doesn't exist in the mapping, which should not be possible. One possibility, like you mentioned is an old job name that is still in redis. Re-creating that container would be a likely fix for the issue.

**Comment by jrasm91** [comment] 2023-07-03 16:32
> @jrasm91 Any thoughts on the error message, looks like `registerHandlers` failed somehow

The method `registerHandlers` itself was successful, but the incoming job name isn't in the mapping. Very strange.

**Comment by jalin2** [comment] 2023-07-03 17:19
Wow, thanks for replying so quickly and with a suggestion!

After removing redis from the stack the thumbnails got generated automatically without me triggering it.  After removing redis, the log microservices log file shows the following:
![image](https://github.com/immich-app/immich/assets/56244277/454d3812-b183-4317-8e6c-44610e300266)

I'm not sure if "upload/upload/..." is the proper path.  When I checked for the 2 files assuming a single "upload" in the path I can confirm those files do not exist.

Shall I keep redis off the stack for now?  Please let me know if there's anything else I can provide to help.

Much appreciated!

**Comment by jrasm91** [comment] 2023-07-03 17:53
Redis is needed/essential to immich working properly. We really just wanted it to be re-created since there was a possibility of old/outdated data in there still. You should be able to add it back now, if you haven't already. I think the original error is fixed, but it looks like you might have another issue.

`upload/upload` is actually correct. Internally (on the docker container) `UPLOAD_LOCATION` maps to `/usr/src/app/upload`. `UPLOAD_LOCATION/upload` then becomes `/usr/src/app/upload/upload.

**Comment by justuspfaue** [comment] 2023-07-08 21:04
I have the same problem when trying to generate Thumbnails for my RAW Image collection consisting of .cr3 files. My deployment is using v1.66.1 on a new Helm deployment. I get the following error a few hundred times in my microservice container:
```
[Nest] 8  - 07/08/2023, 8:58:40 PM   ERROR [JobService] Unable to run job handler: Error: Input file has corrupt header: magickload: Magick: improper image header `upload/library/30d53d9d-baa1-44cf-a0bb-ae2aa7e38abe/2023/2023-05-28/IMG_1017.cr3' @ error/tga.c/ReadTGAImage/239 (null)

[Nest] 8  - 07/08/2023, 8:58:40 PM   ERROR [JobService] Error: Input file has corrupt header: magickload: Magick: improper image header `upload/library/30d53d9d-baa1-44cf-a0bb-ae2aa7e38abe/2023/2023-05-28/IMG_1017.cr3' @ error/tga.c/ReadTGAImage/239 (null)

[Nest] 8  - 07/08/2023, 8:58:40 PM   ERROR [JobService] Object:
{
  "id": "4375986e-3946-4a7d-a7be-484d614a80cf"
}
```

One thing to note, when I uploaded my files they all had the file extension .CR3 while it now is .cr3.

Is this expected behaviour? If you need more information I will gladly provide them.

**Comment by skaylenovo** [comment] 2023-07-19 14:04
Facing same issue on the web-interface and android as well. Please help me to fix this.

**Comment by alextran1502** [comment] 2023-07-19 15:06
@skaylenovo Please make sure the USB HDD mount is accessible on your server. In the log I see this 

```
[Nest] 1  - 07/19/2023, 2:09:32 PM   ERROR [JobService] Unable to run job handler: Error: upload/thumbs/db35d2a9-acec-4ad7-9ad7-b45eb0a24e69/27c7a1e7-4c59-4b32-b5c6-455df06da3ca.jpeg: unable to open for write
unix error: No space left on device
```

The no space left on the device indicates that your mount might not be mounted correctly.

**Comment by skaylenovo** [comment] 2023-07-19 15:09
Hi @alextran1502 : I have verified it to be mounted properly. As you can see below:

Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
tmpfs           1.6G  3.7M  1.6G   1% /run
/dev/sda6        59G   17G   39G  30% /
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           5.0M  8.0K  5.0M   1% /run/lock
/dev/sda2        95M   33M   63M  35% /boot/efi
/dev/sdb1       466G   21G  446G   5% /mnt/sdb1
tmpfs           1.6G   80K  1.6G   1% /run/user/114
tmpfs           1.6G   72K  1.6G   1% /run/user/1000


Free space is 95% too.

**Comment by skaylenovo** [comment] 2023-07-19 15:33
Hi @alextran1502 ,

Did you mean this?:

/usr/src/app # ls
bin                     node_modules            package.json            start-server.sh         upload
dist                    package-lock.json       start-microservices.sh  start.sh
/usr/src/app # cd upload/
/usr/src/app/upload # ls
encoded-video  library        thumbs         upload
/usr/src/app/upload # cd upload/
/usr/src/app/upload/upload # ls
bb029a9e-3c52-4ee7-b086-1404832be92b  db35d2a9-acec-4ad7-9ad7-b45eb0a24e69

**Comment by skaylenovo** [comment] 2023-07-19 17:16
![image](https://github.com/immich-app/immich/assets/139987078/4cc22429-276b-48d2-8c14-83f2282166c4)

Please refer

**Comment by alextran1502** [comment] 2023-07-19 17:53
@skaylenovo looks good - what happen if you run thumbnail generation jobs for the missing one?

**Comment by skaylenovo** [comment] 2023-07-19 18:17
Whenever I run the job, it completes without any issue. I tried following:

1. Changed Job concurrency
2. Disabled Redis section (however it restricted me to load the webpages correctly)
3. Rebooted containers multiple times.

Note that while downloading these images, they appear to be fine after download, the issue is only with the thumbnails.
I am even not able to view the images after clicking on them.

![image](https://github.com/immich-app/immich/assets/139987078/d46325e4-cfc6-46c0-9c24-b1ecc7b93c2e)

**Comment by alextran1502** [comment] 2023-07-19 18:24
@skaylenovo you will need Redis in order to generate the thumbnails

**Comment by skaylenovo** [comment] 2023-07-19 18:48
Yes, hence it was re-enabled, still no progress

**Comment by alextran1502** [comment] 2023-07-20 02:20
@skaylenovo Can you head over to discord so we can help troubleshoot this faster and easier?

**Comment by bo0tzz** [comment] 2023-07-20 14:56
The discord is at https://discord.com/invite/D8JsnBEuKb

**Comment by bt90** [comment] 2023-07-21 09:47
Please make sure that you're not running out of inodes:

```sh
df -i
```

**Comment by skaylenovo** [comment] 2023-07-21 14:41
> Please make sure that you're not running out of inodes:
> 
> ```shell
> df -i
> ```

Hi @bt90 , This is the situation, how to mitigate this?:

Filesystem      Inodes  IUsed   IFree IUse% Mounted on
udev           2008079    516 2007563    1% /dev
tmpfs          2016449   1262 2015187    1% /run
/dev/sda6      3907584 403887 3503697   11% /
tmpfs          2016449      1 2016448    1% /dev/shm
tmpfs          2016449      4 2016445    1% /run/lock
/dev/sda2            0      0       0     - /boot/efi
/dev/sdb1            0      0       0     - /mnt/sdb1
tmpfs           403289     92  403197    1% /run/user/114
tmpfs           403289     81  403208    1% /run/user/1000

**Comment by skaylenovo** [comment] 2023-07-21 14:46
I have checked this article and it says that it might be fine with having zero inodes with FS that are not inbuilt for Linux OS. Refer:

https://superuser.com/questions/647343/zero-inodes-even-after-formatting-hard-disk

**Comment by skaylenovo** [comment] 2023-07-21 14:47
I am facing same issue even after re-uploading the corrupted files. These files are perfectly fine at the source.

**Comment by bt90** [comment] 2023-07-21 14:55
Inodes are looking good

**Comment by jrasm91** [comment] 2023-08-18 03:08
The original issue has been resolved by restarting redis.

For other issues, please open a separate bug report.

**Closed by jrasm91** 2023-08-18 03:08 UTC
Labels: bug, need triage
