### ISSUE TITLE
[BUG] Images not loading on search

### ISSUE THREAD

**Issue by maxrye1996** [immich-app/immich#3007] opened 2023-06-28 14:15 UTC
### The bug

Hello, i have been testing the semantic search and noticed it doesn't return images when you first search:
![image](https://github.com/immich-app/immich/assets/28844671/9ffc9e8e-ae47-42f8-8965-3c96b3f0e321)
If i scroll down and scroll back up they appear, or if i refresh the page they also appear. This screenshot is from the demo site:
https://demo.immich.app/search?q=purple+flower+with+green+background&clip=true

It only seems to happen when you are already on the search page and you search again

### The OS that Immich Server is running on

DEMO

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A, using the demo site
```

### Your .env content

```Shell
N/A, using the demo site
```

### Reproduction steps

```bash
1.Go to the demo site
2.Search "purple flower with green"
3.Change the search to "purple flower with green background"
```

### Additional information

I am also getting this on my instance, i am assuming you have access to the compose files and env files used on the demo site. If not i can provide my compose and env files later.

**Comment by alextran1502** [comment] 2023-06-28 14:17
Confirmed on my own site. @michelheusschen Do you have any idea why sometimes the loading progress doesn't get triggered for some images?

**Comment by uhthomas** [comment] 2023-06-28 22:15
> Confirmed on my own site. @michelheusschen Do you have any idea why sometimes the loading progress doesn't get triggered for some images?

I saw this too. Usually scrolling them out of view and back in will fix it.

**Comment by jrasm91** [comment] 2023-08-18 03:11
Duplicate of #3073

**Closed** 2023-08-18 03:11 UTC
Labels: bug, 🖥️web
