### ISSUE TITLE
[FEATURE] Try /api when people enter just a hostname into the server field.

### ISSUE THREAD

**Issue by shadow7412** [immich-app/immich#921] opened 2022-11-04 02:08 UTC
It's not very intuitive to have to enter the full url, rather than just the hostname when logging into the app.

May I suggest the app automatically try `/app` if the initial connection fails? That way we won't be breaking compatibility in case people have it forwarded that way (for some reason) but the barrier for entry get slightly lowered for those who wish to use the server.

**Comment by bo0tzz** [comment] 2022-11-04 09:48
Duplicate of #614

**Closed** 2022-11-04 09:48 UTC
Labels: good first issue, feature, nice to have
