### ISSUE TITLE
Logout slow and/or unsuccessful if disconnected from Server

### ISSUE THREAD

**Issue by robajr** [immich-app/immich#14022] opened 2024-11-08 17:21 UTC
### The bug

Attempting to logout failed multiple times, and in other cases took over 5 seconds, when not connected to the server attempting to log out from. iOS

### The OS that Immich Server is running on

Ubuntu 24.04 - Docker

### Version of Immich Server

v1.20.0

### Version of Immich Mobile App

v1.20.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not relevant to reproduction
```

### Your .env content

```Shell
Not relevant to reproduction
```

### Reproduction steps

Easiest reproduction

1. Log onto immich local IP
2. Disconnect wifi
3. Log out

### Relevant log output

```shell
2024-11-08 09:18:43.046497 | FINE     | socket_io_client:engine.Socket | socket closing - telling transport to close |
2024-11-08 09:18:43.046479 | FINE     | socket_io_client:Manager | cleanup |
2024-11-08 09:18:43.046469 | FINE     | socket_io_client:Manager | onclose |
2024-11-08 09:18:43.046441 | FINE     | socket_io_client:engine.Socket | socket close with reason: "forced close" |
2024-11-08 09:18:43.046192 | FINE     | socket_io:parser.Encoder | encoded {type: 2, data: [disconnecting, io client disconnect], options: {compress: false}, nsp: /} as 2["disconnecting","io client disconnect"] |
2024-11-08 09:18:43.046157 | FINE     | socket_io:parser.Encoder | encoding packet {type: 2, data: [disconnecting, io client disconnect], options: {compress: false}, nsp: /} |
2024-11-08 09:18:43.046142 | FINE     | socket_io_client:Manager | writing packet {type: 2, data: [disconnecting, io client disconnect], options: {compress: false}, nsp: /} |
2024-11-08 09:18:43.046118 | FINE     | socket_io_client:Socket | close (io client disconnect) |
2024-11-08 09:18:43.046096 | FINE     | socket_io_client:Manager | disconnect |
2024-11-08 09:18:43.045474 | FINE     | socket_io_client:engine.Socket | flushing 1 packets in socket |
2024-11-08 09:18:43.045456 | FINE     | socket_io:parser.Encoder | encoded {type: 1, nsp: /} as 1 |
2024-11-08 09:18:43.045421 | FINE     | socket_io:parser.Encoder | encoding packet {type: 1, nsp: /} |
2024-11-08 09:18:43.045407 | FINE     | socket_io_client:Manager | writing packet {type: 1, nsp: /} |
2024-11-08 09:18:43.045369 | FINE     | socket_io_client:Socket | performing disconnect (/) |
2024-11-08 09:18:43.039240 | SEVERE   | AuthenticationNotifier | Logout failed for rob@alls.house | ApiException 400: HTTP connection failed: POST /auth/logout (Inner exception: ClientException: Operation timed out, uri=http://192.168.0.99:2283/api/auth/logout)

#0      IOClient.send (package:http/src/io_client.dart:156)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      ApiClient.invokeAPI (package:openapi/api_client.dart:96)
<asynchronous suspension>
#3      AuthenticationApi.logout (package:openapi/api/authentication_api.dart:140)
<asynchronous suspension>
#4      AuthenticationNotifier.logout.<anonymous closure> (package:immich_mobile/providers/authentication.provider.dart:105)
<asynchronous suspension>
#5      AuthenticationNotifier.logout (package:immich_mobile/providers/authentication.provider.dart:103)
<asynchronous suspension>
#6      ImmichAppBarDialog.build.buildSignOutButton.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:immich_mobile/widgets/common/app_bar_dialog/app_bar_dialog.dart:118)
<asynchronous suspension>
 |
#0      ApiClient.invokeAPI (package:openapi/api_client.dart:125)
<asynchronous suspension>
#1      AuthenticationApi.logout (package:openapi/api/authentication_api.dart:140)
<asynchronous suspension>
#2      AuthenticationNotifier.logout.<anonymous closure> (package:immich_mobile/providers/authentication.provider.dart:105)
<asynchronous suspension>
#3      AuthenticationNotifier.logout (package:immich_mobile/providers/authentication.provider.dart:103)
<asynchronous suspension>
#4      ImmichAppBarDialog.build.buildSignOutButton.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:immich_mobile/widgets/common/app_bar_dialog/app_bar_dialog.dart:118)
<asynchronous suspension>
```

**Comment by mmomjian** [comment] 2024-11-08 17:26
Thank you, Duplicate of #13886

**Closed by mmomjian** 2024-11-08 17:26 UTC

**Comment by robajr** [comment] 2024-11-08 19:02
Sorry, I should have looked much closer.
