### ISSUE TITLE
Web UI: File Upload Notification Blocks Upload Progress

### ISSUE THREAD

**Issue by TransRapid** [immich-app/immich#9948] opened 2024-06-02 19:28 UTC
### The bug

**Actual Behavior:**
The upload progress will be blocked and overlapped by countless notifications if you have a lot of files being uploaded quickly as the notifications persist too long. There is no way to see the progress, and progress is gone by the time all notifications clear if you have a lot of very small files uploading on a fast connection. UI is not responsive in any way, and even on very large high resolution displays this issue occurs.

![Screenshot 2024-06-02 at 12 00 28](https://github.com/immich-app/immich/assets/17062688/ac3e9043-fe7e-4c1b-ba4b-bf63e98b6e6b)

**Expected Behavior:**
Upload notifications are first displayed starting above the progress indicator, or to the left of a fixed location upload progress area. Notifications should not obstruct the view of overall progress, and UI should be responsive to window size if needed.

### The OS that Immich Server is running on

Debian Bookworm 6.1.0-17-amd64

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A Running In Python Venv
```

### Your .env content

```Shell
N/A Running In Python Venv
```

### Reproduction steps

```bash
1. Create Album
2. Upload many smaller files on a fast connection at once via drag/drop.
```

### Relevant log output

```shell
N/A UI Rendering; CSS/HTML
```

### Additional information

Sample data set was about (800) 2MB files uploading on a 1GB fiber line. Display is 2056x1329, but also tested on 4K resolution, and downsized window to 1080.

**Alternative Option:**
Displays lacking resolution have a fixed progress bar at the bottom that is interactive, and can expand, or unroll to display more details of upload progress and speed. When downsized it displays a simple progress indication bar that is 0%-100% and the width of the screen being used.

Additionally, at the top of the window a similar notification bar exist, and shows the last file uploaded, even if it only displays for fractions of a second due to upload speed. When activated, a larger window rolls down and can show all files uploaded and any related stats.

**Comment by bo0tzz** [comment] 2024-06-02 19:32
Duplicate of #6102. Thank you for the high quality report though!

**Closed by bo0tzz** 2024-06-02 19:32 UTC

**Comment by TransRapid** [comment] 2024-06-02 19:35
Thanks, I uploaded a video as well for reference. I might play with it myself to see what can be done.
