### ISSUE TITLE
Immich doesn't expect changes to image

### ISSUE THREAD

**Issue by ajpanton** [immich-app/immich#11340] opened 2024-07-24 20:24 UTC
### The bug

I have the "Watch external libraries for file changes" setting turned on. It nicely reacts to changes made to the image metadata, but Immich doesn't seem to react well to changes made to the image itself.

If the resolution/aspect ratio changes, it seems to somehow redo the thumbnail, but apparently not from the actual image file? Not really sure. The aspect ratio of the thumbnail will be correct, but what it's actually showing isn't necessarily correct. Maybe it just keeps the previous thumbnail, but tries to display it in the new aspect ratio? 180-degree rotations, flips, or color changes just get ignored, because the dimensions stay the same. It looks weird when you see an old preview, but when zooming, it suddenly switches to the new image. You can manually refresh the thumbnails though I guess.

Any detected faces stay where they originally were. They are correct on the old preview, but zooming to get the new image, they are in the wrong places. And when refreshing the thumbnails (and preview), the faces are still in the old places.

### The OS that Immich Server is running on

Truenas SCALE app

### Version of Immich Server

v1.109.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Reproduction steps

```bash
1. Edit or color correct any image.
2. Watch the thumbnails and previews not changing at all (thumbnails might change in a buggy way if the aspect ratio changed).
3. Manually refresh the thumbnails. Any detected faces are still in the wrong places, assuming you edited the image in a way that would move them around (crop, rotate, flip).
```

**Comment by aviv926** [comment] 2024-07-25 19:47
Can confirm the bug on my side as well.

**Comment by danieldietzler** [comment] 2024-09-23 18:49
Hey, most likely this is a caching issue. Did you make sure to clear the browser cache? 
<img width="919" alt="Screenshot 2024-09-23 at 20 49 07" src="https://github.com/user-attachments/assets/ada5a0e9-0b8c-452e-96e0-2c00071bfcbd">
https://immich.app/docs/features/libraries

**Comment by etnoy** [comment] 2024-10-07 19:36
Closing this for now as it's a known, documented issue

**Comment by etnoy** [comment] 2024-10-07 19:36
Duplicate of #6955

**Closed by etnoy** 2024-10-07 19:36 UTC
