### ISSUE TITLE
albums should use smaller thumbnails

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich#3019] opened 2023-06-28 22:43 UTC
### The bug

Albums use jpeg thumbnails, which for some reason are ginormous compared to webp. There is no need to use a thumbnail with a resolution of 2161x1440 for albums.

https://github.com/immich-app/immich/blob/86562f256f715154e852e0113a05f6a062c858c0/server/src/domain/media/media.constant.ts#L1-L2

Related? #2749

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by jrasm91** [comment] 2023-08-27 19:09
Albums use the asset grid component now which uses webp thumbnails like the main timeline. Unless I am misunderstanding the issue this has been fixed now.

**Closed by jrasm91** 2023-08-27 19:09 UTC
Labels: bug, need triage

**Comment by uhthomas** [comment] 2023-08-27 19:32
> Albums use the asset grid component now which uses webp thumbnails like the main timeline. Unless I am misunderstanding the issue this has been fixed now.

This isn't to do with the album view, but the actual album thumbnail itself.

**Comment by jrasm91** [comment] 2023-08-27 21:32
Ok, might be good to update the issue to be more clear/specific in that case.

The album view loads webp initially and then lazy loads the higher jpegs afterwards, which I think is fine. They look better imo.

**Comment by uhthomas** [comment] 2023-08-27 22:34
To make sure we're on the same page - this view, right? There is no need to use a 2k image for a 300px element.

<img width="993" alt="Screenshot 2023-08-27 at 23 32 16" src="https://github.com/immich-app/immich/assets/9749173/add1b3fa-3002-4588-a2bb-1939e4a6e470">

**Comment by jrasm91** [comment] 2023-08-27 23:02
High res ones are lazy loaded, which is fine imo.

https://github.com/immich-app/immich/blob/main/web/src/lib/components/album-page/album-card.svelte#L17-L42

**Comment by uhthomas** [comment] 2023-08-28 00:58
I'm not so sure. It's not free to do this - it's additional bandwidth and has a performance impact on some platforms. We should really be displaying a more appropriate size like 300px for a 300px element rather than 2k, which is absurdly huge.

**Comment by jrasm91** [comment] 2023-08-28 03:10
You can ask @alextran1502 if he wants to remove the code to load the jpegs. It is working as intended and designed regardless if you think it is correct or not. I don't have an opinion if we keep the high quality thumbnails or only use the webp ones for what it is worth. The whole thumbnail solution will probably need to be revamped in the future, but that is an entirely separate issue and discussion, and certainly not something best described as a bug. There is no action item to take here unless we decide to revert the code that loads the high resolution thumbnail. That was added before my time and I am unaware of the circumstances and thought process around why it was added.
