### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by hairy-tortoise** [immich-app/immich#1876] opened 2023-02-25 23:08 UTC
### The bug

I just installed the app from F-Droid and when I open it it just shows the logo with black background and nothing happens

### The OS that Immich Server is running on

-

### Version of Immich Server

-

### Version of Immich Mobile App

1.49.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Install the app from F-Droid
2. Open it
```

### Additional information

Android 13

**Comment by Eyap53** [comment] 2023-02-26 02:19
Duplicate of #1815

**Closed** 2023-02-26 03:20 UTC
Labels: bug, need triage
