### ISSUE TITLE
Immich labelling photo locations taken near a country border inaccurately.

### ISSUE THREAD

**Issue by ddpruel** [immich-app/immich#11926] opened 2024-08-20 03:17 UTC
### The bug

When labelling locations in a photo taken near the border of the USA (but definitively in a Canadian city), immich labels the photo as being in the corresponding US city. 

### The OS that Immich Server is running on

Docker on Mac

### Version of Immich Server

Latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
As an example:
This can be replicated by uploading a photo with GPS coordinates near the Detroit River in Windsor, Ontario (which has a river border with the US). 

ex) lat: 42.2084833333333 long: -83.0980527777778
```

**Comment by mmomjian** [comment] 2024-08-20 03:42
Thanks. This is a duplicate of #9674. Currently, place naming is based on the closest populated city/town. This may be changed in the future.

**Closed by mmomjian** 2024-08-20 03:42 UTC
