### ISSUE TITLE
Going back to search results from a fullscreen-displayed photo - always returns to the start of the search results list

### ISSUE THREAD

**Issue by dariuszszyc** [immich-app/immich#9347] opened 2024-05-09 07:24 UTC
### The bug

App moves to the beginning of the search results when returning from a clicked photo.

### The OS that Immich Server is running on

not-relevant

### Version of Immich Server

1.103.1

### Version of Immich Mobile App

latest

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not-relevant
```

### Your .env content

```Shell
not-relevant
```

### Reproduction steps

```bash
1. Use the search functionality to find some photos.
2. Scroll down a bit and click any photo - it will open full screen
3. Now you want to return to the list to click another photo you saw next to the previous one - so you click "back/arrow" button on the top left
4. As a result - you are back to the top of the search results list and you have to scroll down again to the place where you were.

It makes it hard to use the searching functionality as every time you click a photo and return - you have to start from the top.

On mobile - when you return from a fullscreen photo display - you are still in the place where you were, seeing the photo that you just clicked.
```

**Comment by nick-roux** [comment] 2024-05-09 18:46
Seeing the same issue on 1.103.1.

**Comment by danieldietzler** [comment] 2024-05-20 10:47
Duplicate of #6052

**Closed by danieldietzler** 2024-05-20 10:47 UTC
