### ISSUE TITLE
[BUG] [Web] Deleting an image from an album causes a soft freeze

### ISSUE THREAD

**Issue by thariq-shanavas** [immich-app/immich#5527] opened 2023-12-07 08:08 UTC
### The bug

When a photo is opened from the timeline and deleted, the web app shows a notification that the item was moved to trash and switches to the next photo. 

However, the web app locks up when a picture is opened from an album and deleted. The left/right arrows do not work, and the next item is not shown. The back button on the top left works and takes you back to the album view.

This is a minor annoyance at best, but I'm making an issue so it does not get lost.

I have confirmed this behavior on the demo instance. Tested using Firefox and Chrome browsers.

### The OS that Immich Server is running on

NA

### Version of Immich Server

1.89.0

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Open an album with at least two pictures
2. Open a picture
3. Delete it from the button on the top right
4. The next photo is not shown, the left/right buttons stop working.
```

**Comment by flyotlin** [comment] 2023-12-13 07:35
If you click next (arrow right) when you're on the last image in the album, this kind of error/soft freeze happens as well.
Seems like it's that the variable `asset` in [here](https://github.com/immich-app/immich/blob/main/web/src/lib/components/asset-viewer/asset-viewer.svelte#L79) would be undefined.

**Comment by jrasm91** [comment] 2024-01-22 03:36
I remember seeing this issue in the past, but I was not able to reproduce it, so I think it must have been fixed in the interim already.

**Closed by jrasm91** 2024-01-22 03:36 UTC
Labels: bug
